### ISSUE TITLE
定制化显示Label信息

### ISSUE THREAD

**Issue by geekyzk** [hustcc/echarts-for-react#100]
例如在阶梯瀑布图中,数据是这样的
`
 series: [
                {
                    name: '辅助',
                    type: 'bar',
                    stack: '总量',
                    itemStyle: {
                        normal: {
                            barBorderColor: 'rgba(0,0,0,0)',
                            color: 'rgba(0,0,0,0)'
                        },
                        emphasis: {
                            barBorderColor: 'rgba(0,0,0,0)',
                            color: 'rgba(0,0,0,0)'
                        }
                    },
                    data: [0, 900, 1245, 1530, 1376, 1376, 1511, 1689, 1856, 1495, 1292]
                },
                {
                    name: '收入',
                    type: 'bar',
                    stack: '总量',
                    label: {
                        normal: {
                            show: false,
                            position: 'top'
                        }
                    },
                    data: [900, 345, 393, '-', '-', 135, 178, 286, '-', '-', '-']
                },
                {
                    name: '支出',
                    type: 'bar',
                    stack: '总量',
                    label: {
                        normal: {
                            show: true,
                            position: 'bottom'
                        }
                    },
                    data: ['310', '-', '-', 108, 154, '-', '-', '-', 119, 361, 203]
                }
            ]
        };
`
我这样搞就变成叠加柱状图了，我能通过定制显示label的信息么？例如显示指出支出的信息为支出占总量的百分比。

![image](https://user-images.githubusercontent.com/21106445/30011086-4c3d4a18-9167-11e7-9d27-7b6df646237a.png)
例如310 定制化显示成总柱状图的百分比

**Comment by hustcc** [comment]
这个可以看 echarts 的官方文档，可以解决的。

**Comment by geekyzk** [comment]
嗯呢，已经解决了
在2017年09月4日 12:46，hustcc<notifications@github.com> 写道：

这个可以看 echarts 的官方文档，可以解决的。
