### ISSUE TITLE
按照代码示例，引入组件以后浏览器报warning  页面没有展示效果，请帮忙看看，谢谢！

### ISSUE THREAD

**Issue by zteBill** [hustcc/echarts-for-react#101]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Statistics`.

**Comment by SidKwok** [comment]
代码看一下

**Comment by zteBill** [comment]
是我import的有问题  只看展示用例 下面的代码了  没仔细看文档使用用例，谢谢！ @SidKwok
