### ISSUE TITLE
我打算直接用echartsforreact中的core.js，修改一下

### ISSUE THREAD

**Issue by daxiong-liang** [hustcc/echarts-for-react#103]
如题，因为我想用的echarts2版本，而这个项目支持的是3，我打算改成可以适应2的，以后有可能会发布到github这边，但是会有版权纠纷，想问一下我能否直接改用作者的源码，并发布到相关平台中

**Comment by hustcc** [comment]
没有问题，如果能直接发送 pr 兼容 echarts 2 和 3 是最好的！

**Comment by daxiong-liang** [comment]
如果要兼容echarts 2的话，你的44行可以改成this.echartsInstance.getInstanceById,而echarts对象里面有version版本号，
我现在基本采用你的代码，将44行改为上面那个，就可以用echarts 2了，如果你想兼容2和3，应该需要对版本进行判断，以便使用getInstanceById
还是getInstanceByDom就好~
还有就是componentWillUnmount里面，this.echartsInstance.dispose(this.echartsElement);我建议改成
const echartObj = this.renderEchartDom();
echartObj.dispose(this.echartsElement);
原有的写法我会报错，不知道你这边会不会

**Comment by hustcc** [comment]
不会，如果可以兼容的话，就建议大一个 pr吧😄

**Comment by daxiong-liang** [comment]
迟下自己试试先 
:smile:
