### ISSUE TITLE
在react中，用setState设置新的theme的时候，不起作用

### ISSUE THREAD

**Issue by bangcodes** [hustcc/echarts-for-react#104]
`  handleChangeTheme(e, { checked }) {
    if (checked === true) {
      this.setState({ theme: 'dark' })
    } else {
      this.setState({ theme: 'shine' })
    }
  }`

`        <ReactEcharts
            notMerge={true}
            option={chartOption}
            className='react_for_echarts'
            theme={theme}
        />
`

**Comment by hustcc** [comment]
这个是一个很好的问题，echarts 本身并没有提供 setTheme 方法，如果要修改主题，需要将原来的实例销毁，然后创建一个新的实例。

感觉这个是 echarts 官方应该优化的地方。

**Comment by hustcc** [comment]
https://github.com/ecomfe/echarts/issues/6580 可以参考这里，如果这里解决之后，本项目将会支持这个特性。
