### ISSUE TITLE
在饼图中无法设置 legend 滚动

### ISSUE THREAD

**Issue by lenzzz** [hustcc/echarts-for-react#106]
官方实现的例子：http://echarts.baidu.com/gallery/editor.html?c=pie-legend&edit=1&reset=1

失效的api : legend.type = 'scroll'

**Comment by SidKwok** [comment]
把echarts升级到[3.7.0](https://github.com/ecomfe/echarts/releases/tag/3.7.0)，这个是新的属性值

**Comment by lenzzz** [comment]
@SidKwok 升级版本后已解决  thx
