### ISSUE TITLE
是BUG吗》？

### ISSUE THREAD

**Issue by ZenSnail** [hustcc/echarts-for-react#107]
webpack打包报错：
index.js:59402 ./~/echarts-for-react/lib/index.js
Module not found: Error: Can't resolve 'echarts' in 'D:\PHPnow-1.5.6\htdocs\coralfrontend_proj\trunk\comment_safe\node_modules\echarts-for-react\lib'

index。js 第7行，var _echarts = require('echarts'); 找不到。我这报错呢？

**Comment by SidKwok** [comment]
试试
```
npm install echarts --save
```

**Comment by RinNguyens** [comment]
> 试试
> 
> ```
> npm install echarts --save
> ```

<3 many tks
