### ISSUE TITLE
Using function for the tooltip.formatter parameter

### ISSUE THREAD

**Issue by abhaychitnis** [hustcc/echarts-for-react#109]
I am using React v16.0.0 and echarts-for-react 2.0.0.

I am having problems in using function inside tooltip.formatter. I get following error
![image](https://user-images.githubusercontent.com/28629632/31489225-a6edac14-af5d-11e7-9e4e-d32794d356ae.png)

 My option object looks like this.

```
			title: {
				text: 'Time Line'
			},
			tooltip: {
				trigger: 'axis',
				formatter: function(params) {
					const param = params[0];
					const date = new Date(param.name);
					return (date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + param.value[1])	
				},
				
				axisPointer: {
					animation: false
				}
			},
			xAxis: {
				type: 'time',
				splitLine: {
					show: false
				}
			},
			yAxis: {
				type: 'value',
				boundaryGap: [0, '100%'],
				splitLine: {
					show: false
				}
			},
			series: [{
				name: 'Test Series',
				type: 'line',
				showSymbol: false,
				hoverAnimation: false,
				data: ''
			}]

```
The problem remain if I use an arrow function like this : 

```
				formatter: (params) => {
					const param = params[0];
					const date = new Date(param.name);
					return (date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + param.value[1])	

				},
```
I get a message like this:

![image](https://user-images.githubusercontent.com/28629632/31489522-8ce807e6-af5e-11e7-9427-300f0ce075b8.png)

What am I doing wrong ?

**Comment by SidKwok** [comment]
I think this issue is caused by your configuration files like `.babelrc` and `webpack.config.js`. Use [create-react-app](https://github.com/facebookincubator/create-react-app) to test your option.

**Comment by abhaychitnis** [comment]
This app was created using create-react-app

**Comment by SidKwok** [comment]
But I can't see any error with your option using create-react-app.

**Comment by abhaychitnis** [comment]
I have other functionalities (not related to echarts ) in the same app using in-line functions as well as arrow functions. These work fine.

**Comment by hustcc** [comment]
@abhaychitnis whether the issue has been fixed?

**Comment by abhaychitnis** [comment]
No the issue is not fixed. There is workaround available. I am using an external function instead of in-line function as follows:
```
  formatFunction = (params) => {
	const param = params[0];
	var date = new Date(param.value[0]);
	return date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + param.value[1];
 }

```
I am using this external function to set the formatter parameter as follows : 
`
option.tooltip.formatter = this.formatFunction;
`
This workaround works

**Comment by hustcc** [comment]
```js
formatter: function (params) {
					const param = params[0];
					const date = new Date(param.name);
					return (date.getDate() + '/' + (date.getMonth() + 1) + '/' + date.getFullYear() + ' : ' + param.value[1])	

				},
```

Can it be available  by writing it with es5 style, if can, maybe the problem of config be babel.

**Comment by abhaychitnis** [comment]
Yes this works.

**Comment by hustcc** [comment]
So check your `webpack`, `babel` config.

**Comment by EfkanKnz** [comment]
If you want to use arrow function, try like this:
```
chartOption: EChartOption = {
  tooltip: {
    trigger: 'item',
    formatter: (params => {
      console.log('params: ', params);
      return params['value'][1];
    })
  },
  ...
};
```
It works fine for me
