### ISSUE TITLE
Doesn't work on IE11

### ISSUE THREAD

**Issue by acierto** [hustcc/echarts-for-react#111]
If I only just add a dependency in package.json 
```
...
"echarts-for-react": "2.0.0"
...
```
Application on IE11 on Win 7 is failing with such exception:

![screen shot 2017-10-23 at 11 53 23](https://user-images.githubusercontent.com/2265094/31883105-21bb8be4-b7e9-11e7-9b7a-b451a90baef6.png)

Info about IE and WIn:

![screen shot 2017-10-23 at 11 56 11](https://user-images.githubusercontent.com/2265094/31883141-36fc171c-b7e9-11e7-97a0-7d7d89845dee.png)

**Comment by hustcc** [comment]
Open http://git.hust.cc/echarts-for-react/ in your IE10 for a test.

**Comment by acierto** [comment]
After a long time of playing with code, I figured out that the issue in the way how you build your library. When I built it with my webpack configuration - it started working on IE 11. So I can conclude that `"npm run clean && cross-env NODE_ENV=production babel src -d lib && npm run demo"` is not enough for cross-browser support.

**Comment by hustcc** [comment]
So give us a pr to fix it ?

**Comment by acierto** [comment]
I'd need to rewrite your whole project for that.

**Comment by hustcc** [comment]
Why？

**Comment by acierto** [comment]
There are several reasons:
1) really outdated libs (webpack 1, though it is already 3), and when you upgrade it, there is a chain of other updates.
2) building by webpack, instead of babel affects all demo files + index.html
3) as you everything run from npm, but not gulp, it makes more difficult to create normal flow. 
I started doing it, but stopped in the middle, as I'm not sure that you want completely different setup of your library.

Maybe you can do it with way smaller change for that. But it takes significant time to nail down exact reason. 

if you want really fix it, and keep it your project config as it is, I can only recommend to not rely on your demo setup, but just to take some real react project, which is using webpack to build a bundle. And add there in `package.json` your lib just as a dependency, even no need to do something else in the code. And in Win7/IE11 (You can download some VM for example from here: https://github.com/magnetikonline/linuxmicrosoftievirtualmachines) you will see crashing app just on a startup. 

Currently I decided to use another lib, as they build sources properly with webpack and no issues there.

**Comment by hustcc** [comment]
So what can I do to help you.
