### ISSUE TITLE
How to use bmap?

### ISSUE THREAD

**Issue by leftluoyi** [hustcc/echarts-for-react#112]
Is there any guide about how to use bmap in echart-for-react?

**Comment by hustcc** [comment]
bmap 在原生 echarts 中是怎么使用？如果也是用 options 配置的话，那么使用上并没有什么特殊的区别！

**Comment by hustcc** [comment]
Is there usagew guide for bmap on echarts's website?

**Comment by JoaoAlrc** [comment]
still no solution?
