### ISSUE TITLE
iphone6s上绘制的图像在反复滚动后会消失

### ISSUE THREAD

**Issue by wanjianwei** [hustcc/echarts-for-react#113]
在iphone上，一个多屏的h5页面上下滚动，绘制在底部的echart图会消失，点击原绘制区域，图像又出现了。另外，从该页面push到下一个页面操作后再返回，也有可能会导致图像消失，请问这是什么原因？与webview的内核渲染有关还是与该框架有关？

**Comment by SidKwok** [comment]
能提供一下原始代码吗？

**Comment by wanjianwei** [comment]
<Chart
                              echarts = {echarts}
                              option ={this.makeOptions()}
                              notMerge={false}
                              lazyUpdate={false}
                              style={{height: '1.92rem', width: '1.92rem',backgroundColor:"white"}}/>

//构造echart的options
    makeOptions = ()=>{
        return {
            series: [{
                type:'pie',
                radius: ['55%', '100%'],
                center:['50%','50%'],
                silent:true,
                animation:false,
                minAngle:5,
                labelLine:{
                    normal:{
                        show:false
                    }},
                avoidLabelOverlap: false,
                legendHoverLink:false,
                hoverAnimation:false,
                color: this.loanItemColors,
                data:this.loanItemValue,
            }
            ]
        }
    };
这是相关代码

**Comment by SidKwok** [comment]
噢不 我说的是可以重现到手机上的代码

**Comment by SidKwok** [comment]
因为我们并没有对echarts本身进行改写，只是基于echarts做了一层封装，所以这个问题有可能是echarts本身的问题。

**Comment by wanjianwei** [comment]
这个给不了啊，正在开发中，android上无问题，iphone模拟器上也没有问题，唯独在iphone真机上出现了，而且也只是偶然现象

**Comment by hustcc** [comment]
@wanjianwei 这个应该是 echarts 的移动兼容性问题！
