### ISSUE TITLE
建议升级 echarts 版本

### ISSUE THREAD

**Issue by Eyrum** [hustcc/echarts-for-react#114]
当前版本依赖的echarts@3.6.1可能引起bug 
```
Uncaught (in promise) ReferenceError: __DEV__ is not defined
```
新版本这个问题已解决  <a href="https://github.com/ecomfe/echarts/pull/6536/files">请参考</a>

**Comment by hustcc** [comment]
echarts 是 peer，可以自行在自己的环境中升级到新版本！
