### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by komorebi-san** [hustcc/echarts-for-react#116]
When compiling there is an error: 

./node_modules/echarts-for-react/lib/index.js
Module not found: Can't resolve 'echarts' in '/Volumes/FLASHDRIVE/KingKongFather/node_modules/echarts-for-react/lib'

**Comment by hustcc** [comment]
echarts 是 peer，请自行安装依赖版本！

**Comment by hustcc** [comment]
echarts is peer dependence, please install in your own app.
