### ISSUE TITLE
折线点的拖拽能实现吗？

### ISSUE THREAD

**Issue by frankgray** [hustcc/echarts-for-react#117]
折线点的拖拽能实现吗？

**Comment by hustcc** [comment]
这种 echarts 功能性的 issue，可以到 echarts 项目下面去提！

**Comment by frankgray** [comment]
抱歉叨扰了。
因为echarts可以实现这个功能，所以我想着这个项目是否可以实现。
毕竟我通过webpack那种方法引入到react项目中，无法实现拖拽。

**Comment by hustcc** [comment]
echarts 实现的方式可以贴一下代码吗？

**Comment by frankgray** [comment]
myChart.setOption({
        graphic: echarts.util.map(data, function (item, dataIndex) {
            return {
                type: 'circle',
                position: myChart.convertToPixel('grid', item),
                shape: {
                    r: symbolSize / 2
                },
                invisible: true,
                draggable: true,
                ondrag: echarts.util.curry(onPointDragging, dataIndex),
                onmousemove: echarts.util.curry(showTooltip, dataIndex),
                onmouseout: echarts.util.curry(hideTooltip, dataIndex),
                z: 100
            };
        })
    });

function showTooltip(dataIndex) {
        myChart.dispatchAction({
            type: 'showTip',
            seriesIndex: 0,
            dataIndex: dataIndex
        });
    }

    function hideTooltip(dataIndex) {
        myChart.dispatchAction({
            type: 'hideTip'
        });
    }

    function onPointDragging(dataIndex, dx, dy) {
        data[dataIndex] = myChart.convertFromPixel('grid', this.position);
        myChart.setOption({
            series: [{
                id: 'a',
                data: data
            }]
        });
    }

设置graphic。我的问题在于onPointDragging、showTooltip、hideTooltip，传不进echarts.util.curry方法中。这个要是能解决也好。


链接：http://echarts.baidu.com/tutorial.html#%E5%B0%8F%E4%BE%8B%E5%AD%90%EF%BC%9A%E8%87%AA%E5%B7%B1%E5%AE%9E%E7%8E%B0%E6%8B%96%E6%8B%BD

**Comment by hustcc** [comment]
直接 `import echarts from 'echarts';`

然后构造 option。这样可以吗？

**Comment by frankgray** [comment]
尝试过，但是就是无法调用方法。打过断点，发现graphic中的ondrag、onmousemove和onmouseout所对应的onPointDragging、showTooltip、hideTooltip方法进不去。

**Comment by cdoneshot** [comment]
我试了下，目前的版本是可以实现这个功能。@fankgray

>**注意这件事需要在第一次 setOption 后再进行，也就是说，须在坐标系（grid）初始化后才能调用 myChart.convertToPixel('grid', dataItem)。**

注意echarts demo里面的这句话。

**Comment by frankgray** [comment]
谢谢，我已经实验成功了。谢谢大佬~

**Comment by Lin-HF** [comment]
> 谢谢，我已经实验成功了。谢谢大佬~

我也卡在这里了，请问大佬最后怎么解决的？我在第二个setOption里设置里也没用啊，求demo！！

**Comment by frankgray** [comment]
@Lin-HF 不好意思，好久以前的，忘记了。
