### ISSUE TITLE
折线图显示问题

### ISSUE THREAD

**Issue by YogaChenYo** [hustcc/echarts-for-react#118]
![default](https://user-images.githubusercontent.com/33825704/33420501-cf581380-d5e9-11e7-8136-c57e166b0a4e.png)
刷新浏览器，图标被拉伸到屏幕外了

缩放下浏览器大小，就会恢复正常，这是什么问题，怎么解决？求大神交流
![default](https://user-images.githubusercontent.com/33825704/33420558-0469bae2-d5ea-11e7-8ee5-51cd6f5a10d5.png)

**Comment by hustcc** [comment]
应该是自己的 css 样式问题！

**Comment by cdoneshot** [comment]
我记得这个问题我在低版本IE（大概是IE6还是IE8）遇到过，当时尝试了一下echarts本身就有这问题

**Comment by hustcc** [comment]
好吧，那你可以尝试到 echarts 项目上去提 issue，不过对于低版本 ie，应该不太会处理的！

**Comment by NearTheSeas** [comment]
想问一下你的问题解决了么？ 我也碰到同样的问题了，像是渲染时机的问题
