### ISSUE TITLE
How to highlight current date in calendar chart

### ISSUE THREAD

**Issue by abhaychitnis** [hustcc/echarts-for-react#119]
I am using echarts-for-react version 2.0.0 and react version 16.0.0

I am unable to find any way to change the color and border of current date in the calendar chart. I am able highlight current month using, 'itemStlye' attribute of 'calendar' object in 'option' settings. But am unable to format individual cell conditionally.

Please help

**Comment by hustcc** [comment]
This is the issue of echarts option.

You can read the document of echarts [here](http://echarts.baidu.com/option.html).

If there is no way to do it, submit an issue on [github echarts](https://github.com/ecomfe/echarts).
