### ISSUE TITLE
未改变容器大小，但图例重新渲染了。

### ISSUE THREAD

**Issue by mxyzzhong** [hustcc/echarts-for-react#130]
应该是这段[代码](https://github.com/hustcc/echarts-for-react/blob/master/src/core.jsx#L5)出了问题吧，判断相等应该是`===`吧，这样在没改变`props.style`和`props.className`的情况下，触发了resize再次渲染。

**Comment by hustcc** [comment]
智商下限了，还好影响分支不大！马上提交新版本，并且提高测试覆盖率！

感谢反馈！

**Comment by hustcc** [comment]
v2.0.3 done.
