### ISSUE TITLE
English version not working

### ISSUE THREAD

**Issue by yonidejene** [hustcc/echarts-for-react#131]
I tried both the CDN version(https://cdnjs.cloudflare.com/ajax/libs/echarts/3.7.2/echarts-en.js) and a custom build with english. I just want to change the tooltips, do you have any recommendations? Thank you!
<img width="82" alt="screenshot 2017-12-29 18 36 37" src="https://user-images.githubusercontent.com/19519903/34440609-3e2fc80e-ecc7-11e7-904d-a94aa0e12155.png">

**Comment by hustcc** [comment]
Show me your code, and the webpack config.

**Comment by yonidejene** [comment]
I haven't ejected my app. Is there anyway to do this without modifying the config? 
Here's how I created the build: 
`node node_modules/echarts/build/build.js --lang en`

**Comment by rahuls360** [comment]
I found a solution to this. Source: https://codepen.io/nizantz/pen/QqgVmZ

Set your titles manually using toolbox.feature.title

toolbox: {
        show: true,
        orient: 'vertical',
        feature: {
          dataView: { show: true, title: 'Data View', readOnly: false },
          restore: { show: true, title: 'Reset' },
          saveAsImage: { show: true, title: "Download" }
        },
      }
