### ISSUE TITLE
'Dynamic' example unexpected token

### ISSUE THREAD

**Issue by Dyanngg** [hustcc/echarts-for-react#132]
Trying to run the 'dynamic' chart example, copied from your project to my own, but code cannot compile:
![screenshot from 2018-01-02 13-49-46](https://user-images.githubusercontent.com/11527024/34501473-f2fc96a0-efc3-11e7-94d3-3cfc586c0e97.png)

**package.json:**

{
  "dependencies": {
    "bootstrap": "^4.0.0-beta.3",
    "d3": "^4.12.2",
    "echarts": "^3.8.5",
    "echarts-for-react": "^2.0.4",
    "jquery": "^3.2.1",
    "popper.js": "^1.12.9",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-container-dimensions": "^1.3.3",
    "react-dom": "^16.2.0",
    "react-measure": "^2.0.2",
    "react-scripts": "0.9.5",
    "reactstrap": "^5.0.0-alpha.4",
    "requirejs": "^2.3.5",
    "rest": "^1.3.1",
    "uglify-js": "^3.3.4",
    "webpack": "^1.15.0"
  },
  "devDependencies": {
      "babel-core": "^6.26.0",
      "babel-loader": "^6.2.7",
      "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es3-member-expression-literals": "^6.22.0",
    "babel-plugin-transform-es3-property-literals": "^6.22.0",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "echarts": "^3.8.5",
    "jsx-loader": "^0.13.2"
}

**webpack.config.js:**

let path = require('path');
let webpack = require('webpack');
let uglifyJsPlugin = webpack.optimize.UglifyJsPlugin;
let definePlugin = webpack.DefinePlugin;

module.exports = {
    entry: './src/index.js',
    devtool: 'sourcemaps',
    cache: true,
    debug: true,
    output: {
        path: __dirname,
        filename: '../../resources/static/built/bundle.js'
    },
    module: {
        loaders: [
            {
                test: path.join(__dirname, '.'),
                exclude: /(node_modules)/,
                loader: 'babel-loader',
                query: {
                    cacheDirectory: true,
                    presets: ['es2015', 'react']
                }
            }
        ]
    },
    externals:[{
        xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}',
        echarts: 'window.echarts'
    }],
    plugins: [
        new uglifyJsPlugin({compress: {warnings: false}}),
        new definePlugin({'process.env': {NODE_ENV: '"production"'}})
     ]
};

**Comment by hustcc** [comment]
Please add the babel plugins in .babelrc.

You can see the .babelrc file in the root dir.
