### ISSUE TITLE
Toolbox components not showing up?

### ISSUE THREAD

**Issue by terndrup** [hustcc/echarts-for-react#134]
Hey, thanks for a great library! 

Just wanted to ask, I cannot seem to get the charts to use the brush / toolbox select items from the echarts demo. I want the user to be able to select a region of the chart by drawing a rectangle using the echarts brushes like here: https://ecomfe.github.io/echarts-doc/public/en/option.html#brush.toolbox

From the demos I just put this in my option:

```js
        toolbox: {
            show: true,
            feature: {
              dataZoom: {
                yAxisIndex: false,
              },
              brush: {
                type: ['lineX', 'clear'],
              },
              dataView: { readOnly: true },
              saveAsImage: {},
            },
          },
          brush: {
            xAxisIndex: 'all',
            brushLink: 'all',
            outOfBrush: {
              colorAlpha: 0.1,
            },
          },
```
but the chart still only renders the dataView and SaveAsImage buttons. Any ideas?

Do you have a demo with echarts-for-react showing the brush data select option?

Thanks!

**Comment by terndrup** [comment]
Sorry this was due to a mistake in my own code. Sorry!

**Comment by hustcc** [comment]
Show your code here.

**Comment by terndrup** [comment]
It was unrelated to the actual options, my chart was not loading my options properly because I had messed something up.
