### ISSUE TITLE
支持下echarts-gl？

### ISSUE THREAD

**Issue by jinmmd** [hustcc/echarts-for-react#135]

**Comment by jinmmd** [comment]
知道了

**Comment by hustcc** [comment]
如果可以的话，帮忙 pr 一个 gl 的 demo？不少人问到这个！

**Comment by hustcc** [comment]
echarts-gl 的使用和 echarts 本身使用上并没有区别。

https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Gl.jsx
