### ISSUE TITLE
[v2.0.4]"element-resize-event" v2.0.8 error: "window is not defined"

### ISSUE THREAD

**Issue by orzYancy** [hustcc/echarts-for-react#136]
Recommended upgrade package "element-resize-event" to v2.0.9.
There is "window is not defined" error on v2.0.8.
https://github.com/KyleAMathews/element-resize-event/issues/17
Thanks~

**Comment by hustcc** [comment]
What is the version of echarts-for-react.

Please update to the lastest version.

**Comment by hustcc** [comment]
I will upgrade it in next version with echarts v4.0.0 supported.

**Comment by hustcc** [comment]
v2.0.5 done
