### ISSUE TITLE
2.0.6 版本添加的 opts 属性无效

### ISSUE THREAD

**Issue by liurongqing** [hustcc/echarts-for-react#142]
npm install echarts-for-react 了
"echarts-for-react": "^2.0.6"

```javascript
return (
   <ReactEcharts
    option={this.getTypeOption()}
     opts={{ render: 'svg' }}
     className='react_for_echarts' />
 )
```
opts属性没生效，渲染出来的还是canvas

**Comment by hustcc** [comment]
请注意看下 readme，或者看下 echarts 文档。

你的代码中，render 名字不对，好像是 renderer.

**Comment by liurongqing** [comment]
看到了，不好意思哈，昨天本来写renderer没改回来哈， 又看了你代码的ReactEchartsPropsTypes里面没有opts，以为你忘记上传了哈，这个没问题了，我刚试了ok了，谢谢
