### ISSUE TITLE
重新渲染后时间轴的进度丢失

### ISSUE THREAD

**Issue by wutairui** [hustcc/echarts-for-react#143]
在监听时间轴改变的事件里setState导致页面重新渲染后，时间轴的进度会丢失，导致时间轴重新开始播放。

**Comment by hustcc** [comment]
可以看下你的大概代码吗？

**Comment by wutairui** [comment]
大致如下：
```
export default class Economy extends Component {
  state = {
    current: 0,
    chartOptions: {}
  }

  timelineChanged = (e) => {
    this.setState({
      current: e.currentIndex,
    });
  }

  render() {
    const onEvents = {
      timelinechanged: this.timelineChanged,
    };
    return (
      <ReactEcharts
        ref={(e) => { this.echarts_react = e; }}
        option={this.state.chartOptions}
        style={{ height: '600px', width: '100%' }}
        notMerge
        lazyUpdate
        onEvents={onEvents}
    />
    )
  }
}
```

**Comment by hustcc** [comment]
可以尝试吧 currentIndex 这个配置到 option 中！

**Comment by ys278099744** [comment]
sunbrust这个组件能不能快点整合进去？项目急用，

**Comment by hustcc** [comment]
@ys278099744 可以使用的啊，demo 都有了，可以看网站的最后一个菜单。

代码在这里：https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Sunburst.jsx

**Comment by ys278099744** [comment]
这是版本号："echarts-for-react": "^2.0.6",
这是报错：
Uncaught Error: Component series.sunburst not exists. Load it first.
用npm安装的就是不行，可能是npm没有更新？

**Comment by hustcc** [comment]
echarts 版本是 4 吗？

**Comment by ys278099744** [comment]
升级echart到4.0.2就好了，没想到echart和echart-for-react不是同一个东西，已经搞定了，非常感谢。有兴趣可以加个微信，18741297528.嘻嘻
