### ISSUE TITLE
使用 ReactEchartsCore时 opts 无效

### ISSUE THREAD

**Issue by liurongqing** [hustcc/echarts-for-react#144]
```
 <ReactEchartsCore
  style={{ height: '280px' }}
  echarts={echarts}
  opts={{ renderer: 'svg' }}
  option={option} />
```
用 ReactEcharts 时 opts renderer svg有效
使用 ReactEchartsCore 时 opts renderer svg 无效

**Comment by hustcc** [comment]
大概是因为你需要自己手动引入 svg render 的模块，就像你如果使用了 bar 图，就需要引入 bar.js 一样。但是这个我没有在官方文档找到如何引入！

**Comment by liurongqing** [comment]
"echarts": "^4.0.2",
"echarts-for-react": "^2.0.6",
"zrender": "^4.0.1"

好象不行，我再试试看

**Comment by liurongqing** [comment]
直接引入 zrender是可以的， 
```javascript
import 'zrender'
```
下面这样引入找不到这个
```javascript
import 'zrender/svg/svg.js'
```

**Comment by liurongqing** [comment]
谢谢你，给了我很多的帮助，非常感谢

echarts上看了下，这样引入可以了
```javascript
import 'zrender/lib/svg/svg'
```

大神，按照你上面的按需加载方式，没压缩前还是有1.2m左右，有没有咋更好的优化思路呢
```javascript
import ReactEchartsCore from 'echarts-for-react/lib/core'
import echarts from 'echarts/lib/echarts'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
import 'zrender/lib/svg/svg'
```

**Comment by hustcc** [comment]
svg.js 应该是在 src 目录的，你在对应的目录找找，然后引入。

echarts 模块加载的时候，没办法定制引入 SVG，应该属于 echarts 上的一个开发体验优化，可以尝试去提 issue。

**Comment by liurongqing** [comment]
好的，谢谢你

**Comment by hustcc** [comment]
@liurongqing 压缩之后，300kb 所有，还是可以接受的吧！
