### ISSUE TITLE
sunbrust能不能整合进去？拜托了

### ISSUE THREAD

**Issue by ys278099744** [hustcc/echarts-for-react#145]

**Comment by hustcc** [comment]
请先看项目主页的 demo 页面，已经可以支持了。

而且支不支持 不依赖于这个项目，而是你本地 echarts 升级到 4，并且写出来的 option 正确！

**Comment by ys278099744** [comment]
妹子，非常感谢，我把echart升级到4就好啦，我是一个业余的前端，见谅。新年快乐！
