### ISSUE TITLE
Bundle sized increased dramatically due to this package

### ISSUE THREAD

**Issue by VALIKCOOL** [hustcc/echarts-for-react#146]
Greetings! Really found your package useful, but I am facing issue with production build. I have analyzed **bundle.js** with **BundleAnalyzerPlugin** and this package takes up to 1.85mb of prod build. What can this issue be due to? 
![screenshot 80](https://user-images.githubusercontent.com/10166922/36232420-6540cc16-11ea-11e8-8b4e-458ebba01c9a.png)

**Comment by hustcc** [comment]
echarts is a chart library base on canvas and svg. you can reduce the bundle size by the way.

1. package echarts out of bundle file. using externals config of webpack.

2. import echarts module by your self instead of all package.

```jsx
import React from 'react';
// import the core library.
import ReactEchartsCore from 'echarts-for-react/lib/core';
// then import echarts modules those you have used manually.
import echarts from 'echarts/lib/echarts';
import 'echarts/lib/chart/bar';
import 'echarts/lib/component/tooltip';

// The usage of ReactEchartsCore are same with above.
<ReactEchartsCore
  echarts={echarts}
  option={this.getOption()}
  notMerge={true}
  lazyUpdate={true}
  theme={"theme_name"}
  onChartReady={this.onChartReadyCallback}
  onEvents={EventsDict}
  opts={} />
```

**Comment by VALIKCOOL** [comment]
Just tried your second solution but it is producing error
![image](https://user-images.githubusercontent.com/10166922/36279051-876e8bac-129e-11e8-98ec-515b8eb4e7c3.png)

**Comment by hustcc** [comment]
You should import `serise` too.

You can see the document about echarts at official website.

I'm in my hometown for new year, there is no network,  so can not help you find the specific document link.

**Comment by hustcc** [comment]
Demo below:

```js
// echarts module
import * as echarts from 'echarts/lib/echarts';
// line
import 'echarts/lib/chart/line';
// tooltip, title, toolbox
import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/title';
import 'echarts/lib/component/toolbox';

// 基于准备好的dom，初始化 echarts 实例并绘制图表。
echarts.init(document.getElementById('main')).setOption({
    title: {text: 'Line Chart'},
    tooltip: {},
    toolbox: {
        feature: {
            dataView: {},
            saveAsImage: {
                pixelRatio: 2
            },
            restore: {}
        }
    },
    xAxis: {},
    yAxis: {},
    series: [{
        type: 'line',
        smooth: true,
        data: [[12, 5], [24, 20], [36, 36], [48, 10], [60, 10], [72, 20]]
    }]
});
```

You should import `line` as well.
