### ISSUE TITLE
zrUtil.isTypedArray is not a function

### ISSUE THREAD

**Issue by lotusms** [hustcc/echarts-for-react#147]
It seems late updates of echarts and/or echarts-for-react are producing this error (See image below). Any idea if this is getting handled or if there is a patch for it?

![zrutil error](https://user-images.githubusercontent.com/6147772/36321474-fa02b854-1317-11e8-8d7f-ed5643ab563d.png)

**Comment by hustcc** [comment]
Show me your code?

**Comment by lotusms** [comment]
This is my custom chart   
 
    import React from 'react';
    import ReactEcharts from 'components/ReactECharts';

    const area = {};
    area.options = {
	  xAxis : [
                 {
                         type : 'category',
                         boundaryGap : false,
	                 splitLine: {
	                       show: false,
	                 },
	                 axisLabel: {
            	               inside: false,
	                       show: true,
			       textStyle: {
			              color: '#898989',
			       },
	                 },
                         data : ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                  },
           ],
            yAxis : [
                  {
                          type : 'value',
	                  splitLine: {
	                        show: false,
	                  },
	                  axisLabel: {
            	                inside: false,
	                        show: true,
			        textStyle: {
			      	      color: '#898989',
			        },
	                  },
                    },
             ],
             grid: {
                    show: false,
                    containLabel: true,
                    splitLine: {
                           show: false,
                    },
             },
             legend: {
                     data:['Online', 'Offline'],
		     orient: 'horizontal',
		     x : 'right',
                     y : 'top',
	             textStyle: {
	      	            color: '#898989',
	             },
             },
             tooltip : {
                     trigger: 'axis',
                     axisPointer: {
                            type: 'cross',
                            label: {
                                    backgroundColor: '#6a7985',
                            },
                     },
             },
             series : [
                     {
                             name:'Online',
                             type:'line',
                             stack: 'Total',
        	             showSymbol: false,
                             label: {
                                    normal: {
                                          show: true,
                                          position: 'top',
                                    },
                             },
                             areaStyle: {normal: {color: '#E91E63'}},
                             data:[6, 1, 3, 4, 5, 5, 2],
                      },
                      {
                              name:'Offline',
                              type:'line',
                              stack: 'Total',
        	              showSymbol: false,
                              label: {
                              normal: {
                                      show: true,
                                      position: 'top',
                              },
                       },
                       areaStyle: {normal: {color: '#03A9F4'}},
                       data:[4, 2, 1, 3, 2, 2, 1],
                },
          ],
    };

    class DBPoolStats extends React.Component {
	    render() {
		    return (
			   <ReactEcharts
                    		option={area.options}
                    		showLoading={false}
                    	    />
		    );
	    }
     }

     module.exports = (DBPoolStats);

This is the ReactECharts Component

	import React from 'react';
	import PropTypes from 'prop-types';
	import echarts from 'echarts';
	import 'echarts/theme/macarons';

	import elementResizeEvent from 'element-resize-event';

	class ReactEcharts extends React.Component {
	    propTypes: {
	        option: PropTypes.object.isRequired,
	        notMerge: PropTypes.bool,
	        lazyUpdate: PropTypes.bool,
	        style: PropTypes.object,
	        className: PropTypes.string,
	        theme: PropTypes.string,
	        onChartReady: PropTypes.func,
	        showLoading: PropTypes.bool,
	        loadingOption: PropTypes.object,
	        onEvents: PropTypes.object
	    }

	    // first add
	    componentDidMount() {
	        const echartObj = this.renderEchartDom();
	        const onEvents = this.props.onEvents || {};
	        let reizeEvent;

	        this.bindEvents(echartObj, onEvents);
	        // on chart ready
	        if (typeof this.props.onChartReady === 'function') this.props.onChartReady(echartObj);

	        function resize() {
	          clearTimeout(reizeEvent);
	          reizeEvent = setTimeout(() => { echartObj.resize(); }, 200);
	        }

	        // on resize
	        elementResizeEvent(this.echartsDom, () => {
	            resize();
	        });
	    }

	    // update
	    componentDidUpdate() {
	        this.renderEchartDom();
	        this.bindEvents(this.getEchartsInstance(), this.props.onEvents || []);
	    }

	    // remove
	    componentWillUnmount() {
	        echarts.dispose(this.echartsDom);
	    }

	    // bind the events
	    bindEvents(instance, events) {
	        const loop = function loop(eventName) {
	            // ignore the event config which not satisfy
	            if (typeof eventName === 'string' && typeof events[eventName] === 'function') {
	                // binding event
	                instance.off(eventName);
	                instance.on(eventName, (param) => {
	                    events[eventName](param, instance);
	                });
	            }
	        };

	        for (const eventName in events) {
	            loop(eventName);
	        }
	    }

	    // render the dom
	    renderEchartDom() {
	        // init the echart object
	        const echartObj = this.getEchartsInstance();
	        // set the echart option
	        echartObj.setOption(this.props.option, this.props.notMerge || false, this.props.lazyUpdate || false);
	        // set loading mask
	        if (this.props.showLoading) echartObj.showLoading(this.props.loadingOption || null);
	        else echartObj.hideLoading();

	        return echartObj;
	    }

	    getEchartsInstance() {
	        // return the echart object
	        const theme = this.props.theme ? this.props.theme : 'macarons';
	        return echarts.getInstanceByDom(this.echartsDom) || echarts.init(this.echartsDom, theme);
	    }

	    render() {
	        const style = this.props.style || {
	            height: '350px'
	        };
	        // for render
	        return (
	            <div
	                ref={(c) => { this.echartsDom = c; }}
	                className={this.props.className}
	                style={style} />
	        );
	    }
	}

	module.exports = ReactEcharts;

**Comment by lotusms** [comment]
"echarts": "^3.5.4",
    "echarts-for-react": "^2.0.6",

**Comment by hustcc** [comment]
Why not use echarts-for-react directly instead of your wrapped component?

You can get all the demo code in dir `demo`.

**Comment by hustcc** [comment]
`options.series[x].data` should be an array.

online demo [here](http://echarts.baidu.com/examples/editor.html?c=line-simple).

**Comment by zhongtingbing** [comment]
> `options.series[x].data` should be an array.
> 
> online demo [here](http://echarts.baidu.com/examples/editor.html?c=line-simple).
It was not the probleam
