### ISSUE TITLE
Cannot read property 'requestAnimationFrame' of undefined

### ISSUE THREAD

**Issue by houx15** [hustcc/echarts-for-react#148]
持续提示“Cannot read property 'requestAnimationFrame' of undefined”信息
源码中显示为

```js
var requestFrame = function () {
  var window = this;
  var raf = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || function fallbackRAF(func) {
    return window.setTimeout(func, 20);
  };
  return function requestFrameFunction(func) {
    return raf(func);
  };
}();
```

window 为 undefined

使用版本： `echarts-for-react 2.0.6`

**Comment by hustcc** [comment]
你是怎么使用？

 - react echarts版本
 - 浏览器版本

可以试下打开 http://git.hust.cc/echarts-for-react/ 看看会不会出错。

**Comment by houx15** [comment]
react版本：16.2.0
echarts-for-react版本：2.0.6
echarts版本：4.0.2
浏览器版本：Chrome 64.0.3282.167

**Comment by hustcc** [comment]
你本地打开 上面的网址 是否会出现错误。

**Comment by houx15** [comment]
这个网站没有报错。
之前其他项目也使用过echarts-for-react没有出错

**Comment by hustcc** [comment]
打包工具有变化？

**Comment by houx15** [comment]
打包工具均是webpack，版本有所不同。

![image](https://user-images.githubusercontent.com/18237830/36636911-d74cee5c-1a0a-11e8-8dae-89efa5870d39.png)

如图为相关依赖。

**Comment by hustcc** [comment]
这个问题之前也出现过，问题在于 element-resize-event 这个库写法问题，可能导致打包出现找不到 window。

**Comment by wyh2020** [comment]
这个有解决方案吗？ @houx15 @hustcc

**Comment by hustcc** [comment]
@wyh2020 @houx15 Are you use server-side render ?

**Comment by Nickolee** [comment]
Hello! I'm having the exact same problem. Have you found a solution for this?

**Comment by hustcc** [comment]
@Nickolee Are you use it by server side render？

**Comment by Younger-Peng** [comment]
我使用create-react-app初始haul整个项目时，没有这个问题；
但是我自己重新配置整个环境时也出现了上述问题

**Comment by hustcc** [comment]
Younger-Peng 试试用 server side render 吗？

**Comment by Younger-Peng** [comment]
@hustcc 
[项目地址]https://github.com/Younger-Peng/xx_platforml)
麻烦抽时间运行一下，看在你那里会不会复现

**Comment by hustcc** [comment]
@Younger-Peng update .babel by

```js
{
    "presets": ["env", "react", "stage-0"],
    "plugins":[
        "transform-remove-strict-mode"
    ]
}
```

remove strict-mode which add by babel default.

It is issue of `element-resize-event`. https://github.com/KyleAMathews/element-resize-event/issues/29
