### ISSUE TITLE
打包后样式高度不是100%

### ISSUE THREAD

**Issue by Viin-zx** [hustcc/echarts-for-react#149]
![image](https://user-images.githubusercontent.com/19523605/36637951-dfb0fd7e-1a21-11e8-80a7-b1080fd6db18.png)

前面两个没问题，总是最后一个就不会计算高度，删掉一个的话就是第二个变成这样
![image](https://user-images.githubusercontent.com/19523605/36637955-fbff0d90-1a21-11e8-8770-77920427862d.png)

![image](https://user-images.githubusercontent.com/19523605/36637967-2fbd8666-1a22-11e8-89a9-63d36b7d2d74.png)

用的dva框架

**Comment by Viin-zx** [comment]
改变下浏览器大小好像就会resize,变成正常的样子，初始化就会出先这样的问题，请问如何解决？

**Comment by hustcc** [comment]
你看下是不是宽高都是 100px？

**Comment by hustcc** [comment]
你从浏览器开发工具里面，看出问题的那个 dom 结构，看看渲染出来的宽高是不是 100 px。

之前也有遇到过类似的问题。

**Comment by Viin-zx** [comment]
@hustcc 是的，在第一张图里面我就截了图，组件设置的高度是 100%， 然后生成的canvas父元素(组件子元素)高度就是100px了， 您看下。

**Comment by hustcc** [comment]
和 #150 是一类问题，后面在 #150 中处理。这个先关闭了~

如果有时间，麻烦在 codepen 上做一个可以复现的实例吧！
