### ISSUE TITLE
关于dynamic chart图片显示堆叠的问题

### ISSUE THREAD

**Issue by cyranosky** [hustcc/echarts-for-react#15]
你好，我的电脑是MAC Pro OS操作系统，浏览器版本是Chrome 50.0.2661.102 (64-bit)。

当将ReactEChart的style的height设置为100%时，Dynamic Chart显示异常，出现堆叠的情况。
注：我的图表空间的父节点的height是700px，不存在收到父节点高度的影响。

当我们将Chrome的版本更新至最新时，图表显示正常。
请抽时间解决一下，我们这边也努力寻找一下原因，保持联系啊。
若你那边有结果了请告诉我们一声。多谢兄弟了，谢谢 ~

代码如下：
![image](https://cloud.githubusercontent.com/assets/20176581/18744045/05e30f1a-8071-11e6-8892-71bf59cc5746.png)

异常图片如下：
![image](https://cloud.githubusercontent.com/assets/20176581/18743803/a0b1c114-806f-11e6-8358-4f678748ba6d.png)

**Comment by hustcc** [comment]
其实问题很简单，应该你设置为100%高度，所以图表的高度和父节点一致，所以图表的高度也就取决于父节点的高度了…

父节点高度不够，就导致图表高度也不够了-_-||

解决办法就是：增大父div的高度。或者使用js计算屏幕高度，然后设置为div的height。

**Comment by cyranosky** [comment]
虽然我们本地对echarts-for-react进行了简单的再次封装后，在shouldComponetUpdate()中进行了resize()操作暂时解决了这个堆叠的问题，但是感觉这并不是最完美的解决方案，而且效率和性能并不高。

代码如下:
shouldComponentUpdate(nextProps){
            let echarts_instance = this.refs.echarts_react.getEchartsInstance();
            echarts_instance.resize();
            return true;
 }

如果能在echarts-for-react内部解决，将是Very Good了。 @hustcc

**Comment by cyranosky** [comment]
问题我已经提到issue中了。

我的父div的高度很大，没有对图表有影响。

而且你的例子我下载到了本地，设置为height：100%。存在同样的问题，issue中的堆叠截图就运行的是你的Sample。

**Comment by hustcc** [comment]
执行resize()之后的效果是什么样子的？

**Comment by cyranosky** [comment]
resize是正常显示了啊。

**Comment by hustcc** [comment]
高度百分之百，就是占满整个屏幕的高度？你的父div高度怎么设置的？

**Comment by cyranosky** [comment]
这是你的Sample，我更改后的代码。红色字体是我更改的，你可以自己实验一下，将height改为100%。


render: function() {
        let code = "<ReactEcharts ref='echartsInstance' \n" +
                    "    option={this.state.option} />\n";
        return (
            <div className='examples'>
                <div className='parent'>
                    <label> use React state to render dynamic chart</label>
                    <ReactEcharts ref='echarts_react'
                        option={this.state.option}
                        style={{height: '100%'}} />
                    <label> code below: QQQQQQQQQQQQuse state of react to render dynamic chart</label>
                    <pre>
                        <code>{code}</code>
                    </pre>
                </div>
            </div>
        );
    }

**Comment by hustcc** [comment]
这个我试过了，但是父div的高度是不够的。所以这个chart的高度只有那么一点点，你把父div加高之后，这个chart高度就可以展开了。
