### ISSUE TITLE
peer dependency 该升级了。。。

### ISSUE THREAD

**Issue by blade254353074** [hustcc/echarts-for-react#152]
`warning " > echarts-for-react@2.0.6" has unmet peer dependency "prop-types@^15.5.7".`

**Comment by hustcc** [comment]
^15.5.7 是包含最新的 v15.6.x 版本的。

出现这个 warning 的原因应该是你自己的 package.json 中 dependency 没有添加 prop-types 吧。

**Comment by blade254353074** [comment]
![image](https://user-images.githubusercontent.com/9346008/36706946-2ad37616-1ba7-11e8-94bd-db91e3e65384.png)
我这边是有的，yarn 安装报的 warning

**Comment by hustcc** [comment]
yarn 没有怎么使用过，你可以本地尝试下，怎么解决，然后欢迎给一个 pr。

**Comment by blade254353074** [comment]
行，我有闲时间帮你看一下

**Comment by Congee** [comment]
@blade254353074 大胸弟看的咋样了？

**Comment by blade254353074** [comment]
大兄弟我很忙，还是得大熊弟@Congee 你来看啊。。。

**Comment by hustcc** [comment]
也许并不是一个什么问题！https://stackoverflow.com/a/23131619/6509426

**Comment by blade254353074** [comment]
其实也不是什么问题，就是蛋疼不想看 WARN 😝

**Comment by hustcc** [comment]
删除 node module 重新安装也会存在？

**Comment by Congee** [comment]
@hustcc 会的。而且`npm cache clean --force` 没也没用

**Comment by hustcc** [comment]
那是个问题，大兄弟有空帮忙看看😁
