### ISSUE TITLE
2.0.7bug

### ISSUE THREAD

**Issue by fwh1990** [hustcc/echarts-for-react#154]
从2.0.6升级到2.0.7用不了，错误定位到 componentDidUpdate 的 prevProps.onEvents。错误是从react-dom发出来的，没啥卵用。回滚到2.0.6恢复正常。

>- webpack: 3.11
>- babel: 7.0-beta40
>- react: 16

**Comment by hustcc** [comment]
可以看下你使用组件的代码吗？是因为 onEvents 为 null 吗？

**Comment by fwh1990** [comment]
onEvents没有传过，也没有用过，错误提示给你吧：

```js
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ProxyComponent.componentDidUpdate (core.js:139)
    at commitLifeCycles (react-dom.development.js:8778)
    at commitAllLifeCycles (react-dom.development.js:9946)
    ...
```

**Comment by hustcc** [comment]
理论上，onEvents 如果是 undefined 的话，会自动转成 {}。

现在的情况应该是 onEvents 传了 null 了。

```js
Object.keys(null);
```

上面的代码就会报 `Uncaught TypeError: Cannot convert undefined or null to object` 错误。

**Comment by fwh1990** [comment]
已解决。因为继承ReactEchartsCore，然后在子类增加自定义的defaultProps。正确做法是
```js
Object.assign({}, ReactEchartsCore.defaultProps, ...);
```
