### ISSUE TITLE
onEvents calls assigned function an increasingly larger amount of times when using setState

### ISSUE THREAD

**Issue by synekdok** [hustcc/echarts-for-react#155]
Hi,
I'm working on a heatmap chart where the different items can be clicked to highlight other elements on the page.
I've run into some strange behaviour though where the onEvents function gets called an increasingly larger amount of times for every time the heatmap is clicked (2*number of clicks), which slows down the page and crashes it after a while.
This happens _only_ when calling `this.setState()` within the function.
Relevant code below.

```JSX
<ReactEcharts onEvents={{'click': (e) => { this.onHeatMapItemClick(e) }}}/>
```

```JSX
onHeatMapItemClick = (heatmapObject) => {
        let tempList = Object.assign([], this.state.highlightedItems);
        let itemId = heatmapObject.data.id;

        if (!this.state.highlightedItems.includes(itemId)){
            tempList.push(itemId);
        }
        else {
            tempList.splice(tempList.indexOf(itemId), 1);
        }
        this.setState({highlightedItems: tempList});
        console.log("Executed");
    };
```
Console output:
![echarts-itemclick](https://user-images.githubusercontent.com/7900888/36899091-d85f0a02-1e1d-11e8-8593-37d78c05a0a2.PNG)

```JSON
"echarts": "^4.0.2",
"echarts-for-react": "^2.0.7",
"react": "^16.2.0",
```
If anyone has any idea about what might be going on it would be appreciated
Cheers

**Comment by hustcc** [comment]
Thanks, it is a typo. Fixed on the commit(https://github.com/hustcc/echarts-for-react/commit/44c1e27e105236b72aff1bd2a3cc62a83fe3c75d).

Will publish later.
