### ISSUE TITLE
Toolbox language

### ISSUE THREAD

**Issue by OscarCanek** [hustcc/echarts-for-react#156]
How to make the toolbox show the text in english?

**Comment by hustcc** [comment]
You should import echarts of en version.

**Comment by hoschi** [comment]
@hustcc how to import english version of echarts from installed npm module? Can't find information how to do this :cry: 

This one is has Chinese labels:
`import echarts from 'echarts/lib/echarts';`

**Comment by hustcc** [comment]
```html
<script src="https://cdn.bootcss.com/echarts/4.0.4/echarts-en.min.js"></script>
```

**Comment by hoschi** [comment]
@hustcc that is a script tag fetching it from CDN ... not a installed npm module

**Comment by hustcc** [comment]
I do not know either. May be you should submit an issue in echarts.

**Comment by ffarella** [comment]
try this!

```
addWebpackAlias({
      echarts$: "echarts/dist/echarts-en.min",
      echarts: "echarts/dist",
    }),
```

(I use antd so I have to do this with react-app-rewired)
