### ISSUE TITLE
How to handle click in tooltip?

### ISSUE THREAD

**Issue by erezcarmel** [hustcc/echarts-for-react#158]
Using a formatter to customise the tooltip, for example:
`<div className="myTooltip"><div onClick={() => someParentComponentFunc()}>Click me</div>`

How can I trigger a parent component function by clicking inside the tooltip?

**Comment by hustcc** [comment]
Customise the tooltip by formatter with html string, so can not use react `onClick`, we can only use global function, like below:

```js
// define function

function tooltip_click_event() {
   // process the event.
}

// config tooltip formatter
formatter: function() {
    return `<div onclick='tooltip_click_event'>...</div>`
}
```

**Comment by erezcarmel** [comment]
@hustcc ok, that's what I did for now. I wasn't sure it's the only way.
Thank you.

**Comment by mozhs** [comment]
> Customise the tooltip by formatter with html string, so can not use react `onClick`, we can only use global function, like below:
> 
> ```js
> // define function
> 
> function tooltip_click_event() {
>    // process the event.
> }
> 
> // config tooltip formatter
> formatter: function() {
>     return `<div onclick='tooltip_click_event'>...</div>`
> }
> ```

不一定非得全局监听函数吧...在echarts实例dom上监听事件，并通过判断 event.target 是否是 tooltip dom就可以
