### ISSUE TITLE
Change origin position in chart line

### ISSUE THREAD

**Issue by winwave** [hustcc/echarts-for-react#159]
Hello,
I have a question, Can i change the axis X at 10 ( not 0 by defaut)
![image](https://user-images.githubusercontent.com/19307759/37159360-ecf414a6-22ed-11e8-9d92-b4ca3a14462c.png)
because i want to fill the area like that 
![image](https://user-images.githubusercontent.com/19307759/37159862-27f78654-22ef-11e8-98cb-b21c1b6363fc.png)

**Comment by hustcc** [comment]
Sorry, you should send issue on `echarts`.

Same issue: https://github.com/ecomfe/echarts/issues/6525. Echarts is not support the feature now.
