### ISSUE TITLE
Tree change data has bug

### ISSUE THREAD

**Issue by zhoulexing** [hustcc/echarts-for-react#160]
Tree在改变数据时，组件会对之前的图进行remove，在remove的时候有bug

**Comment by hustcc** [comment]
可以给出实例代码吗？最好能在 codepen 有复现啊😊

**Comment by CShame** [comment]
我也碰到了这个问题，对数据进行筛选的时候有时候会报错

**Comment by CShame** [comment]
是echarts3的问题，更新到echarts4+, echarts-for-react插件也更新以及依赖更新就ok了
