### ISSUE TITLE
HideLoading, when storing multiple instances

### ISSUE THREAD

**Issue by AllanCodes** [hustcc/echarts-for-react#162]
Hi, when creating an instance of a chart, I'm able to hideloading with no problem, by calling hideLoading() after setOption().  However, when working with an array of instances for some reason all instances, usually only 1 instance if that, work with hideLoading().

```jsx
<ReactEcharts ref={(e) => { this.echarts_react[i] = e; }}
                option={this.vars.subalgorithms[i].graph ? this.vars.subalgorithms[i].graph.getOption() : this.vars.defaultScatterOptions }
                showLoading={true}
                style={{height: '100%', width: '100%'}}
            />
```

```jsx
 this.echarts_react[r.identification.vars.i].getEchartsInstance().setOption( g.getOption() );
      this.echarts_react[r.identification.vars.i].getEchartsInstance().hideLoading();
      this.forceUpdate();
```

For some reason, when storing in an array the instance does not react to the hideLoading().  I am sure that I am calling the instances correctly, but it just doesn't react to the hideLoading() function.  Is there an apparent problem here?

**Comment by hustcc** [comment]
Your usage is not very react-like.

You should set `option` and `showLoading` into state instead of call setOption manually.

**Comment by AllanCodes** [comment]
@hustcc 

Possible to provide an example?  I'm not very smooth with React.

**Comment by hustcc** [comment]
```jsx

class Componet {
  constructor() {
    this.state = {
        option: {},
        showLoading: true,
    }
  }

  fetchData = () => {
    this.setState({
      showLoading: true,
    });
    // ... do async code
    // ...
    this.setState({
      showLoading: false,
      option: this.calcOption(),
    });
  }

  render() {
    return (
      <ReactEcharts
        option={this.state.option}
        showLoading={this.state.showLoading}
        style={{height: '100%', width: '100%'}}
      />
    );
  }
}
```
