### ISSUE TITLE
Enterable tooltip on map chart?

### ISSUE THREAD

**Issue by erezcarmel** [hustcc/echarts-for-react#164]
Is it possible to make the map chart tooltip to be enterable?
The `enterable: true` parameter does not work because the tooltip moves with the cursor position. Is it possible to make the tooltip show over a country without moving with the cursor?
Any other way doing it?

**Comment by hustcc** [comment]
Demo option below:

```js
tooltip: {
  trigger: 'axis',
  enterable: true,
},
```
