### ISSUE TITLE
Issue regarding your documentations of the options object.

### ISSUE THREAD

**Issue by ikteru** [hustcc/echarts-for-react#167]
I found an issue when I was trying to understand a react dashboard template, I found that the Option object is used quiet a lot! 
When I came to consult the documentation, I found that the page documenting the option object is not working: http://echarts.baidu.com/option.html#title

Please make it work.

**Comment by hustcc** [comment]
not work ? Why

**Comment by hustcc** [comment]
All config of echarts is option object.
