### ISSUE TITLE
How can I customize the item colors in Legend?

### ISSUE THREAD

**Issue by ikteru** [hustcc/echarts-for-react#168]
Hello,

I'm trying to change the colors of the bars in my Bar chart. But they're set automatically and I would like to change the color for this Chart ALONE without changing the default color array. 
And of course since the color of the bar will change, I want the Legend color to change with it! 

How can I do that? 

Thank you!

**Comment by jjzjx118** [comment]
hi,hustcc. 我尝试了注册 theme 的方法,但是没有成功.在 Echarts 的自定义构建工具栏里下载的似乎是整个 option 的配置. 呢么 整个 theme 如果传递构建工具生成的 json 文件,是否和 option 冲突了呢?
