### ISSUE TITLE
How can I make a "Half" Doughnut chart?

### ISSUE THREAD

**Issue by ikteru** [hustcc/echarts-for-react#169]
Hello, 

I'm using this library to make all of my charts, and I want to make a "Half Doughnut" chart, something like this: 
![image](https://user-images.githubusercontent.com/24244295/37844175-ceae1a0a-2ebe-11e8-868d-4e444b524fab.png)

However, the options object doesn't contain a single parameter where I could change the Pie chart into a Half Pie chart ( Half Doughnut Chart ). And there is no pre-configured Half Doughnut chart! There isn't even a preconfigured Doughnut Chart .

Someone suggested I use an other library, but I don't to do that! I like to keep things uniform and I really like this particular library.

Please answer me as soon as possible.

**Comment by hustcc** [comment]
Demo is here: http://echarts.baidu.com/examples/editor.html?c=pie-doughnut

All the document of echarts [here](https://ecomfe.github.io/echarts-doc/public/en/index.html).

**Comment by ikteru** [comment]
I'm not sure you understood what I said, I said "HALF" a doughnut chart ,, not a doughnut chart!

**Comment by hustcc** [comment]
Maybe it is not supported by echarts.

**Comment by erocks2010** [comment]
app.title = '环形图';

option = {
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}: {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'half semi',
            type:'pie',
            radius: ['50%', '70%'],
            center: ['50%', '100%'],
            startAngle:180,
            endAngle:360,
            avoidLabelOverlap: false,
            label: {
                normal: {
                    show: false,
                    position: 'center'
                },
                emphasis: {
                    show: true,
                    textStyle: {
                        fontSize: '30',
                        fontWeight: 'bold'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:3, name:'ok'},
                {value:5, name:'bad'},
                {value:2, name:'warning'},
                {value:10, name:'bottom'}
            ]
        }
    ]
};




had the same requirement. This is what I did .

**Comment by erocks2010** [comment]
![capture](https://user-images.githubusercontent.com/17801612/45537021-cb0ea900-b820-11e8-835d-688ca549820d.PNG)

**Comment by full-stack-dev-mex** [comment]
You want a Gauge component https://echarts.apache.org/examples/en/editor.html?c=gauge

**Comment by david31021** [comment]
Anyone know how to do this in R using the library echarts4r?

**Comment by rafacc87** [comment]
You need bottom of 180º and WALA!

var start = 180*90/100;
var end = 180*10/100;
var discard = 180;

option = {
    series: [{
        name: 'half semi',
        type: 'pie',
        radius: ['50%', '70%'],
        center: ['50%', '100%'],
        startAngle: 180,
        clockwise: true,
        data: [{
                value: start,
                name: 'ok'
            },
            {
                value: end,
                name: 'bad'
            },
            {
                value: discard,
                name: 'discard'
            }
        ]
    }]
};

**Comment by masum-mollik-rocketml** [comment]
turning on decals for half doughnut chart makes bottom half visible
