### ISSUE TITLE
[BABEL] 

### ISSUE THREAD

**Issue by XiaoFanTuan** [hustcc/echarts-for-react#17]
TransformError: /Users/xxxx/workspace/xxxx/node_modules/echarts-for-react/lib/echarts-for-react.js: [BABEL] /Users/xxxx/workspace/xxxx/node_modules/echarts-for-react/lib/echarts-for-react.js: Unknown option: foreign.Children. Check out http://babeljs.io/docs/usage/options/ for more info
怎么办呢

**Comment by hustcc** [comment]
可以告知一下具体环境吗？

**Comment by XiaoFanTuan** [comment]
是不是在react-native中不能使用啊，其实不是很懂

**Comment by hustcc** [comment]
rn我也没有试过，没有玩过rn，如果你能够帮忙解决，欢迎pull代码…
