### ISSUE TITLE
怎么添加百度地图官方提供的控件呢？

### ISSUE THREAD

**Issue by shulanDeng** [hustcc/echarts-for-react#170]
比如平移缩放控件，比例尺等

**Comment by hustcc** [comment]
官方是使用 option 配置实现的吧？这个项目也是配置 option 即可，没有其他什么特殊的做法！

**Comment by hustcc** [comment]
官方是使用 toolbox，使用这个项目的时候，构造 option 也加入 toolbox 即可，使用方法是一样的！

**Comment by hustcc** [comment]
```jsx

getOption = () => {
  return {
    toolbox: {}, // 在这里写你的控件就好了，拼接 option 结构和 echarts 官方一致！
  }
}

<ReactEcharts
  option={this.getOption()}
/>
```

**Comment by shulanDeng** [comment]
恩恩好的，我懂你的意思了。感谢~

**Comment by ruur** [comment]
@shulanDeng  @hustcc  请问 平移缩放控件，比例尺等 最终是如何实现的，怎么能通过toolbox拼接成一个平移缩放控件呢？

**Comment by ruur** [comment]
@shulanDeng echarts官方的toolbox似乎并没有平移缩放相关的配置，而这些控件本身是百度地图的，如果你实现了，可否贴一段代码上来供我参考一下，谢谢。

**Comment by shulanDeng** [comment]
@ruur 我也没有找到echarts官方的平移缩放配置，只有一个数据区域缩放，在可以拖拽的地图区域上使用是实现不了的。之后我也没有深究~你要是研究出来了可以告诉下我实现原理~
