### ISSUE TITLE
How to cancel dot's flash in the dynamic chart?

### ISSUE THREAD

**Issue by Evanna51** [hustcc/echarts-for-react#171]
example : http://git.hust.cc/echarts-for-react/#/echarts/dynamic?_k=z75yp2

when time and xAxis updated, Some dots in the line are show itself, but some one else, it's look likes flash.

So, Is there any way to solve this problem?

**Comment by hustcc** [comment]
不知道你要表达什么意思？

**Comment by Evanna51** [comment]
之前担心用中文不礼貌,所以用半吊子英文写的
就是在dynamic chart里, 随着时间和x轴的刷新, 有的坐标点会"闪", 
具体表为数据载入的时候, 有的点会显示出自己的那个白色圈圈,有的点不会,
公司电脑不能上传github的图片, 等我下班后再截图给您

**Comment by hustcc** [comment]
什么浏览器呢？

使用 chrome 试试看，也许就是 echarts 渲染的问题！
