### ISSUE TITLE
Refresh tooltip content

### ISSUE THREAD

**Issue by erezcarmel** [hustcc/echarts-for-react#173]
I'm using a tooltip with a button, once the user pushes the button, a new data should be loaded and shown in the tooltip.
How can I add new content into the tooltip without reopening it?

**Comment by hustcc** [comment]
update the formatter of tooltip in option, then update the option by set it into component state.

**Comment by erezcarmel** [comment]
@hustcc Do you have a codepen boilerplate with echarts-for-react implemented?

**Comment by erezcarmel** [comment]
@hustcc Please see this test case I've created:
https://github.com/erezcarmel/echarts-tooltip-test-case

Look for the 'Question' comment in the code to understand what I'm trying to do.
Thanks.

**Comment by hustcc** [comment]
Save your chart option into state.

```js
class MyChart extends Component {
   state = {
     chartOption: {
        ...options,
        tooltip: {
            ...options.tooltip,
            position: point => [point[0] + 10, point[1] + 10],
            formatter: params => MyChart.generateTooltip(params),
        }
    }
  }
  componentWillReceiveProps(nextProps) {
      // then re-generate chart option by nextProps.extraData
      // and set the chart option into state

    this.setState({
      chartOption: this.generateChartOption(), // TODO
    })
  }
}
```

**Comment by erezcarmel** [comment]
@hustcc I've updated my test case demo by your solution, and it's still not working.
I expect the new 'extraData' loaded to the MyChart component to be shown in the tooltip instead of the 'load more' text link. Still not working.

**Comment by hustcc** [comment]
You should setState with immutable method.

**Comment by erezcarmel** [comment]
@hustcc I'm using an immutable method AND creating a new object, but still the tooltip does not re-render once I click the link. Can you review my code and give me a solution for this?
