### ISSUE TITLE
src/core里的componentDidUpdate是否可以改进一下

### ISSUE THREAD

**Issue by anyexinglu** [hustcc/echarts-for-react#174]
https://github.com/hustcc/echarts-for-react/blob/master/src/core.jsx#L21 

    componentDidUpdate(prevProps) {
      // const echartObj = this.renderEchartDom(); 移到下面👇
      // 以下属性修改的时候，需要 dispose 之后再新建
      // 1. 切换 theme 的时候
      // 2. 修改 opts 的时候
      // 3. 修改 onEvents 的时候，这样可以取消所以之前绑定的事件 issue #151
      if (
        prevProps.theme !== this.props.theme ||
        !isEqual(prevProps.opts, this.props.opts) ||
        !isEqual(Object.keys(prevProps.onEvents || {}).sort(), Object.keys(this.props.onEvents || {}).sort())
      ) {
        this.dispose();
        this.rerender(); // 重建
        return;
      }
      const echartObj = this.renderEchartDom() // 👆挪到这里`

这样避免在dispose前renderEchartDom，因为rerender里还会执行renderEchartDom

**Comment by hustcc** [comment]
好像是一个优化点，可以提交一个 pr，看看单测和 demo 是否正常？

**Comment by zhaodagang** [comment]
可以实现实时趋势图 吗？

**Comment by hustcc** [comment]
可以，请看 live demo.
