### ISSUE TITLE
Running into some performance issues... 

### ISSUE THREAD

**Issue by grahambryan** [hustcc/echarts-for-react#175]
Hello I am running into some performance issues and am only looking to make interactive line graphs. I am working with 80,000 + data points per series. I am wondering if you have any suggestions on how to improve my performance within my code: 

````
class Plot extends React.Component {


  getOption = () => {
    const ddv = this.props.dropdownValue;
    const gf1=this.props.gf1;
    const gf2=this.props.gf2;
    const pcf_array=this.props.pcf_array;
    const time_array=this.props.time_array;

    var xData = time_array; // this should always be the same for each chart
    const legend = pcf_array;
    const xlabel = 'DOY';
    if (ddv === 'C' || ddv === 'D') {
      if (ddv === 'C') {
        // var data = [this.props.plotData.C];
        var data = gf1;
      } else {
        // data = [this.props.plotData.D];
        data = gf2;
      } 
      // build y values series object array 
      var series = [];
      var cnt=0;
      for (let key in data) {
        series.push({
          name: legend[cnt], 
          type: this.props.plotType, 
          data: data[key],
          showSymbol: false,
          hoverAnimation: false,
        })
        cnt = cnt + 1;
      };
      var grid = {bottom: 85};
      // x axis settings and lables
      var xAxis = {
                  boundaryGap: false,
                  data: xData,
                  name: xlabel,
                  nameLocation: 'center',
                  nameGap: 35
                };
      // y axis settings and lables   
      var yAxis = {
                  type: 'value',
                  //name: this.props.plotTitle.y,
                  nameLocation: 'center',
                  nameGap: 40,
                  // min: 'dataMin',
                  // max: 'dataMax'
                  scale: true
                };
      // dataZoom settings
      var dataZoom =[
                {
                    show: true,
                    //realtime: true,
                },
                {
                    type: 'inside',
                    //realtime: true,
                }
      ];
      // toolTip option 
      var axisPointer = {
            link: {xAxisIndex: 'all'}
        };
      // dataZoom pointer drag titles
      var dataZoomFeature = {
                  title: {
                    zoom: 'area zoom',
                    back: 'last zoom'
                  }
            };
    } else {
      var dataC = gf1;
      var dataD = gf2;
      var seriesC = [];
      var seriesD = [];
      var cnt2 = 0;
      for (let key in dataC) {
        seriesC.push(
          {
            name: legend[cnt2],//dataC[i]._name, 
            type: this.props.plotType, 
            data: dataC[key],
            showSymbol: false,
            hoverAnimation: false,
            sampling: sampling
          })
        cnt2 = cnt2 + 1;
      };
      var cnt3 = 0;
      for (let key in dataD) {
        seriesD.push(
          {
            name: legend[cnt3], 
            type: this.props.plotType, 
            data: dataD[key],
            xAxisIndex: 1,
            yAxisIndex: 1,
 },
            showSymbol: false,
            hoverAnimation: false,
            sampling: sampling

          })
        cnt3 = cnt3 + 1;
      };
      series = seriesC.concat(seriesD);
      // build grid and axes for two plot view
      grid = [
              {
                    left: 50,
                    right: 50,
                    height: '35%'
                }, 
                {
                    left: 50,
                    right: 50,
                    top: '55%',
                    height: '35%'
                }
            ];
       xAxis = [
                  {
                      boundaryGap : false,
                      axisLine: {onZero: true},
                      data: xData,
                      name: 'DOY',
                      nameLocation: 'center',
                      nameGap: 20
                  },
                  {
                      gridIndex: 1,
                      boundaryGap : false,
                      axisLine: {onZero: true},
                      data: xData,
                      show: false,
                      position: 'top'
                  }
              ];
      yAxis = [
                  {
                      //name : this.props.plotTitle.y,
                      type : 'value',
                      nameLocation: 'center',
                          nameGap: 30,
                        scale: true
                  },
                  {
                      gridIndex: 1,
                      type : 'value',
                          scale: true
                  }
              ];
      dataZoom = [
                  {
                      show: true,
                      type: 'inside',
                      //realtime: true,
                      // start: 30,
                      // end: 70,
                      xAxisIndex: [0, 1]
                  },
                  {
                      //realtime: true,
                      // start: 30,
                      // end: 70,
                      xAxisIndex: [0, 1]
                  }
              ];
      axisPointer = {
                    link: {xAxisIndex: 'all'}
            };

      dataZoomFeature = {
                        yAxisIndex: 'none',
                        title: {
                          zoom: 'area zoom',
                          back: 'last zoom'
                        }
                };
    };

    const ddvName = this.props.dropdownValue==='both' ? 'C (top) and D (bottom)' : this.props.dropdownValue;
    const options = {
            title: {
                subtext: ddvName,
                x: 'center',
            },
            tooltip: {
              trigger: 'axis', //'axis' 'none'
              transitionDuration: 0,
            },
            grid: grid,
            toolbox: {
            feature: {
                saveAsImage: {
                  title: 'save as png'
                },
                restore: {
                  title: 'restore'
                },
                dataZoom: dataZoomFeature,
            },
            z: 500000,
            right: '5%',
            orient: 'horizontal',
            itemGap: 20,
            showTitle: true
        },
            legend: {
                data: legend,
                x: 'left'
            },
            yAxis: yAxis,
            xAxis: xAxis,
            axisPointer: axisPointer,
            dataZoom: dataZoom,
            series: series,
            //animation: false
        };
    return options
  };

  render () {
    return (
      <div  >  
        <ReactEcharts
          key={this.props.plotTitle.main+'_'+this.props.dropdownValue}
          option={this.getOption()}
          style={{width: '100%', height:'500px'}}
          className='react_for_echarts'
        /> 
      </div>

```

**Comment by hustcc** [comment]
whether it is issue of `echarts-for-react`, or issue of `echarts`.

**Comment by grahambryan** [comment]
true! Is the setup you see an optimal one? Meaning do you see any issues with how I have set it up that may cause my performance to be bad?

**Comment by hustcc** [comment]
no need to set key props.

Other settings seem no problem.

**Comment by grahambryan** [comment]
Actually, looks like I need the key prop, either on the div tag or the component.  

> DataZoomModel.js:166 Uncaught TypeError: Cannot read property '__dzAxisProxy' of undefined
    at ExtendedClass.<anonymous> (DataZoomModel.js:166)
    at ExtendedClass.<anonymous> (DataZoomModel.js:376)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.<anonymous> (DataZoomModel.js:375)
    at helper.js:42
    at Array.forEach (<anonymous>)
    at Object.each (util.js:298)
    at helper.js:32
    at ExtendedClass.eachTargetAxis (DataZoomModel.js:374)
    at ExtendedClass._giveAxisProxies (DataZoomModel.js:163)
    at ExtendedClass.doInit (DataZoomModel.js:155)
    at ExtendedClass.mergeOption (DataZoomModel.js:126)
    at ExtendedClass.<anonymous> (Global.js:190)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.visitComponent (Global.js:174)
    at Function.entity.topologicalTravel (component.js:86)
    at ExtendedClass.mergeOption (Global.js:156)
    at ExtendedClass.resetOption (Global.js:106)
    at ExtendedClass.setOption (Global.js:85)
    at ECharts../node_modules/echarts/lib/echarts.js.echartsProto.setOption (echarts.js:352)
    at EchartsReactCore._this.renderEchartDom (core.js:107)
    at EchartsReact.componentDidUpdate (core.js:133)
    at commitLifeCycles (react-dom.development.js:8778)
    at commitAllLifeCycles (react-dom.development.js:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at commitRoot (react-dom.development.js:10050)
    at performWorkOnRoot (react-dom.development.js:11017)
    at performWork (react-dom.development.js:10967)
    at batchedUpdates (react-dom.development.js:11086)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)
(anonymous) @ DataZoomModel.js:166
(anonymous) @ DataZoomModel.js:376
each @ util.js:298
(anonymous) @ DataZoomModel.js:375
(anonymous) @ helper.js:42
each @ util.js:298
(anonymous) @ helper.js:32
eachTargetAxis @ DataZoomModel.js:374
_giveAxisProxies @ DataZoomModel.js:163
doInit @ DataZoomModel.js:155
mergeOption @ DataZoomModel.js:126
(anonymous) @ Global.js:190
each @ util.js:298
visitComponent @ Global.js:174
entity.topologicalTravel @ component.js:86
mergeOption @ Global.js:156
resetOption @ Global.js:106
setOption @ Global.js:85
./node_modules/echarts/lib/echarts.js.echartsProto.setOption @ echarts.js:352
EchartsReactCore._this.renderEchartDom @ core.js:107
componentDidUpdate @ core.js:133
commitLifeCycles @ react-dom.development.js:8778
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
index.js:2178 The above error occurred in the <EchartsReact> component:
    in EchartsReact (at Plot.js:249)
    in div (at Plot.js:248)
    in Plot (at PlotSegmentsDisplay.js:90)
    in div (at PlotSegmentsDisplay.js:82)
    in div (at PlotSegmentsDisplay.js:75)
    in div (at PlotSegmentsDisplay.js:74)
    in PlotSegment (at PlotSegmentsDisplay.js:37)
    in div (at PlotSegmentsDisplay.js:36)
    in div (at PlotSegmentsDisplay.js:34)
    in PlotSegmentsList (created by Connect(PlotSegmentsList))
    in Connect(PlotSegmentsList) (at App.js:19)
    in div (at App.js:17)
    in PredefinedPlots (at App.js:26)
    in Provider (at App.js:25)
    in WrappedApp (at index.js:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2178
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
commitRoot @ react-dom.development.js:10058
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
DataZoomModel.js:166 Uncaught TypeError: Cannot read property '__dzAxisProxy' of undefined
    at ExtendedClass.<anonymous> (DataZoomModel.js:166)
    at ExtendedClass.<anonymous> (DataZoomModel.js:376)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.<anonymous> (DataZoomModel.js:375)
    at helper.js:42
    at Array.forEach (<anonymous>)
    at Object.each (util.js:298)
    at helper.js:32
    at ExtendedClass.eachTargetAxis (DataZoomModel.js:374)
    at ExtendedClass._giveAxisProxies (DataZoomModel.js:163)
    at ExtendedClass.doInit (DataZoomModel.js:155)
    at ExtendedClass.mergeOption (DataZoomModel.js:126)
    at ExtendedClass.<anonymous> (Global.js:190)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.visitComponent (Global.js:174)
    at Function.entity.topologicalTravel (component.js:86)
    at ExtendedClass.mergeOption (Global.js:156)
    at ExtendedClass.resetOption (Global.js:106)
    at ExtendedClass.setOption (Global.js:85)
    at ECharts../node_modules/echarts/lib/echarts.js.echartsProto.setOption (echarts.js:352)
    at EchartsReactCore._this.renderEchartDom (core.js:107)
    at EchartsReact.componentDidUpdate (core.js:133)
    at commitLifeCycles (react-dom.development.js:8778)
    at commitAllLifeCycles (react-dom.development.js:9946)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at commitRoot (react-dom.development.js:10050)
    at performWorkOnRoot (react-dom.development.js:11017)
    at performWork (react-dom.development.js:10967)
    at batchedUpdates (react-dom.development.js:11086)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)


I am getting the above error when I try to transition to this section of the if statement (by changing the dropdown value) when I do not leave the key prop. 
`else {
      // build options for viewing BOTH satellites at once
      var dataC = gf1;
      var dataD = gf2;
      var seriesC = [];
      var seriesD = [];
      var cnt2 = 0;
      for (let key in dataC) {
        seriesC.push(
          {
            name: legend[cnt2],//dataC[i].PCF_name, 
            type: this.props.plotType, 
            data: dataC[key],
            showSymbol: false,
            hoverAnimation: false,
            sampling: sampling
          })
        cnt2 = cnt2 + 1;
      };
      var cnt3 = 0;
      for (let key in dataD) {
        seriesD.push(
          {
            name: legend[cnt3], 
            type: this.props.plotType, 
            data: dataD[key],
            xAxisIndex: 1,
            yAxisIndex: 1,
 },
            showSymbol: false,
            hoverAnimation: false,
            sampling: sampling

          })
        cnt3 = cnt3 + 1;
      };
      series = seriesC.concat(seriesD);
      // build grid and axes for two plot view
      grid = [
              {
                    left: 50,
                    right: 50,
                    height: '35%'
                }, 
                {
                    left: 50,
                    right: 50,
                    top: '55%',
                    height: '35%'
                }
            ];
       xAxis = [
                  {
                      boundaryGap : false,
                      axisLine: {onZero: true},
                      data: xData,
                      name: 'DOY',
                      nameLocation: 'center',
                      nameGap: 20
                  },
                  {
                      gridIndex: 1,
                      boundaryGap : false,
                      axisLine: {onZero: true},
                      data: xData,
                      show: false,
                      position: 'top'
                  }
              ];
      yAxis = [
                  {
                      //name : this.props.plotTitle.y,
                      type : 'value',
                      nameLocation: 'center',
                          nameGap: 30,
                        scale: true
                  },
                  {
                      gridIndex: 1,
                      type : 'value',
                          scale: true
                  }
              ];
      dataZoom = [
                  {
                      show: true,
                      type: 'inside',
                      //realtime: true,
                      // start: 30,
                      // end: 70,
                      xAxisIndex: [0, 1]
                  },
                  {
                      //realtime: true,
                      // start: 30,
                      // end: 70,
                      xAxisIndex: [0, 1]
                  }
              ];
      axisPointer = {
                    link: {xAxisIndex: 'all'}
            };

      dataZoomFeature = {
                        yAxisIndex: 'none',
                        title: {
                          zoom: 'area zoom',
                          back: 'last zoom'
                        }
                };
    };`




It works when the key prop is unique to each plot I create. A little more background - I am creating a list of unique plots. Can you see a reason for this error when im viewing the grided plots?

**Comment by hustcc** [comment]
Can you give me an online demo?

**Comment by ggregoire** [comment]
Same for me, having about 10,000 data points. Here the perf chart:

<img width="1315" alt="screen shot 2018-04-20 at 12 53 33 pm" src="https://user-images.githubusercontent.com/591804/39066314-3d031582-449a-11e8-8f47-85882591d2d1.png">

I don't know if we could reduce the initial mounting and all the stuff happening in `componentDidMount`.

**Comment by hustcc** [comment]
when `componentDidMount`, the echarts will initial the DOM, and render the data(10000+) , seems to be a reasonable performance consumption

**Comment by grahambryan** [comment]
@hustcc sorry I do not have a demo ready at this time. I will let you know if I make any improvements.

**Comment by hustcc** [comment]
Do something to save the performance in new version v2.0.9, you can download for test again!

**Comment by hustcc** [comment]
May be it is the performance issue of [echarts](https://github.com/apache/incubator-echarts).

Echarts-for-react do nothing except initial the dom and set the option into echarts.

**Comment by sylsaint** [comment]
@grahambryan you should use echarts-gl when data points is at large scale

**Comment by JacobMillward** [comment]
@sylsaint How can you use echarts-gl for 2D graphs?

**Comment by sylsaint** [comment]
@JacobMillward http://echarts.baidu.com/option-gl.html#series-scatterGL

It can be used in 2D graphs. But there is only Chinese version of GL-options. Sorry for the inconvenience.

**Comment by hustcc** [comment]
demo here https://github.com/hustcc/echarts-for-react/blob/master/demo/src/charts/Gl.jsx

**Comment by jcviau** [comment]
@sylsaint @hustcc I cannot find an example of 2D line graph with GL. Is it really possible ?
