### ISSUE TITLE
geo 地图中的 onEvents 点击事件不起作用？

### ISSUE THREAD

**Issue by terrence386** [hustcc/echarts-for-react#177]
geo 地图中的 onEvents 点击事件不起作用？ 需要别的什么组件吗?

**Comment by hustcc** [comment]
geo 的事件有哪些？你在 echarts 文档上弄清楚没有？

另外，你的代码是怎么写的？onEvents 里面指定了哪些？

**Comment by terrence386** [comment]
echarts 从3.0 开始，geo已经开始支持click事件了，但是在onEvents中指定click事件，geo也不会触发，这就奇怪了

**Comment by hustcc** [comment]
你可以在官方网站找一个 geo click 的 demo 看看！
