### ISSUE TITLE
How to clear the old data?

### ISSUE THREAD

**Issue by stevelacerda7** [hustcc/echarts-for-react#178]
I'm having a hard time clearing out the old data. So, I have several echart components on a single page, and the data varies depending on the users selection of metrics. So, there can be 2 or 10 metrics. What I'm seeing is that when users deselect a metric, the data remains.

How do I re-initialize before re-rendering the component? Basically, I want a fresh canvas on each render.

**Comment by hustcc** [comment]
Can you help to submit a pr, and add it in the readme at `QA` chapter.

**Comment by PipiHua** [comment]
> Set props `notMerge` with true, maybe can help you.

I have a problem now, notMerge=false, I set the data=[] of the series according to the name. The result cannot be cleared, but sometimes it can be cleared. What's the matter?
