### ISSUE TITLE
Have you seen any issues with legend.scroll?

### ISSUE THREAD

**Issue by stevelacerda7** [hustcc/echarts-for-react#182]
The click event for legend.scroll is not working for me. My legend options look like:

`legend: {
  data: this.props.legendData,
  type: 'scroll',
  scrollDataIndex: 0,
  orient: 'horizontal',
  show: true,
},`

**Comment by stevelacerda7** [comment]
Okay, so I've done some more digging, and no luck. It seems that the onEvents triggers fine when I click on a legend data point, meaning on/off of the line or bar or whatever. It clearly triggers the onEvents handler, but not when I click on the scroll buttons. I tried legendselectchanged also, no luck. Any ideas?

**Comment by hustcc** [comment]
I think you should review the events of echarts [here](http://echarts.baidu.com/api.html#events)

I do not know whether is legends click event supported by echarts.
