### ISSUE TITLE
在antd-pro中使用时，刷新界面图表超出边界

### ISSUE THREAD

**Issue by zhangyu921** [hustcc/echarts-for-react#187]
![image](https://user-images.githubusercontent.com/19166761/39860294-615b68c8-546f-11e8-81fd-d9bf633e83a5.png)

代码是标准的正常使用代码，自其它页面进入就没有问题，仅在刷新时出现，父组件是Card

**Comment by hustcc** [comment]
可以截图看看效果吗？

**Comment by hustcc** [comment]
可以看看是不是因为 Card 在初始化的时候宽度太大的原因导致的！

echarts-for-react 中的图形在渲染的时候，保持沾满父容器宽度！
