### ISSUE TITLE
echart未能准确更新。

### ISSUE THREAD

**Issue by lzr900515** [hustcc/echarts-for-react#188]
根据查询条件首先生成echart图表有三条曲线，然后变更查询条件，数据为零条曲线。这时上次的三条曲线还留在图中。
`
<ReactEcharts option={{...option}} style={{height, width: '100%'}/>
`

**Comment by hustcc** [comment]
notMerge 属性设置为 true 试试看。

**Comment by lzr900515** [comment]
赞~感谢。完美解决。
