### ISSUE TITLE
如何在airport demo中展示行政区名称

### ISSUE THREAD

**Issue by jasonpanacea** [hustcc/echarts-for-react#189]
你好，我想用geo形式展示一些行政区对应的数据，参考了你airport的demo，自己也研究了一下，但是没找到如何展示行政区名称的方法，现在地图上有行政区的边界，但是却没有展示出省市的名称。
我看了china.js的数据中是有各个省名称的，但是却不知道怎么显示，请问有具体的方法吗？谢谢

**Comment by hustcc** [comment]
这个问题，可能需要你去查阅一下 echarts 关于地图的使用文档。本项目不会修改 echarts 的使用方式。

对于地图的使用，我这边没有太多涉猎，所以没有办法直接回答你的问题，不好意思！
