### ISSUE TITLE
2.0.8版本 style传入{height:100%} 渲染出canvas 高度100px

### ISSUE THREAD

**Issue by or2byd** [hustcc/echarts-for-react#193]

**Comment by SidKwok** [comment]
你这个问题应该是父容器没有高度，如果父容器没有高度而图表设置了高度的话，echarts会默认给一个100px的高度，你这种情况给父容器设置一个高度就可以了

**Comment by himyyy** [comment]
创建的父节点是有高度的，出现在2.0.8版本上，2.0.5没有问题。

**Comment by SidKwok** [comment]
@himyyy 看看相关代码

**Comment by hustcc** [comment]
@himyyy 只有 2.0.5 是好的？

2.0.6、2.0.7、2.0.8 都是坏的吗？

**Comment by SidKwok** [comment]
你父容器的高度是固定的吗 还是说有变化

**Comment by himyyy** [comment]
固定的，只是初始默认设置的100%

**Comment by himyyy** [comment]
嗯，直接写死是正常显示的

**Comment by himyyy** [comment]
![7uh am 3sq2x wff zmcb](https://user-images.githubusercontent.com/13343279/40300819-ee41aec2-5d1c-11e8-898c-17934e133cc4.png)
现在没有复现出来，只有这个图片

**Comment by SidKwok** [comment]
建议你在得到最后的高度之后，调用一下echarts的resize

**Comment by himyyy** [comment]
好的，谢谢

**Comment by SidKwok** [comment]
客气
