### ISSUE TITLE
x轴刻度不从0显示

### ISSUE THREAD

**Issue by ting0125** [hustcc/echarts-for-react#194]
option配置的代码如下：
const option = {
    xAxis: {
        type: 'category',
        data: ['2017-05-01', '2017-05-02', '2017-05-03', '2017-05-04', '2017-05-05', '2017-05-06','2017-05-07'],
        boundaryGap: false,
        splitLine: {
            show: true,
            interval: 'auto',
            lineStyle: {
                color: ['#D4DFF5']
            }
        },
        axisTick: {
            show: false
        },
        axisLine: {
            lineStyle: {
                color: '#609ee9'
            }
        },
        axisLabel: {
            margin: 10,
            textStyle: {
                fontSize: 10
            }
        }
    },
    yAxis: {
        type: 'value',
        splitLine: {
            lineStyle: {
                color: ['#D4DFF5']
            }
        },
        axisTick: {
            show: false
        },
        axisLine: {
            lineStyle: {
                color: '#609ee9'
            }
        },
        axisLabel: {
            margin: 0,
            textStyle: {
                fontSize: 8
            }
        }
    },
    series: [{
        name: '昨日',
        type: 'bar',
        data: ['1200', '1400', '808', '811', '626', '488', '1600'],
    }]
};
问题：x轴从0开始的，导致x轴的第一个数据覆盖在y轴上

**Comment by hustcc** [comment]
这个是 echarts option 配置的问题，可以到 echarts 项目下提问，或者查看 echarts 官网 demo 怎么写的😳

**Comment by ting0125** [comment]
好的，还有个问题，就是
axisLabel: {
            textStyle: {
                color: "#f00eff"
            }
        }
这里的字体颜色配置了没有任何效果，刻度线、轴线的颜色都可以正常配置的，这个。。。

**Comment by SidKwok** [comment]
这个也是 echarts option 配置的问题
