### ISSUE TITLE
using control box ?

### ISSUE THREAD

**Issue by jejesh26** [hustcc/echarts-for-react#196]
Dear,

how to display the control box, that enables to interact with the graph directly

I'm refering to the black control box in the website example that enables to modify the label positions and roation : 
https://ecomfe.github.io/echarts-examples/public/editor.html?c=bar-label-rotation

tried to use the same code as in the example, but the box doesn't show up.

Thks

**Comment by hustcc** [comment]
```js
toolbox: {
        show: true,
        orient: 'vertical',
        left: 'right',
        top: 'center',
        feature: {
            mark: {show: true},
            dataView: {show: true, readOnly: false},
            magicType: {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore: {show: true},
            saveAsImage: {show: true}
        }
    },
```

`toolbox` in option is the configure of control box.

**Comment by jejesh26** [comment]
I'm not talking about the tools box but the control box 
![image](https://user-images.githubusercontent.com/37058666/41229497-c67d3800-6dae-11e8-8abf-7aadf8bd0947.png)

**Comment by hustcc** [comment]
The control box is not rendered from echarts. Just a GUI demo to generate the option.

**Comment by jejesh26** [comment]
ok

2018-06-11 19:41 GMT+08:00 hustcc <notifications@github.com>:
