### ISSUE TITLE
字组件无法刷新

### ISSUE THREAD

**Issue by xingzhewj** [hustcc/echarts-for-react#197]
子组件采用class方式react组件时，父组件动态传递给子组件，无法刷新echars图表，设置了nomerage为false依旧不行。

**Comment by xingzhewj** [comment]
采用函数式子组件方式可可以正常刷新。

**Comment by RainWangjie** [comment]
遇到同样的问题，动态传入`option`无法刷新echarts图表。
```
 <ReactEcharts  option={option} />
```
`2.0.11`和`2.0.10`不行，`2.0.8`OK

**Comment by hustcc** [comment]
请使用 immutable 的方式修改 state 中的 option。
