### ISSUE TITLE
请问 v1.4.4 中依赖的 echarts 的版本号是多少？

### ISSUE THREAD

**Issue by Feel-Joy** [hustcc/echarts-for-react#198]
release 中貌似找不到关于 v1.4.4 的相关信息了，但是我有个项目中用的是此版本，现在出现了一些版本兼容的问题，所以需要知道 echarts-for-react 所依赖的 echarts 的版本号，求告知~

**Comment by hustcc** [comment]
你可以 npm i echarts-for-react@1.4.4 然后在 node_module 中看下 echarts 版本。

**Comment by Feel-Joy** [comment]
@hustcc ok, thx~
