### ISSUE TITLE
新人求教！圆饼图的中心圆的颜色如何设置？

### ISSUE THREAD

**Issue by xueguozhongli** [hustcc/echarts-for-react#199]
![image](https://user-images.githubusercontent.com/22338719/40910277-44037028-681e-11e8-8b77-c67d95a21962.png)
如图，中心部分如何设置成蓝色？还是说必须做成嵌套环形图？

目前代码：
app.title = '环形图';

option = {
    tooltip: {
        trigger: 'item',
        formatter: "{b}: {c} ({d}%)"
    },
    color:['#393939','#f5b031','#fad797','#59ccf7','#c3b4df'],
    legend: {
        orient: 'vertical',
        x: 'left',
        data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series: [
        {
            name:'访问来源',
            type:'pie',
            radius: ['15%', '35%'],
            avoidLabelOverlap:false,
            label: {
                normal: {
                    show: true,
                    position: 'center',
                    
                    formatter: function(){
                        return 8973
                    },
                    textStyle:{
                        fontSize:16,
                        color:'green'
                    }
                },
                emphasis: {
                    show: false
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ]
        }
    ]
};

**Comment by hustcc** [comment]
到 echarts 官方文档去找配置 demo 或者文档吧。

**Comment by xueguozhongli** [comment]
谢谢回复~~~最后解决办法，中间又画了一个pie：
const pieOption = {
    series: [
        {
            name:'外圈',
            type:'pie',
            silent:true,
            radius: ['15%', '35%'],
            hoverAnimation:false,
            avoidLabelOverlap:true,
            label: {
                normal: {
                    show: false,
                },
                emphasis: {
                    show: false
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[{name:'暂无数据',value:0}],
            color:[VendorColor['color_0'].full],
        }, {
            name:'车辆分布内圈',
            type:'pie',
            silent:true,
            radius: [0, '15%'],
            hoverAnimation:false,
            label: {
                normal: {
                    show: true,
                    position: 'center',
                    textStyle:{
                        fontSize:12,
                        color:'#fff'
                    }
                }
            },
            labelLine: {
                normal: {
                    show: false
                }
            },
            data:[
                {value:0, name:'暂无数据'}
            ],
            color:['#2E7AC8']
        },
    ]
};
