### ISSUE TITLE
貌似没有考虑兼容IE8

### ISSUE THREAD

**Issue by codering** [hustcc/echarts-for-react#2]
看了下lib里代码，default关键字并没有做特殊处理，在ie8下会有问题的。

**Comment by hustcc** [comment]
确实是的，感谢^_^~如果有空，欢迎PR代码~

**Comment by hustcc** [comment]
测试了一下，ie8问题貌似不少~

**Comment by codering** [comment]
可用用 es3ify-loader 做处理

**Comment by hustcc** [comment]
这个问题产生是因为babel6导致的，是不是我这边换成babel5也可以解决这个问题？

**Comment by codering** [comment]
babel5 可以。 我的意思用babel6的话，要再用es3ify-loader 处理下， 可以参考下antd的做法https://github.com/ant-design/ant-design/blob/master/webpack.config.js

**Comment by hustcc** [comment]
@codering 已经commit，babel 官方已经有类似plugins。

**Comment by codering** [comment]
Good job!
