### ISSUE TITLE
为什么放在移动端上，视图直接看不清了，求原因

### ISSUE THREAD

**Issue by SynChron1zed** [hustcc/echarts-for-react#20]
![image](https://cloud.githubusercontent.com/assets/18717051/19618540/ee71b562-987f-11e6-8fd0-c3d0642696ac.png)

**Comment by hustcc** [comment]
可以看下echarts的option配置，可以将一些margin，padding配置大一点。

**Comment by SynChron1zed** [comment]
@hustcc  不知道我去看下 我看了官网的 然后和我的对比了下 发现我的视图canvas height 和width 特别大

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/19619379/560be216-9898-11e6-84f1-5c63519a32cd.png)

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/19619386/6a197f66-9898-11e6-90dd-3c7f50bebe51.png)

**Comment by SynChron1zed** [comment]
@hustcc  上面的是官网的 下面的是我 图标设置的标签都一样

**Comment by hustcc** [comment]
你试试在移动端打开 [http://git.hust.cc/echarts-for-react/](http://git.hust.cc/echarts-for-react/)试试看。

排除下是不是一些css框架，在移动端导致的样式区别。
