### ISSUE TITLE
Theme props types is not correct

### ISSUE THREAD

**Issue by jejesh26** [hustcc/echarts-for-react#200]
Hi,

in your source the prop types is defined as String. It should be an array of string or shapes, as it is defined as an object in echarts.js

Although have error in the console :
[
echarts Failed prop type: Invalid prop `theme` of type `object` supplied to `EchartsReact`, expected `string`.](url)

**Comment by hustcc** [comment]
You are right.

I think the best practices is `registerTheme ` theme object firstly, then use the theme name string.

**Comment by hustcc** [comment]
Maybe you can push a pr.
