### ISSUE TITLE
本项目运行起来之后,修改代码后刷新页面,页面没有更新

### ISSUE THREAD

**Issue by despagito** [hustcc/echarts-for-react#201]
Compiled successfully 之后刷新的页面.

**Comment by hustcc** [comment]
可以再具体点吗？

**Comment by despagito** [comment]
clone这个项目之后,我尝试改了点`demo/src/App.jsx`的内容(比如删掉`<h1>`),但是compiled之后,刷新页面没有变化,然后我又改了`demo/src/index.js`里面的console.log输出,compiled之后还是没有变化.
webpack明明检测到了变化,并且 Compiled successfully,不知道为什么页面就是没有变化.

**Comment by despagito** [comment]
不过,我新添加的路由和新页面倒是生效了,访问也没有问题.
