### ISSUE TITLE
Rendering echarts-for-react on server side?

### ISSUE THREAD

**Issue by erezcarmel** [hustcc/echarts-for-react#202]
Is it possible to render Echarts using echarts-for-react on server side?
I have a React component with ReactEcharts (using svg renderer) and rendering it `ReactDOMServer.renderToStaticMarkup(React.createElement(Component))`.

When I save the html to local file, I only get this:

`<div class="echarts-for-react "></div>`

**Comment by hustcc** [comment]
I do not know whether ssr is supported by `echarts`.
