### ISSUE TITLE
Update the options but it is not re-render

### ISSUE THREAD

**Issue by hxg543453406** [hustcc/echarts-for-react#203]
when I change the datas,but the echarts do not re-render, how can I to fix it?

> BPMOption.xAxis.data
> BPMOption.series[i].data

 
```
this.state ={BPMOption: {
  title: {
    text: '会员血压历史记录',
    textStyle: {
      fontSize: 18,
      fontWeight: 'normal',
      color: '#333'
    }
  },
  tooltip: {
    trigger: 'axis'
  },
  legend: {
    x:'center',
    y:'bottom',
    data:['收缩压','舒张压','心率'],
    icon: 'rect'
  },
  grid: {
    left: '3%',
    right: '4%',
    bottom: '12%',
    containLabel: true
  },
  xAxis: {
    type: 'category',
    boundaryGap: true,
    data: [],
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      name:'收缩压',
      type:'line',
      data:[],
    }, {
      name:'舒张压',
      type:'line',
      data:[],
    }, {
      name:'心率',
      type:'line',
      data:[],
    }
  ]
};
}


....
 <ReactEcharts
                  option={this.state.BPMOption}
                  notMerge
                  style={{ height: '300px', width: '100%' }}
                  lazyUpdate
                  theme={'theme_name'}
                />

```

**Comment by hustcc** [comment]
You should setState with an immutable method.

**Comment by hxg543453406** [comment]
@hustcc the options data is change,but the echarts is render on the first change data, the others is not re-render, someone suggest me to reset the options data null and reset option data

**Comment by hustcc** [comment]
The simplest method: before setState, you deepClone it first.

**Comment by hxg543453406** [comment]
@hustcc I do it, but does not works,.

**Comment by hustcc** [comment]
Show me your code.

**Comment by hxg543453406** [comment]
@hustcc I fix it. thank you

**Comment by hustcc** [comment]
After you fix the bug, You can write the solution here for others.

**Comment by logic1013** [comment]
I met the same problem, could you please write your solution here?

**Comment by hustcc** [comment]
@logic1013 You should update option with an immutable way.

**Comment by logic1013** [comment]
@hustcc I tried that, but in fact it also render on the first change data. And if I use echarts-for-react@2.0.4, it rendered as my mind. Why it does not works at echarts-for-react@2.0.13?

**Comment by hustcc** [comment]
Show me your code.

**Comment by logic1013** [comment]
@hustcc It seems something wrong, the code is a little out of order, sorry..

**Comment by RohanKhedekar21** [comment]
> @hustcc I fix it. thank you

can you plz share solution here

**Comment by ikikika** [comment]
hi, i encountered this problem as well but i set the prop of notMerge to true. and that fixed the issue. By default its false. hope this helps.
https://echarts.apache.org/en/api.html#echartsInstance.setOption

**Comment by zechau** [comment]
I fix this out by deep clone the option

**Comment by Gr3at** [comment]
It's been some time, but as I understand it, setting the `notMerge` prop and `deep cloning` the option object have the same effect.

Essentially, based on the docs *ikikika* shared, if `notMerge` is `true` the echarts will not try to merge (diff) with the previous option object. As a result the graph is recreated.

On the other hand, `deep cloning` creates a full copy of the object (**with a different object reference**) and thus echarts interprets it as a whole new option config.

> Note: My own thought. Might not map to what's really happening.
