### ISSUE TITLE
IE11不能正常显示

### ISSUE THREAD

**Issue by xueguozhongli** [hustcc/echarts-for-react#204]
http://git.hust.cc/echarts-for-react/
在IE11中打开上述链接，显示白板（如下图）。切换到IE10，可以正常显示。请问是什么问题？

![image](https://user-images.githubusercontent.com/22338719/41710703-e6efdc60-7578-11e8-9cc4-0b604a37530e.png)

**Comment by hustcc** [comment]
可以看下控制台报错吗？截图出来！

**Comment by xueguozhongli** [comment]
控制台没有报错。浏览器缩小后，发现图标在白板的后面！
![image](https://user-images.githubusercontent.com/22338719/41712718-d04481b4-757d-11e8-899f-d252753c4151.png)

**Comment by hustcc** [comment]
那你看看能不能修复，提个 pr。

**Comment by xueguozhongli** [comment]
chrome和IE11的html的div结构都不太一样，IE11未找到白板部分对应html。
因项目中遇到同样问题，烦请大神有时间看下，谢谢~~

**Comment by hustcc** [comment]
@xueguozhongli 大概找到原因呢，今天修复！

**Comment by hustcc** [comment]
fixed v2.0.13!

**Comment by xueguozhongli** [comment]
厉害，点个赞！

**Comment by xueguozhongli** [comment]
示例中的显示确实已正常。
但我正在做的项目中，"echarts-for-react": "^2.0.13"；"echarts": "^4.1.0"，这两项均已升级后，白板问题依然存在，请问可能是什么原因导致的呢？控制台无报错

**Comment by hustcc** [comment]
可以看到白板区域的 dom 结构吗？

**Comment by xueguozhongli** [comment]
这是chrome中正常显示的DOM结构。IE11中白板区域的DOM无法选中，未找到
![Uploading image.png…]()

**Comment by xueguozhongli** [comment]
谢谢，项目不是很急。使用 2.0.11 版本，未解决问题
经过对比，在Chrome和IE11下，DOM结构不太一样：

Chrome下的结构：
![image](https://user-images.githubusercontent.com/22338719/41773576-13148968-764f-11e8-9e9d-e8ef9b0bc8c8.png)

IE11下的结构：
![image](https://user-images.githubusercontent.com/22338719/41773587-1cc15b9e-764f-11e8-8323-ff76432be021.png)

amap-layers的div下，amap-markers中是多个饼图，**amap-layer在Chrome中是canvas，在IE11中为div**，这个可能是什么原因导致的？

**Comment by hustcc** [comment]
可能是 echarts 自己的渲染逻辑问题了，echarts 官方地图的 示例 是好的吗？

**Comment by xueguozhongli** [comment]
echarts官方Map示例，IE11中没发现这种问题。
只有一个示例是其他错误，示例http://echarts.baidu.com/examples/editor.html?c=lines-ny
![image](https://user-images.githubusercontent.com/22338719/41806522-484d96bc-76f2-11e8-825b-2262d47e359d.png)
我再试下其他echarts版本，看能不能解决这个问题

**Comment by tianzhiqi** [comment]
@xueguozhongli 你好，IE11不能正常显示的问题解决了吗
