### ISSUE TITLE
uncaught typeerror : cannot read property 'requestAnimationFrame' of undefined

### ISSUE THREAD

**Issue by oujiaru** [hustcc/echarts-for-react#206]
你好！ 我的项目上运行出现该错误
uncaught typeerror : cannot read property 'requestAnimationFrame' of undefined
是因为兼容性问题吗？
请教一下 谢谢
`import React, {Component} from 'react';

import ChartsToggle from '../public/chartsToggle/chartsToggle';
import BorderAngle from '../public/borderAngle/borderAngle';
import moment from 'moment';
import {hashHistory} from 'react-router';
import PieRightBar from './peopleRightBar/pieRightBar';
import ReactEcharts from 'echarts-for-react';
        
class PeoplePieCharts extends React.Component{
	
    constructor(props) {
        super(props);

        this.state={
            optionData:{},
            inputData:{
                dateRange1:moment().subtract(2,'year').format('YYYY')+'-12-26 - '+moment().subtract(1,'year').format('YYYY-MM-DD'),
                dateRange2:moment().subtract(1,'year').format('YYYY')+'-12-26 - '+moment().format('YYYY-MM-DD'),
                personType:'0',
                seriousZones:''
            },
            pubObj:{}
        }
        
    }
    getPieData=(data,obj)=>{
        this.setState({
            optionData:data,
            inputData:obj
        })
    }
    componentWillMount=()=>{
        
        loadCompareZoneData(this.state.inputData,(data)=>{
            let getData = data.data
            this.getPieData(getData,this.state.inputData)
        })
    }
    
    getOption1=(pieViewData,inputData)=> {
        let pieNum1 = 0
        let pieTime1 = 0
        let tmp_pie1_arr=[]
        let pie1_arr=pieViewData
        return {

            title:{
                text:'人员:'+inputData.dateRange1,
                subtext:'总人数：'+pieNum1+'总人次: '+pieTime1,
                textStyle:{
                    width:'200px',
                    height:'50px',
                    marginLeft:'2%',
                    marginTop:'1%',
                    color:'#fff',
                },
                subtextStyle:{
                  
                    color:'#fff',
                }             
            },

            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            series:[
                {
                    name:'各地区占比',
                    type:'pie',
                    radius : ['0.1', '60%'],
                    center:['45%','60%'],
                    label:{
                        normal:{
                            color:'#fff',//00BFE7
                            fontSize:'16px',
                            trigger: 'item',
                            formatter: "{b}\n{d}%"
                        }
                    },
                    labelLine:{
                        normal:{
                            lenght:20,
                            lenght2:40,
                            lineStyle:{
                                color:'#00BFE7'
                            }
                        }
                    },
                    data: pie1_arr,
                }
                
            ],
            color:['#00B4ED','#F0B4ED','#5D42FA','#26ABEF','#4075FF','#98DCFF','#2AB7FF','#C67839','#1AD570','#0807DB','#F0AF22'].reverse()

        } 
    }
    }
    render() {
        return (
            <div className="clearfix">
                <ChartsToggle ref="change1" people={true} />
                <div style={{width:'50%',float:'left'}}>
                    <ReactEcharts
                    option={this.getOption1(this.state.optionData,this.state.inputData)} 
                    noMerge={true}
                    lazyUpdate={false} theme={"peoplePie1"}
                    
                    style={{height:window.innerHeight-152+'px',width:'100%'}}
                    ref={(e)=>{this.peoPie1 = e}}
                    />
                </div>
                <PieRightBar style={{height:window.innerHeight-59+'px'}} getPieFun={this.getPieData} area={false} ref="right"/>
            </div>
        )
    }
}
export default PeoplePieCharts`

**Comment by hustcc** [comment]
你使用的 echarts-for-react 版本是多少？升级到最新版本可以解决吗？
