### ISSUE TITLE
Prevent it setting a height of 300px

### ISSUE THREAD

**Issue by damiangreen** [hustcc/echarts-for-react#208]
I have the component styled with flex:
```
  .widgetContainer > div {
  display: flex;
  flex: 1 1 auto;
  justify-content: center;
}

````

But it kepes getting a height of 300px which causes it to jump outside of my container.
I tried setting a height of 100% and a height of 0% to no effect.
My component is inside a resizable panel.

Example below:
[
![overlap](https://user-images.githubusercontent.com/1592820/42893797-39f74e0e-8aad-11e8-8a25-180a4211f8aa.JPG)
](url)

**Comment by SidKwok** [comment]
you need to invoke ‘chartInstance.resize()’ when you resize your panel

**Comment by damiangreen** [comment]
actually I solved it like this:


```
  <div className={s.widgetContainer}>
          {EchartsReact &&
            this.props.option && (
              <EchartsReact
                option={option}
                style={{
                  height: '100%',
                  width: '100%',
                }}
              />
            )}
          {children}
        </div>
```

.widgetContainer.css:

```
.widgetContainer {
  padding: 9px;
  flex-grow: 1;
  display: flex;
  align-items: center;
  height: 100%;
}
```

**Comment by hustcc** [comment]
👍
