### ISSUE TITLE
动态启用和关闭多Y轴的问题

### ISSUE THREAD

**Issue by jolinlizhihua** [hustcc/echarts-for-react#209]
问题描述：需要动态启用多Y轴的功功能，在点击启用多Y轴按钮后会根据图形的数量来显示多Y轴（此时显示正常），当点击关闭多Y轴按钮时显示错误，多Y轴并没有消失（正常的情况是多Y轴消失）。如下图1所示：当点击关闭多Y轴时红色的Y轴应该消失，可是并没有消失（此时当点击关闭多Y轴按钮时，已经修改了yAxis属性）
![pic1](https://user-images.githubusercontent.com/30651709/43055694-ab558c26-8e6a-11e8-9eac-3226eea1e625.PNG)

**Comment by hustcc** [comment]
notMerge 属性设置为 true 试试。

**Comment by jolinlizhihua** [comment]
我试了一下 虽然可以成功，但是影响了其他的显示效果

**Comment by hustcc** [comment]
这个是 echarts 提供的能力，原理告诉你了，具体要怎么处理，你可以自己按照需求处理。

**Comment by jolinlizhihua** [comment]
谢谢了
