### ISSUE TITLE
动图中tooltip显示问题

### ISSUE THREAD

**Issue by jolinlizhihua** [hustcc/echarts-for-react#210]
问题描述：我用echarts做了一个动图，现在当鼠标固定在图片中某一个位置时，出现了该位置的数据信息的tooltip，现在想随着图不断运动的过程中tooltip的内容一直在变化而不是显示一下就立即消失（也就是说一直显示鼠标固定位置x坐标对应的y的信息值），如下图所示

![pic1](https://user-images.githubusercontent.com/30651709/43064068-7100b052-8e90-11e8-90b2-c29828a5c491.PNG)

**Comment by hustcc** [comment]
这个是 echarts 使用问题，可以查看 echarts 文档，或者到 echarts 项目上提 issue。
