### ISSUE TITLE
How do i import  stuff from eCharts when using this in isomorphic app?

### ISSUE THREAD

**Issue by damiangreen** [hustcc/echarts-for-react#212]
I'm using RSK and I think this line is causing me issues on page reload

`const dattoHorizontalGradient = new echarts.graphic.LinearGradient(...)`

I manged to get around window.document errors when using the main component by doing tihs:
`const EchartsReact =
  typeof document !== 'undefined' && require('echarts-for-react').default; // eslint-disable-line
`
...
```
  {EchartsReact &&
            this.props.option && (
              <EchartsReact
                option={option}
                style={{
                  height: '100%',
                  width: '100%',
                }}
              />
            )}
```

Is there another way of importing gradients I'm unaware of?

**Comment by hustcc** [comment]
Why you need to:

> const EchartsReact = typeof document !== 'undefined' && require('echarts-for-react').default;

Use it when ssr?

**Comment by damiangreen** [comment]
Do i load `LinearGradient` from `EchartsReact` also?
Can i only instantiate one of these objects in `ComponentDidMount` ?
