### ISSUE TITLE
componentDidMount 时调用resize方法 报错

### ISSUE THREAD

**Issue by Hongbo-Wang** [hustcc/echarts-for-react#213]
在项目中测试，当componentDidMount 时调用resize方法，出现如下报错

`Uncaught TypeError: Cannot read property 'get' of undefined
    at Scheduler.proto.getPipeline`

如果将npm包里

`if (_this.echartsElement) {
        (0, _sizeSensor.bind)(_this.echartsElement, function () {
          echartObj.resize();
        });
      }`

这段代码进行判断，当`componentDidMount`调用时，不进行`resize`，则不会报错
麻烦看下是怎么回事

**Comment by hustcc** [comment]
这个错误应该不影响 echarts 图形的渲染吧？

**Comment by Hongbo-Wang** [comment]
恩，不影响渲染，但是做了异常监控，不停地报错，想问下这个能修复下吗？

**Comment by hustcc** [comment]
你们使用 echarts 和 echarts-for-react 版本是多少？

**Comment by Hongbo-Wang** [comment]
echarts：4.1.0
echarts-for-react： 2.0.13

**Comment by hustcc** [comment]
这个应该是 echarts 的问题，就是在 echarts 渲染过程中，调研 resize，可能会导致出错。

我的做法只能是将 resize 的代码 try catch 一下，然后打印 warn。

console.warn 不会影响你们的上报吧？

**Comment by Hongbo-Wang** [comment]
可以，谢谢

**Comment by hustcc** [comment]
v2.0.14
