### ISSUE TITLE
will this include latest 4.1.0 version or next?

### ISSUE THREAD

**Issue by jiehu567** [hustcc/echarts-for-react#215]
We are using tree graph and do need zoom in/ out option, which is only available in the official website version, not npm (according to [#8823](https://github.com/apache/incubator-echarts/issues/8823) ).  Or if there's anyway I can just involve the official version into react wrapper?

**Comment by hustcc** [comment]
echarts version can be 4.x

v4.1.0 can be supportted.

**Comment by hustcc** [comment]
You can add echarts as external in webpack.config.js
