### ISSUE TITLE
Chart doesn't update after changing options

### ISSUE THREAD

**Issue by VictorChen** [hustcc/echarts-for-react#216]
Here's a simple reproducer:

https://codesandbox.io/s/v1y9560k8l

All it's doing is toggling on/off one of the series, but the chart doesn't re-render.

**Comment by VictorChen** [comment]
nvm seems like this is actually a bug with echarts: https://github.com/apache/incubator-echarts/issues/6202

**Comment by diogns** [comment]
I solved this for React and only set "notMerge" to true.

``
 <ReactECharts
                option={options}
                opts={{ renderer: 'svg' }}
                notMerge={true}
        />
``
