### ISSUE TITLE
Override dataZoom event 

### ISSUE THREAD

**Issue by MarcMagnin** [hustcc/echarts-for-react#219]
Hi,

Within a line chart with time as X axis, is there is any way to prevent the default datazoom to query new data for the selected time range rather than zooming in?

I'm currently using echarts._componentsViews[Object.keys(echarts._componentsViews)[0]]._features['dataZoom'].model.iconPaths.zoom.trigger('click'); to trigger the datazoom feature but it doesn't seems that I can get an handle on the event to prevent it's normal execution.

Many thanks!

**Comment by hustcc** [comment]
Your meaning is that you want to set default datazoom select range？

**Comment by MarcMagnin** [comment]
What I'm doing is a zoom like the one on this highcharts demo: https://www.highcharts.com/demo/line-time-series
But the difference is that I'm not actually zooming in, I'm requesting new data for the time range in the 'zoom' selection (as the resolution of the data can change based upon the time range, server side).
The problem with echarts is that I can't prevent the actual zoom of the current data (that I'll drop to show the new data) and then when setting the new series data it's not behaving right (weird state/zoom kinda disabled).
```
event.preventDefault()
event.stopPropagation()
``` 
doesn't seems to work so the trick that I've done is that just before querying new data I reset the zoom using `echarts._componentsViews[Object.keys(echarts._componentsViews)[0]]._features['dataZoom'].model.iconPaths.back.trigger('click')` but that's definitely hacky and can sometimes cause some `Animator.js:64 Uncaught TypeError: Cannot set property '0' of undefined at interpolateArray`

**Comment by hustcc** [comment]
I think you can write `data zoom` button  with html as you like, when `data zoom` was click or touched, then request new data and show them on echarts.
