### ISSUE TITLE
多个echarts组件是否支持联动功能,怎么实现？

### ISSUE THREAD

**Issue by wlc534** [hustcc/echarts-for-react#222]
希望组件间联动。有如图的效果
<img width="1068" alt="2018-09-13 10 41 05" src="https://user-images.githubusercontent.com/26006959/45464224-2f0e7000-b742-11e8-9d46-feef7925c97f.png">

**Comment by SidKwok** [comment]
echarts本身支持图表的联动，可以参考一下[例子](http://echarts.baidu.com/examples/editor.html?c=candlestick-brush)
