### ISSUE TITLE
Why  is not  support type of map?

### ISSUE THREAD

**Issue by zhaodagang** [hustcc/echarts-for-react#224]

**Comment by SidKwok** [comment]
你是指map图表吗，这是[支持](https://git.hust.cc/echarts-for-react/#/echarts/map?_k=h9gu4r)的啊

**Comment by zhaodagang** [comment]
import ReactEcharts from 'echarts-for-react';

error:     Map undefined not exists.

**Comment by zhaodagang** [comment]
series: [
        {
          name: '香港18区人口密度',
          type: 'map',

**Comment by SidKwok** [comment]
提供一下重现的环境、版本和代码

**Comment by SidKwok** [comment]
你是不是没有引入map组件:
```javascript
require('echarts/map/js/china.js'); 
```
看一下示例代码

**Comment by zhaodagang** [comment]
It is still wrong:    Map undefined not exists. You can download map file on http://echarts.baidu.com/download-map.html

**Comment by SidKwok** [comment]
不清楚你的环境、版本和代码，没有办法重现你的错误

**Comment by zhaodagang** [comment]
"echarts": "3.6.2",
    "echarts-china-cities-js": "^0.1.1",
    "echarts-for-react": "^2.0.14",

**Comment by SidKwok** [comment]
你应该引入[这里](https://github.com/apache/incubator-echarts/tree/master/map/js)的文件，你引入map组件的相关代码看看

**Comment by zhaodagang** [comment]
还是不行呀，你写下引入代码 可以吗？

**Comment by zhaodagang** [comment]
代码是这样的：
import ReactEcharts from 'echarts-for-react';
import from 'echarts/map/json/china.json';

 series: [
        {
          name: '香港18区人口密度',
          type: 'map',
          mapType: 'HK', // 自定义扩展图表类型
          itemStyle:{
            normal:{label:{show:true}},
            emphasis:{label:{show:true}}
          },

**Comment by zhaodagang** [comment]
is it not support "heatMap" ?

**Comment by hustcc** [comment]
echarts 支持就是支持的！
