### ISSUE TITLE
阅读源码的疑惑

### ISSUE THREAD

**Issue by FourEyebrowXiake** [hustcc/echarts-for-react#230]
![image](https://user-images.githubusercontent.com/18180417/46130172-2d2ccc80-c26b-11e8-9c8c-1cc0f1844b91.png)
![image](https://user-images.githubusercontent.com/18180417/46130177-3027bd00-c26b-11e8-8ab8-6e38fa93b09e.png)

我看你在EchartsReact的constructor里执行了：
`this.echartsLib = echarts;`
这就是覆盖了EchartsReactCore的constructor里的：
`this.echartsLib = props.echarts; // the echarts object.`
还能实现按需加载echarts吗？

**Comment by SidKwok** [comment]
这个主要用于[按需引入](https://github.com/hustcc/echarts-for-react#typescript)的，默认使用echarts整体的包，用户也可以引入echarts的核心包，然后按需引入其他模块。

**Comment by FourEyebrowXiake** [comment]
@SidKwok 但是EchartsReact的构造函数里有重新赋值了this.echartsLib,这不就覆盖了props.echarts

**Comment by SidKwok** [comment]
就是要覆盖啊，因为默认的是引入echarts整体的包

**Comment by SidKwok** [comment]
`index.js`里使用的是默认的echarts，`core.jsx`中使用的是用户提供的`echarts`

**Comment by FourEyebrowXiake** [comment]
覆盖了，那还怎么按需引入

**Comment by SidKwok** [comment]
你得用`core.jsx`里面的东西才能按需引入。
```javascript
// 整体引入
import ReactEcharts from "echarts-for-react";
// 按需引入
import ReactEchartsCore from 'echarts-for-react/lib/core';
```
我觉得在`index.js`中写成这样子可能你会好理解一丢丢：
```javascript
import echarts from 'echarts';
import EchartsReactCore from './core';

// export the Component the echarts Object.
export default class EchartsReact extends EchartsReactCore {
  constructor(props) {
    super({...props, echarts});
    // this.echartsLib = echarts;
  }
}
```

**Comment by FourEyebrowXiake** [comment]
明白了，谢谢。

**Comment by SidKwok** [comment]
不谢
