### ISSUE TITLE
我这个最后有700kb，是不是哪里引入错了呢

### ISSUE THREAD

**Issue by Jason-story** [hustcc/echarts-for-react#231]
![image](https://user-images.githubusercontent.com/1809584/46140211-037f9f80-c283-11e8-8ad8-ffa04169413d.png)
![image](https://user-images.githubusercontent.com/1809584/46140226-109c8e80-c283-11e8-97c1-637757133435.png)

**Comment by SidKwok** [comment]
你引入的那部分代码是什么？

**Comment by Jason-story** [comment]
![image](https://user-images.githubusercontent.com/1809584/46141302-23649280-c286-11e8-92da-469de1902873.png)

**Comment by SidKwok** [comment]
改成`echarts-for-react/lib/core`试试，看看[文档](https://github.com/hustcc/echarts-for-react#typescript)

**Comment by Jason-story** [comment]
恩试了，可以了，还有个问题，就是我循环创建了4个图表，数据都不一样，可是图表展现却一样，怎么解决呢，多谢了

**Comment by SidKwok** [comment]
看看相关代码

**Comment by Jason-story** [comment]
![image](https://user-images.githubusercontent.com/1809584/46142152-91aa5480-c288-11e8-815b-86353695d3ce.png)
这个是图表组件的代码

**Comment by SidKwok** [comment]
循环那部分呢？

**Comment by Jason-story** [comment]
![image](https://user-images.githubusercontent.com/1809584/46142688-590b7a80-c28a-11e8-8caa-7b7ca5aeac1c.png)
现在是写了4个，其实里面都是一样的。。。
是在render里map时调用的

**Comment by SidKwok** [comment]
> 循环创建了4个图表，数据都不一样，可是图表展现却一样
> 现在是写了4个，其实里面都是一样的

没搞懂你在说什么啊

**Comment by Jason-story** [comment]
额 好吧 我再试试吧

**Comment by Jason-story** [comment]
多谢了
