### ISSUE TITLE
Pass props to dynamic chart

### ISSUE THREAD

**Issue by mangione77** [hustcc/echarts-for-react#234]
Hello, I am facing the following issue.

When trying to implement a dynamic chart while passing the values from a parent component, I can't access _this_ on the anonymous function (obviously), so we must pass it to getOptions function, which causes a lot of issues. 

Last one I encountered was the following:

![image](https://user-images.githubusercontent.com/29716602/46825211-613bdd80-cd93-11e8-816b-28e5ed2e5082.png)

The code causing the issue is the following:

- I'm passing the data through a socket connection to my frontend client
` 
render() {
        return (
            <div>
                <DynamicChart
                    sentimentValues={this.state.sentimentValues}
                />
            </div>
        )
    }
`
sentimentValues is an array which is being continuously updated by the socket connection.

My getOptions function:

`

    getOptions = (props) => {
        return {
            title: {
                text: 'dynamichart',
                x: 'center'
            },
            tooltip: {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left',
                data: [0, 50, 100]
            },
            series: [
                {
                    name: 'Live Tweets',
                    type: 'line',
                    data:(function (){
                        return props.sentimentValues
                      })()
                    ,
                    itemStyle: {
                        emphasis: {
                            shadowBlur: 10,
                            shadowOffsetX: 0,
                            shadowColor: 'rgba(0, 0, 0, 0.5)'
                        }
                    }
                }
            ]
        }
    }
`

render function (DynamicChart):

`
    render() {
        console.log(this.props.sentimentValues)
        return (
            <div>
                <ReachEcharts
                    option={this.getOptions(this.props)}
                    style={{ height: '400px', width: '100%' }}
                    opts={{ renderer: 'svg' }}
                    className='react_for_echarts'
                />
            </div>
        )
    }
`

Thanks for your work on echarts for react, it's been really useful.

**Comment by SidKwok** [comment]
Close for now.
Feel free to reopen the issue with code snippet for your issue.
