### ISSUE TITLE
fast-deep-equal不是深度比较

### ISSUE THREAD

**Issue by logic1013** [hustcc/echarts-for-react#235]
用{...option}拷贝进行修改以后，再this.setState({option: option})并不能触发重新渲染，因为fast-deep-equal比较的结果为true，感觉是个很深的坑，这个能解决一下吗？需要主动调用rerender感觉很无奈。
`this.state.option.series[0].data = data;

    data.forEach((item, index) => {

      this.state.option.legend.data[index] = item.name;

    });

    this.setState({ option: this.state.option }, () => {

      this.echarts_react.rerender();

    });`

**Comment by hustcc** [comment]
8102 年了，修改 object 使用 immutable 的方法吧😄

**Comment by logic1013** [comment]
@hustcc immutable倒是可以，但是没必要为了一个东西引入一个这个呀，，代价太大了= =

**Comment by logic1013** [comment]
@SidKwok 深拷贝的话option里面的function就没有了。。

**Comment by hustcc** [comment]
immutable-helper 1kb 左右。

或者直接使用 array.concat 等等。

**Comment by SidKwok** [comment]
你这种情况只能用`immutable`，或者`deep-clone`一份`option`出来再赋值再修改再`setState`，[官方不建议直接修改`state`](https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly)，原因看上一条comment。

**Comment by logic1013** [comment]
@hustcc 我引入一下immutable试试吧，多谢！

**Comment by logic1013** [comment]
@SidKwok 多谢建议，我试一下吧！
