### ISSUE TITLE
IE11中报错：Unhandled promise rejection Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render ...

### ISSUE THREAD

**Issue by zhaiqiang1987** [hustcc/echarts-for-react#236]
React Dva引入该图表，chrome浏览器没任何问题，Ie11中报错：
Unhandled promise rejection Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
 in EchartsReact (created by SbbtgjPanel)

百度说是在index.js中加入
import 'react-dom';
import '@babel/polyfill';
未起作用

改用bizcharts也是一样的问题。
求指点

**Comment by SidKwok** [comment]
参考一下[这里](https://github.com/kriasoft/react-starter-kit/issues/1098#issuecomment-283276346)

**Comment by zhaiqiang1987** [comment]
.webpackrc改为js格式
.webpackrc.js
export default {
  entry: {
    server: ['babel-polyfill', './src/index.js'],
  },
......
问题解决
