### ISSUE TITLE
两个独立的Simple demo能不能不要设置成堆叠效果

### ISSUE THREAD

**Issue by tuihou123321** [hustcc/echarts-for-react#238]
两个独立的Simple demo能不能不要设置成堆叠效果，左边垂直坐标和实际数字都对不上了

**Comment by omitchen** [comment]
![image](https://user-images.githubusercontent.com/23668478/62098731-28d3a480-b2be-11e9-8b89-8794e4291d86.png)
是的,simple demo 的表达有问题
