### ISSUE TITLE
div大小发生改变时怎么让图表自适应

### ISSUE THREAD

**Issue by 532269148** [hustcc/echarts-for-react#239]
拖动改变div大小后横轴会随着一块改变但是竖直方向大小没有变化，查询资料后说原生echarts有个resize功能可以实现，请问这个组件支持resize吗？怎么实现？

**Comment by hustcc** [comment]
已经做了这个了。

因为你的 div 高度没有变化，所以，垂直上不会有变化！

**Comment by 532269148** [comment]
我通过拖拽改变了div的大小，宽度可以自适应，但是高度不行，设置成饼图圆心竖直方向上也不会有变化。我是设了一个可以改变大小的div，内部设置了一个宽和高都是100%的新div，然后渲染到内部的div上，会有影响吗？

**Comment by 532269148** [comment]
> 已经做了这个了。
> 
> 因为你的 div 高度没有变化，所以，垂直上不会有变化！

core.jsx里render有这么一行：
const newStyle = {
      height: 300,
      ...style,
    };
这是无法改变高度的原因吗？我尝试了一下怎么变图表高度都是300px

**Comment by hustcc** [comment]
在 属性中设置 style 的 height 就可以覆盖这个属性了啊！

**Comment by 31526** [comment]
同样的问题，怎么设置图表都是300px高，这个问题还没有修复？！

**Comment by SidKwok** [comment]
@31526 [看style那里](https://github.com/hustcc/echarts-for-react#3-component-props)，这个高度是可以自己修改的
