### ISSUE TITLE
How do i use bmap?

### ISSUE THREAD

**Issue by harunkelesoglu** [hustcc/echarts-for-react#240]
I am trying use bmap instead of geo.But map not showing for this [demo](https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-map-brush) .I am importing just echarts library in this way ->
`import ReactEcharts from 'echarts-for-react';`

how can i solve this problem.

**Comment by SidKwok** [comment]
Did you add `bmap.js` in your code base?

**Comment by harunkelesoglu** [comment]
Thanks @SidKwok i solved. If you still dont solve it. You can try @jerryyan1990 
`import ReactEcharts from 'echarts-for-react';
require('echarts/extension/bmap/bmap')`

Additional you should add to index.html header
` <script src="https://api.map.baidu.com/getscript?v=2.0&ak=yourApiKey"></script>`

But this time the map is loading slowly. How can i speed up? Is there someone who knows?

**Comment by SidKwok** [comment]
> <script src="https://api.map.baidu.com/getscript?v=2.0&ak=yourApiKey"></script>

Did you mean the script loading time or just the paint time of charts?

**Comment by harunkelesoglu** [comment]
i mean script loading

**Comment by SidKwok** [comment]
the servers should be deployed in China, and it may the cause network issue. I think it would be much better if you download the script and store it in your local environment. Or you can just `require` with webpack.
