### ISSUE TITLE
getOption()功能与setOption()效果不同？

### ISSUE THREAD

**Issue by chairy11** [hustcc/echarts-for-react#242]
Hi, 我在使用echarts-for-react中的force graph 关系图，我需要动态变更节点、颜色、大小。
如果我使用`this.echarts_react.getEchartsInstance().setOption(newOption);`，过渡将非常平滑，而如果是getOption得到的config变化，则会重新渲染整个图，动来动去，体验非常不好。

![image](https://user-images.githubusercontent.com/1669457/48339753-e15fa680-e6a3-11e8-9731-62a57c05e1e5.png)

但我又因为其它的原因，非要用getOption来更新。有没有办法去优化这个问题？使getGraphOption()与setOption一样？

**Comment by hustcc** [comment]
例如主题变化，宽高变化会导致重绘。

因为什么原因必须使用 gitOption？

**Comment by chairy11** [comment]
@hustcc 
我的页面比较复杂，要从关系图中的节点类型、边的类型、颜色选用的变量、大小选用的变量、点的名称过滤（需要发请求）等多个角度去动态设置这个图。还有依赖于节点数据的表格。
另如果你用过neo4j，来开发知识图谱，会知道这些都是必须的。但echart只支持颜色映射，所以我需要通过改节点里的value啊、edges、tooltip啊，各种动态变量。
getOption中用到了些类似state或是reducer里的state的变量，有时我的确需要改变某些state的值，所以如果是通过state变量导致getOption变化，从而更新图形，本来是最方便的。
如果纯用setOption，state改变了，它同样触发getOption重绘，很不方便。

**Comment by chairy11** [comment]
@hustcc 我知道解决方法了，之前没留意到加进了「 notMerge」属性，现在去掉这个就好了。
