### ISSUE TITLE
'getEchartsInstance' does not exist on type 'ReactEcharts'.

### ISSUE THREAD

**Issue by wangqianwen0418** [hustcc/echarts-for-react#244]
Property 'getEchartsInstance' does not exist on type 'ReactEcharts'.

"echarts": "^4.1.0",
"echarts-for-react": "^2.0.14",
"typescript": "^3.1.5"

**Comment by hustcc** [comment]
是 ts 报错吧？ignore 掉可以执行吗？

**Comment by wangqianwen0418** [comment]
对，是ts报错，我把ref的类型设置成any可以运行
