### ISSUE TITLE
cann't auto download the latest rc  version of echarts

### ISSUE THREAD

**Issue by AllanSmithX** [hustcc/echarts-for-react#246]
now  the latest version of echarts is  "4.2.0-rc.2",my echarts-for-react is 2.0.14,only can get the "4.1.0" version of echarts，how to modify the file “package.json” can get a better result ?

**Comment by SidKwok** [comment]
Simply modify your `echarts` version field in `package.json` can do the job.

**Comment by AllanSmithX** [comment]
@SidKwok  我知道直接修改相应字段就行，但目前我们项目中没把react-for-echarts 的 package.json 文件加入到git版本控制中，还有很多组件的 package.json 也都没加入到 git版本控制中，所以希望 react-for-echarts里的package.json 是直接能拿过来用那种，不知可否处理一下子呢？

**Comment by SidKwok** [comment]
`echarts-for-react`使用的是peer dependency的，所以你再你的package.json里面写echarts的版本就好，没必要修改这个库里面的package.json

**Comment by AllanSmithX** [comment]
奥
