### ISSUE TITLE
svg渲染模式下热力图（heatmap）报错

### ISSUE THREAD

**Issue by patire-tu** [hustcc/echarts-for-react#248]
![default](https://user-images.githubusercontent.com/21333109/49213206-afb64180-f3fe-11e8-9402-ddb108e34f82.png)
![default](https://user-images.githubusercontent.com/21333109/49213214-b3e25f00-f3fe-11e8-8301-1d1cf6ca0599.png)
如标题，热力图在svg模式下渲染不出来，canvas模式下是没有问题的

**Comment by sunnyabc789** [comment]
水球图也遇到了同样的问题,一模一样的报错

**Comment by sunnyabc789** [comment]
echarts-liquidfill has same question and same error

**Comment by sunnyabc789** [comment]
I though it will be helpful to this bug
ecomfe/zrender/issues/358
