### ISSUE TITLE
Blank canvas after rendering

### ISSUE THREAD

**Issue by rajvengala** [hustcc/echarts-for-react#250]
Hi,

I'm seeing blank canvas after following instructions in the readme. 

`
"dependencies": 
    "antd": "^3.10.4",
    "echarts": "^3.8.5",
    "echarts-for-react": "^2.0.14",
`
I have tried with latest version of echarts, I still have the same issue.

<img width="921" alt="screenshot 2018-12-21 at 18 59 57" src="https://user-images.githubusercontent.com/158846/50344819-aa0dd080-0552-11e9-9334-6de2043147a3.png">

**Comment by hustcc** [comment]
what is your option？

**Comment by rajvengala** [comment]
Here is one (taken from echarts example). I have tried other options too.
`
const option = {
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [{
    data: [820, 932, 901, 934, 1290, 1330, 1320],
    type: 'line',
    areaStyle: {}
  }]
};
`

**Comment by rajvengala** [comment]
I'm able to reproduce this, using pure React.

https://codesandbox.io/s/pmpkvk155q

**Comment by rajvengala** [comment]
Parent of the target div is ,issing height and width. Works fine now.
