### ISSUE TITLE
ref callback 在componentdidmount 之后执行吗？

### ISSUE THREAD

**Issue by lifeneedspassion** [hustcc/echarts-for-react#251]
componentDidMount() {
     this.echarts_react // undefined
}

render:
<ReactEcharts
              ref={inst => { this.echarts_react = inst }}
              option={this.getOption()}
            />

**Comment by hustcc** [comment]
是的…

**Comment by lifeneedspassion** [comment]
请教一下哈，我页面有多个图表，我怎么一次拿到所有echarts图表的实例呢？

**Comment by lifeneedspassion** [comment]
围观了楼主的代码：），用onChartReady，不要用ref，ref callback是在componentDidUpdate之后执行的，想拿到echarts实例还是要在 componentDidUpdate 里拿，不能在componentDidMount里。
