### ISSUE TITLE
onEvents传入外部函数方法导致组件重绘

### ISSUE THREAD

**Issue by SophieFUofficial** [hustcc/echarts-for-react#257]
我是将ReactEcharts封装成一个组件，用在业务代码中，其中onEvents={onEvents}。
我将const onEvents = {
      click: this.props.pieClick,
    };
在外部组件中希望通过pieClick来获取点击的Echarts的值，确实可以做到，但此时所有用到pieClick的组件都会闪烁（重绘了），不知是什么原因。

**Comment by hustcc** [comment]
方法挂到类上，保证引用同一个。

**Comment by SophieFUofficial** [comment]
问题解决了，谢谢大佬。还是自己经验太少了~
