### ISSUE TITLE
zoom in icon

### ISSUE THREAD

**Issue by KristinaMatuleviciute** [hustcc/echarts-for-react#258]
When trying to add English description to zoom in/out icons its not working, the same Chinese is under the icons :
toolbox: {
       feature: {
         dataZoom : {
           title :'zoom',
           show: true,
           title : {
            dataZoom : 'zoom in',
            dataZoomReset : 'zoom out'
        }

**Comment by ffarella** [comment]
try this!

```
addWebpackAlias({
      echarts$: "echarts/dist/echarts-en.min",
      echarts: "echarts/dist",
    }),
```

(I use antd so I have to do this with react-app-rewired)
