### ISSUE TITLE
How do I use `setOption`?

### ISSUE THREAD

**Issue by ashpreetbedi** [hustcc/echarts-for-react#261]
I tried reading through some issues, [this](https://github.com/hustcc/echarts-for-react/issues/242) and [this](https://github.com/hustcc/echarts-for-react/issues/244) but unfortunately I can't understand Chinese (really sorry about that).

How would I use `setOption()` in the react component?
I'd like to render charts based on specific props.

Eg:
```
props = {
  chartType: 'line'
}
```
then i want to render
```
...
series: [
  {
    type: 'line'
    ...
  }
]
```

----

if 

```
props = {
  chartType: 'candlestick'
}
```
then i want to render
```
...
series: [
  {
    type: 'candlestick'
    ...
  }
]
```

Thanks in advance!

**Comment by SidKwok** [comment]
have you tried getEchartsInstance.setOption?

**Comment by ashpreetbedi** [comment]
Got it, sorry I missed the `getEchartsInstance` part. Thank you @SidKwok

**Comment by TylerGriffin99** [comment]
@ashpreetbedi can you please elaborate on how you did this in react? Perhaps with some code examples? Whenever i try this is getEchartsInstance seems to be null or undefined

**Comment by sunpar** [comment]
> @ashpreetbedi can you please elaborate on how you did this in react? Perhaps with some code examples? Whenever i try this is getEchartsInstance seems to be null or undefined

In case anyone comes to this thread and has this question doing something like this works for me:

```
const eChartsRef = React.useRef(null as any);
...
if (eChartsRef && eChartsRef.current)
      eChartsRef.current?.getEchartsInstance().setOption(options);
...
<ReactEcharts
          option={options}
          style={{ height: 600 }}
          ref={eChartsRef}
        />
```

**Comment by SaranVad-1996** [comment]
> > @ashpreetbedi can you please elaborate on how you did this in react? Perhaps with some code examples? Whenever i try this is getEchartsInstance seems to be null or undefined
> 
> In case anyone comes to this thread and has this question doing something like this works for me:
> 
> ```
> const eChartsRef = React.useRef(null as any);
> ...
> if (eChartsRef && eChartsRef.current)
>       eChartsRef.current?.getEchartsInstance().setOption(options);
> ...
> <ReactEcharts
>           option={options}
>           style={{ height: 600 }}
>           ref={eChartsRef}
>         />
> ```

For if (eChartsRef && eChartsRef.current)
      eChartsRef.current?.getEchartsInstance().setOption(options); ",

I am getting "Expected an assignment or function call and instead saw an expression".

**Comment by sunpar** [comment]
> Expected an assignment or function call and instead saw an expression

That's a linting error, @SaranVad-1996 

You can try to use brackets to see if that's the issue, like so: 

```
const eChartsRef = React.useRef(null as any);
...
if (eChartsRef && eChartsRef.current) {
      eChartsRef.current?.getEchartsInstance().setOption(options);
}
...
<ReactEcharts
          option={options}
          style={{ height: 600 }}
          ref={eChartsRef}
        />
```

**Comment by SaranVad-1996** [comment]
> > Expected an assignment or function call and instead saw an expression
> 
> That's a linting error, @SaranVad-1996
> 
> Set Option is a function though, so it shouldn't complain about that. You can try to use brackets to see if that's the issue, like so:
> 
> ```
> const eChartsRef = React.useRef(null as any);
> ...
> if (eChartsRef && eChartsRef.current) {
>       eChartsRef.current?.getEchartsInstance().setOption(options);
> }
> ...
> <ReactEcharts
>           option={options}
>           style={{ height: 600 }}
>           ref={eChartsRef}
>         />
> ```

Do you know where you're getting getEchartsInstance() from? How does it come from eChartsRef.current?

**Comment by sunpar** [comment]
> > > Expected an assignment or function call and instead saw an expression
> > 
> > 
> > That's a linting error, @SaranVad-1996
> > Set Option is a function though, so it shouldn't complain about that. You can try to use brackets to see if that's the issue, like so:
> > ```
> > const eChartsRef = React.useRef(null as any);
> > ...
> > if (eChartsRef && eChartsRef.current) {
> >       eChartsRef.current?.getEchartsInstance().setOption(options);
> > }
> > ...
> > <ReactEcharts
> >           option={options}
> >           style={{ height: 600 }}
> >           ref={eChartsRef}
> >         />
> > ```
> 
> Do you know where you're getting getEchartsInstance() from? How does it come from eChartsRef.current?

See the React.useRef and how eChartsRef is assigned to the ref property of ReactECharts component.
