### ISSUE TITLE
getOption() usage

### ISSUE THREAD

**Issue by shalmalijain** [hustcc/echarts-for-react#265]
How to use getOption()? Nowhere in the document is it mentioned. What is this.getOptions()

**Comment by CitiVince** [comment]
Just getting started, but from what I understand, it's just a function you need to add to your react component that returns an option object. 

```javascript
class Chart extends React.Component {
  constructor(props){
    ...
  }

  getOption(){
   
    const option = {
      title: { text: 'my chart title'},
      dataset: [...],
      ...
    }

     return option
  }

  render(){
     return (
         <ReactEcharts
            option={this.getOption()},
            ...
     )
  }
}
```

alternatively, you can just write static options instead.

**Comment by hustcc** [comment]
see echarts document.

**Comment by Awful-Leo** [comment]
thanks a lot
