### ISSUE TITLE
Some options of echarts are not supported?such as xAxis: {nameGap, nameTextStyle}

### ISSUE THREAD

**Issue by soybeanxiaobi** [hustcc/echarts-for-react#266]
### 问题描述
官方例子:https://echarts.baidu.com/examples/editor.html?c=line-stack
在上面例子上的`xAxis`属性里面新增下面属性.均不生效.项目里面也不生效.
```
nameGap: 100,
nameTextStyle: {
    color: '#f9b041'
}
```
难道`echarts-for-react`不支持echarts这些的options吗？

官方NPM介绍:
![clipboard.png](/img/bVboIK1)

谢谢！

**Comment by hustcc** [comment]
options 是直接透传的，所以只要 echarts 支持，这里就支持的，并且不会修改他的格式。

如果遇到问题，可能是 echarts 版本和文档对应不上。
