### ISSUE TITLE
Line graph don't have loading animation

### ISSUE THREAD

**Issue by daarxwalker** [hustcc/echarts-for-react#270]
Bar graph is ok, but when i use line, there is no animation when component mount, like draw line, you know. Am I missing something? I read API docs, there's no property like this need to set, looks like default.

My test option:
`{
	tooltip: {},
	xAxis: {
		type: 'category',
		boundaryGap: false,
		data: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
	},
	yAxis: {
		type: 'value'
	},
	series: [{
		data: [5, 20, 36, 10, 10, 20, 45],
		type: 'line',
		smooth: true,
		areaStyle: { color: color.primary, },
		color: color.primaryLight,
	}]
}`

My component use:
`
<ReactEcharts
  echarts={echarts}
  option={options}
  lazyUpdate={true}
  opts={{renderer: 'svg'}}
/>
`

**Comment by EvanPurkhiser** [comment]
I'm running into something similar. If I load the tab for the chart *without* the tab focused, and switch to it after it's loaded the animation seems to work.

**Comment by CrzMarvin** [comment]
Same Problem!

**Comment by hustcc** [comment]
It is echarts's issue, send it here: https://github.com/apache/incubator-echarts/issues
