### ISSUE TITLE
echarts组件测试失败TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by mpw0311** [hustcc/echarts-for-react#271]
能交流交流么，给指点指点
![image](https://user-images.githubusercontent.com/20100082/53791925-80672180-3f65-11e9-9a92-d194e8b7cb45.png)

![image](https://user-images.githubusercontent.com/20100082/53791995-a68cc180-3f65-11e9-9251-c4aa59bfab4d.png)

**Comment by sdytybdbaba** [comment]
简单点说就是，你要渲染echarts的元素还没有生成就执行了echarts代码，可是获取节点的时候就报错了，因为获取不到
