### ISSUE TITLE
饼图的highlight无效

### ISSUE THREAD

**Issue by glin7976** [hustcc/echarts-for-react#273]
highlight(echarts) {
        console.log('echarts:', echarts.dispatchAction);
        echarts.dispatchAction({type: 'highlight', seriesIndex: 0, dataIndex: 0});
    }

    // 182 , 321
    getOption() {
        let option = {
            color: ['rgba(255, 255, 255, 0.6)', 'rgba(8, 189, 134, 1)'],
            calculable: true,
            series: [
                // {
                //     name: '总数',
                //     type: 'pie',
                //     z: 1,
                //     clockwise: false,
                //     radius: [179, 187],
                //     center: ['50%', '50%'],
                //     hoverAnimation: false,
                //     labelLine: {
                //         show: false
                //     },
                //     itemStyle: {
                //         color: 'rgba(31, 31, 31, 1)'
                //     },
                //     label: {
                //         show: true,
                //         width: 297,
                //         height: 207,
                //         align: 'center',
                //         backgroundColor: {
                //             image: innerPieBg
                //         },
                //         padding: [80, 0, 0, 0],
                //         position: 'center',
                //         formatter: '{a|900}',
                //         rich: {
                //             a: {
                //                 color: 'rgba(94, 243, 255, 1)',
                //                 fontSize: 64
                //             }
                //         }
                //     },
                //     data: [900]
                // },
                {
                    name: '',
                    type: 'pie',
                    z: 2,
                    clockwise: false,
                    radius: [179, 187],
                    center: ['50%', '50%'],
                    label: {
                        formatter: (params) => {
                            return '{a|' + params.data.value + 'Sensors}\n {b|' + params.data.name + '}\n {c|' + params.data.enName + '}\n' + '{d|' + params.data.aver + params.data.unit + '}';
                        },
                        rich: {
                            a: {
                                color: 'rgba(94, 243, 255, 0.6)',
                                fontSize: 20,
                                lineHeight: 30
                            },
                            b: {
                                color: 'rgba(255, 255, 255, 0.9)',
                                fontSize: 20,
                                lineHeight: 20
                            },
                            c: {
                                color: 'rgba(162, 163, 176, 1)',
                                fontSize: 20,
                                lineHeight: 20
                            },
                            d: {
                                color: 'rgba(94, 243, 255, 1)',
                                fontSize: 36,
                                lineHeight: 36
                                // padding: [70, -120, 0, 0]
                            },
                            e: {
                                color: 'rgba(94, 243, 255, 1)',
                                fontSize: 24,
                                lineHeight: 24
                                // padding: [70, -80, 0, 0]
                            },
                            hr: {
                                borderColor: 'rgba(94, 243, 255, 0.8)',
                                width: '100%',
                                borderWidth: 1,
                                height: 0
                            }
                        },
                        padding: [0, -3, 30, 0]
                    },
                    labelLine: {
                        lineStyle: {
                            color: 'rgba(94, 243, 255, 0.8)'
                        },
                        length: 60,
                        length2: 100
                    },
                    data: [830, 70]
                }
            ]
        };
        return option;
    }

    render() {
        return (
            <div>
                <ReactEcharts
                    ref={(e) => { this.echarts_react = e; }}
                    option={this.getOption()}
                    style={{ height: '100%', width: '100%' }}
                    onChartReady={(echarts) => { this.highlight(echarts); }}
                />
            </div>
        );
    }

**Comment by hustcc** [comment]
echarts 的使用问题请到 https://github.com/apache/incubator-echarts/issues 提 issue。

**Comment by codinglilong** [comment]
大兄弟你这问题解决了吗？我今天也碰到了。一闪而过，就是不能固定住
