### ISSUE TITLE
Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by liuxuewen-site** [hustcc/echarts-for-react#276]
TypeError: Cannot read property 'count' of undefined                                                      core.js:77
    at Task.dataTaskProgress (Series.js:567)
    at doProgress (task.js:217)
    at Task.webpackJsonp../node_modules/echarts/lib/stream/task.js.taskProto.perform (task.js:157)
    at Scheduler.js:302
    at ExtendedClass.<anonymous> (Global.js:517)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.eachSeries (Global.js:514)
    at Scheduler.webpackJsonp../node_modules/echarts/lib/stream/Scheduler.js.proto.performSeriesTasks (Scheduler.js:300)
    at ECharts.update (echarts.js:767)

看了下报错的地方是echarts-for-react/lib/core.js里的console.warn(e);：
if (_this.echartsElement) {
        (0, _sizeSensor.bind)(_this.echartsElement, function () {
          try {
            echartObj.resize();
          } catch (e) {
            console.warn(e);
          }
        });
      }

version: echarts-for-react 2.0.15-beta.0

**Comment by andywwu** [comment]
切到2.0.14版本

**Comment by FishLuo1992** [comment]
切换到2.0.14版本并没有解决，请问一下你们的解决方法。

**Comment by seminelee** [comment]
same here

**Comment by hustcc** [comment]
echarts-for-react/lib/core.js 文件中并没有 用到 count 吧？请说下你的具体的 case

**Comment by hmzh2016** [comment]
![image](https://user-images.githubusercontent.com/17775613/62690650-a22a7000-b9ff-11e9-8a15-c89d68182e5e.png)

**Comment by hmzh2016** [comment]
Series.js:567 Uncaught TypeError: Cannot read property 'count' of undefined
    at Task.dataTaskProgress (Series.js:567)
    at doProgress (task.js:217)
    at Task.taskProto.perform (task.js:157)
    at Scheduler.js:302
    at ExtendedClass.<anonymous> (Global.js:517)
    at Array.forEach (<anonymous>)
    at each (util.js:298)
    at ExtendedClass.eachSeries (Global.js:514)
    at Scheduler.proto.performSeriesTasks (Scheduler.js:300)
    at ECharts.update (echarts.js:767)
    at ECharts.echartsProto.resize (echarts.js:991)
    at ECharts.resize (util.js:424)
    at core.js:74
    at Sensor.js:52
    at Array.forEach (<anonymous>)
    at Sensor.<anonymous> (Sensor.js:51)
    at debounce.js:27

**Comment by hmzh2016** [comment]
echarts@4.2.1：echarts/lib/model/Series.js里面的dataTaskProgress

**Comment by hmzh2016** [comment]
> echarts-for-react/lib/core.js 文件中并没有 用到 count 吧？请说下你的具体的 case

echarts@4.2.1：echarts/lib/model/Series.js里面的dataTaskProgress

**Comment by Li-Kuan** [comment]
function dataTaskProgress(param, context) {
  // Avoid repead cloneShallow when data just created in reset.
  if (param.end > context.outputData.count()) {
    context.model.getRawData().cloneShallow(context.outputData);
  }
} // TODO refactor

**Comment by howel52** [comment]
@Li-Kuan @liuxuewen-site  

有 codesandbox 等可复现的例子么?  我这边并没有复现这个 case， 但从错误栈上看是 echarts 的一个空指针 https://github.com/apache/incubator-echarts/pull/11718 导致的。

有稳定复现的 case 可提供下，可作为 echarts 的单测补充

**Comment by eazow** [comment]
similar issue

![image](https://user-images.githubusercontent.com/1249362/70328203-6ef3d280-1873-11ea-95a0-db2bd6dcacf4.png)
![image](https://user-images.githubusercontent.com/1249362/70328233-7d41ee80-1873-11ea-812b-46aef85ee271.png)

**Comment by Joycewu31400** [comment]
same problem

**Comment by zhoulijuanmiao** [comment]
same problem, how to fix it

**Comment by zoffyzhang** [comment]
same here

**Comment by Li-Kuan** [comment]
> @Li-Kuan @liuxuewen-site
> 
> 有 codesandbox 等可复现的例子么? 我这边并没有复现这个 case， 但从错误栈上看是 echarts 的一个空指针 [apache/incubator-echarts#11718](https://github.com/apache/incubator-echarts/pull/11718) 导致的。
> 
> 有稳定复现的 case 可提供下，可作为 echarts 的单测补充

我这里也不是必现的问题

**Comment by hustcc** [comment]
去[这里发 +1 ](https://github.com/apache/incubator-echarts/pull/11718)吧，echarts-for-react 仅仅是 react 组件包装，不感知 option 配置。

**Comment by 100pah** [comment]
@liuxuewen-site @zoffyzhang @zhoulijuanmiao @Joycewu31400 @eazow @Li-Kuan 

十分抱歉，仔细审查 echarts 代码却仍没有能够想到，出现这个错误可能的原因。
在出问题的代码行处：
https://github.com/apache/incubator-echarts/blob/4.2.1/src/model/Series.js#L582

虽然可以加空指针判断，但是按照逻辑，这个地方本身不应该出现空指针。
如果出现，那么可能意味着，其他地方的某个逻辑已经出现了错误。

如果大家谁有时间，
能摸索处稳定复现的方法，
亦或者提供更多的信息，如：
`notMerge` `lazyUpdate` 设置的是什么，传给 echarts 的 `option` 是什么样的，
会有助于缩小排查范围。

非常感谢 🙏
