### ISSUE TITLE
Double Click on legend item to filter for only that item

### ISSUE THREAD

**Issue by rustyb** [hustcc/echarts-for-react#278]
Hi There - looking for some advice on how to catch / add an event handler to track for a double click event on a legend item? 

Looking to implement the same functionality as NVD3charts where a double click on a legend item deselects all other legend items. (See for an example http://nvd3.org/examples/line.html)

Looking into the source it appears only a `click` event is emitted by the legend items. Any help would be greatly appreciated!

**Comment by hustcc** [comment]
It is echarts's issue, please send it to https://github.com/apache/incubator-echarts/issues
