### ISSUE TITLE
dva结合echarts-for-react

### ISSUE THREAD

**Issue by jasminecjc** [hustcc/echarts-for-react#28]
dva结合ant design的table组件：展示组件第一次获得初始state为null，table显示暂无数据，第二次获取到了model返回的ajax请求接口数据，数据填充
dva结合echarts-for-react：展示组件第一次获得初始state为null，ReactEcharts获取的数据为null直接报错没有进入数据填充阶段
解决方案：
```
{chart? <ReactEcharts
                    option={getOption(chart)}
                    style={{height: '400px'}} /> : 'test'}
```
这是我目前的解决方案，想问echarts-for-react现在是怎么处理数据还没就位的情况的

**Comment by hustcc** [comment]
```js
option: React.PropTypes.object.isRequired,
```

代码中 option 是必备参数，并且没有做任何处理。dav 我没有玩过，不过你可以这么处理：

```js
{chart? <ReactEcharts
                    option={getOption(chart) || {}}
                    style={{height: '400px'}} /> : 'test'}
```
组件库中做一些默认处理，感觉不太好，因为可能会影响组件使用的灵活性。

**Comment by tangzhirong** [comment]
nice

**Comment by hustcc** [comment]
@jasminecjc  如果可以帮助到你的话，就关闭 issue 吧 ^^~

**Comment by Molloh** [comment]
你好，我看了解决方案后还是不太明白，可不可以更具体地讲一下
