### ISSUE TITLE
选择了legend后，axis所选择的数据不更新

### ISSUE THREAD

**Issue by foxlisimulation** [hustcc/echarts-for-react#281]
本来选了5个指标展示5个折线，然后录取消了2个，正确情况应该是只展示3个数据：

代码结果是这样的：
legend实时更新了只剩3个
但是tooltip还是之前的5个
![image](https://user-images.githubusercontent.com/14816026/34139475-9d81cff4-e43a-11e7-9e9f-00e8de368555.png)

_Originally posted by @Aggie123 in https://github.com/hustcc/echarts-for-react/issues/126#issuecomment-352629890_

**Comment by foxlisimulation** [comment]
我也碰到了这个问题，但是之前的同学说的设置merge并没有找到，想问问怎么设置

**Comment by hustcc** [comment]
设置组件参数 notMerge = true
