### ISSUE TITLE
地图突然不显示了？！！

### ISSUE THREAD

**Issue by jerryyan1990** [hustcc/echarts-for-react#283]
业务需求需要一个地图上下钻之前这个功能做好了，功能正常，地图显示也正常。

今天突然被告知地图一直没显示。通过调试发现并没有任何报错存在。

使用```echarts.registerMap(name, res)```注册地图正常。

使用```echarts.getMap(mapName).geoJson.features```能正常获取已注册地图的信息。

就是地图不显示一片空白？有人遇到过同样的问题吗？求指导

**Comment by hustcc** [comment]
应该是 echarts 的问题，请到 echarts 的 issue 上提问题！
