### ISSUE TITLE
树图的symbol使用图片时，图片高度明度，看不清；直接使用echarts无此问题

### ISSUE THREAD

**Issue by alecthw** [hustcc/echarts-for-react#284]
尝试之后发现2.0.11以及之前版本无此问题，从2.0.12出现此问题。
比较结果参考codesandbox
https://codesandbox.io/embed/53560pvl14

**Comment by hustcc** [comment]
没有明白具体的问题是什么？

**Comment by alecthw** [comment]
codesandbox里写了两个比较，注意比较下使用echarts-for-react时和直接使用原生echart时，root节点的图片。
使用echarts-for-react时，root节点有透明度，看不清

**Comment by alecthw** [comment]
> 没有明白具体的问题是什么？

codesandbox里写了两个比较，注意比较下使用echarts-for-react时和直接使用原生echart时，root节点的图片。
使用echarts-for-react时，root节点有透明度，看不清

**Comment by alecthw** [comment]
> 没有明白具体的问题是什么？
再贴个图吧
![image](https://user-images.githubusercontent.com/22856212/60377412-4efcef00-9a49-11e9-8a00-c4514b40dfb6.png)

**Comment by hustcc** [comment]
可以看下，两个例子中 echarts 版本分别是什么吗？

**Comment by hustcc** [comment]
我用你的 codesandbox 实例测试是，在 echarts-for-react 中是透明的，但是直接 echarts 执行，跟节点是空的。

**Comment by alecthw** [comment]
感觉很迷啊。。。
echarts-for-react 2.0.14
echarts 4.2.1
![image](https://user-images.githubusercontent.com/22856212/60406584-26abf680-9be9-11e9-9630-4b7eeb3a34f8.png)
![image](https://user-images.githubusercontent.com/22856212/60406601-45aa8880-9be9-11e9-8b0e-e49274bc30a8.png)

echarts-for-react 2.0.11 就是好的
echarts 4.2.1
![image](https://user-images.githubusercontent.com/22856212/60406698-d41f0a00-9be9-11e9-9d46-559688c66746.png)
