### ISSUE TITLE
堆叠条形图Y轴类目轴不显示头尾两个标签

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [hustcc/echarts-for-react#289]
问题：当Y轴的类目数较多（其实也不多，大于三个就会出现如下情况），就会导致第一个类目和最后一个类目的标签名不显示。
已配置 
```yAxis.axisLabel.interval = 0```
如下图：
![image](https://user-images.githubusercontent.com/20035768/58479534-125c8000-818b-11e9-8f61-b4bba4cab682.png)

当类目只有三个时正常显示：
![image](https://user-images.githubusercontent.com/20035768/58479653-3f109780-818b-11e9-8ccf-eeec2744db53.png)

求问如何让他们显示出来。感谢！

--------------
更新：
增加配置：
```yAxis.axisLabel.showMinLabel = true```
```yAxis.axisLabel.showMaxLabel = true```
后的效果（不显示第二个label）：
![image](https://user-images.githubusercontent.com/20035768/58480435-f3f78400-818c-11e9-8af3-734ed132a665.png)

**Comment by hustcc** [comment]
请到 echarts 仓库中提 issue。

**Comment by Shaunchenzhaojin** [comment]
echarts的提issue外链好像出来点问题？
![image](https://user-images.githubusercontent.com/20035768/59014512-66442480-886f-11e9-9df1-8523112eaf2a.png)
这个地方一直在zhuan转圈，无法提issues啊。在github上提也被直接关闭。。。

**Comment by hustcc** [comment]
echarts 地址是这个：https://github.com/apache/incubator-echarts
