### ISSUE TITLE
写了一个简单的demo，可是一直报错Cannot use 'in' operator to search for 'x' in

### ISSUE THREAD

**Issue by JieChang** [hustcc/echarts-for-react#29]
`class Charts extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            option: {
                title: {
                    text: 'Step Line'
                },
                tooltip: {
                    trigger: 'axis'
                },
                legend: {
                    data:[ 'Step Middle']
                },
                grid: {
                    left: '3%',
                    right: '3%',
                    bottom: '3%',
                    containLabel: true
                },
                toolbox: {

                },
                xAxis: {
                    type: 'category',
                    data: [],
                    splitLine: {
                        show: true
                    }
                },
                yAxis: {
                    type: 'value',
                    splitLine: {
                        show: false
                    }
                },
                series: [
                    {
                        name:'Step Middle',
                        type:'line',
                        step: 'middle',
                        data:[]
                    }
                ]
            },
            showChart: false,
        };
    }

    componentWillMount () {
        this.getChartDatas();
    }

    getChartDatas () {
        ajax({
            api: 'orderGoodsChartsData',
            method: 'get',
            data: {},
            withCredentials: true,
            crossOrigin: true
        }, suc => {
            if(suc.success != true){
                Toast.error(suc.message || '获取图表信息异常');
            }else{
                let data = suc.data || {},
                    option = this.state.option;
                    option.title = data.title;
                    option.xAxis.data = data.jxch && data.jxch.date;
                    option.series[0].data = data.jxch && data.jxch.out;
                this.setState({option: option, showChart: true});
            }
        }, err => {
            Toast.error('获取图表信息异常');
        });
    }

    render () {
        console.log('option',this.state.option);
        if(this.state.showChart){
            return (
                <div>
                    <ReactEcharts
                        option={this.state.option}
                        style={{height: '300px', width: '100%'}}
                        lazyUpdate={true}
                        theme={"theme_name"}
                        onChartReady={() => { console.log('onChartReady'); }}
                        onEvents={{
                            'click': () => {console.log('clickCharts');}
                        }} />
                </div>
            );
        }
        else{
            return <div></div>;
        }
    }
}

export default Charts;`

![image](https://cloud.githubusercontent.com/assets/8551885/21010413/e45449ce-bd86-11e6-8d52-a65ab72c465c.png)
![Uploading image.png…]()

**Comment by hustcc** [comment]
自己close了？解决了？
