### ISSUE TITLE
series动态更新

### ISSUE THREAD

**Issue by wellorange** [hustcc/echarts-for-react#290]
你好我在render函数里面这样写的,每次render渲染的时候option中的series都不一样, 但是没有动态渲染series中的值              

     <ReactEcharts
                         notMerge={true}
                         lazyUpdate={true}
                        option={option}
                        style={{ height: '700px', width: '100%' }}
                        className='react_for_echarts' />

**Comment by hustcc** [comment]
option 请使用 immutable 的方式更新！
