### ISSUE TITLE
如何实现一个页面里多个组件中的图表的自适应

### ISSUE THREAD

**Issue by 52jc** [hustcc/echarts-for-react#291]
一个react页面里有多个组件，多个组件里有echarts图表，且图表中有自己使用graphic画的线等图案，可是在子组件中使用window.onresize函数会冲突，有的不执行，若统一在主页面里使用window.onresize，graphic图案需要重画，需传入多个参数到主页面，有什么更好的办法能实现该页面的自适应吗？

**Comment by hustcc** [comment]
graphic 自适应都需要重绘的！
