### ISSUE TITLE
symbol使用Function时控制台提示symbolType.indexOf is not a function

### ISSUE THREAD

**Issue by eagleLiying** [hustcc/echarts-for-react#292]
这个问题官方 echarts 只有升级到4.2.1版本才能解决，希望echarts-for-react 可以同步升级

**Comment by hustcc** [comment]
echarts 是 peerDependence，你在自己项目中升级到最新即可。"echarts": "^3.0.0 || ^4.0.0"

另外，你用的 echarts-for-react 版本是什么？
