### ISSUE TITLE
Unable to call SetOption and getEchartsInstance

### ISSUE THREAD

**Issue by TylerGriffin99** [hustcc/echarts-for-react#294]
I am rendering the following stateless component in the DOM. This renders fine although in a parent component I have some redux actions that change state and hence props on this object (options).

When these props change I cannot get Echarts for react to rerender the component. I have tried setOption and using getEchartInstance

the parent component renders:
<CustomIrrigationConfigChart soilSettings={eChartOptions}  />

where eChartOptions = const eChartOptions = customIrrigationConfig(this.props.sample)

Any feedback on how I can access setOption and getChartInstance?

Thanks in advacne

**Comment by hustcc** [comment]
Are you use `getEchartsInstance` like [this](https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api)?

**Comment by TylerGriffin99** [comment]
> Are you use `getEchartsInstance` like [this](https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api)?

Yes I am. In the docs you detail as below but the problem here is that with React you have to create the let echarts_instance first but at that points this.echarts_react.getEchartInstance returns "getEcahrtsInstance is not a function os this.echarts"

// render the echarts component below with rel
<ReactEcharts ref={(e) => { this.echarts_react = e; }}
  option={this.getOption()} />

// then get the `ReactEcharts` use this.echarts_react

let echarts_instance = this.echarts_react.getEchartsInstance();

**Comment by TylerGriffin99** [comment]
Below is the stateless code I am using but am unable to get access to SetOpition and getEchartInstance. What I want to do is when props (option) change the component should rerender but because setOption is never called in the render method the Chart never gets refreshed. Do I have to set up a static method or componentDidUpdate method that looks to see if the next props are different - if they are call setOption?

Thanks in advance @hustcc 

`import React from 'react';
import Async from '../../../helpers/asyncComponent';
const ReactEcharts = (props) => <Async load={import('echarts-for-react')} componentProps={props} />;

  const CustomIrrigationConfigChart = (options) => {
    let echarts_react
    return (
      <ReactEcharts
        ref={(e) => { echarts_react = e;}}
        option = {options.soilSettings}
        style={{ height: 200 }}
        lazyUpdate={true}
        notMerge={true}
      />
    );
  }

export default CustomIrrigationConfigChart`
