### ISSUE TITLE
Can't Load 3D Bar Chart with Dataset Demo

### ISSUE THREAD

**Issue by mdasntc** [hustcc/echarts-for-react#295]
I'm trying to load the following example, but am getting an error:
https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1

The above error occurred in the <EchartsReact> component:
    in EchartsReact (at EChart3DBarWithDataset.js:80)
    in article (at EChart3DBarWithDataset.js:78)
    in div (at EChart3DBarWithDataset.js:76)
    in div (at EChart3DBarWithDataset.js:75)
    in section (at EChart3DBarWithDataset.js:74)
    in div (at EChart3DBarWithDataset.js:73)
    in div (at EChart3DBarWithDataset.js:72)
    in div (at EChart3DBarWithDataset.js:66)
    in EChart3DBarWithDataset (created by Connect(EChart3DBarWithDataset))
    in Connect(EChart3DBarWithDataset) (created by Route)
    in Route (at App.js:61)
    in main (at Layout.js:18)
    in div (created by Container)
    in Container (at Layout.js:14)
    in div (at Layout.js:10)
    in Unknown (at App.js:34)
    in Unknown (at src/index.js:29)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (at src/index.js:28)
    in Provider (at src/index.js:27)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. index.js:2178
    __stack_frame_overlay_proxy_console__ index.js:2178
    React 13
    unstable_runWithPriority scheduler.development.js:255
    React 14
    js index.js:26
    Webpack 6
Error: Component series.bar3D not exists. Load it first. clazz.js:178
    getClass clazz.js:178
    visitComponent Global.js:223
    forEach self-hosted:262
    each util.js:298
    visitComponent Global.js:212
    topologicalTravel component.js:125
    mergeOption Global.js:194
    initBase Global.js:663
    resetOption Global.js:141
    setOption Global.js:123
    setOption echarts.js:385
    renderEchartDom core.js:107
    rerender core.js:66
    componentDidMount core.js:125
    React 7
    unstable_runWithPriority scheduler.development.js:25

**Comment by hustcc** [comment]
> Error: Component series.bar3D not exists. Load it first. clazz.js:178

**Comment by pegues** [comment]
How do I load series.bar3D ? I'm already doing:

import ReactEcharts from 'echarts-for-react';

Do I need to get another library in addition to echarts and echarts-for-react?

**Comment by pegues** [comment]
My component code is below:

import React from 'react';
import { connect } from 'react-redux';

import SectionTitle from '../tools/SectionTitle';

import ReactEcharts from 'echarts-for-react';

import lifeExpectancy from '../../assets/json/life-expectancy-table.json';

// https://echarts.apache.org/examples/en/editor.html?c=bar3d-dataset&gl=1
class EChart3DBarWithDataset extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            mounted: false,
            sectiontitle: 'Demo: EChart 3D Bar With Dataset',
            chartstyle: {
                width: '100%',
                height: '800px'
            },
            chartoption: {
                grid3D: {},
                tooltip: {},
                xAxis3D: {
                    type: 'category'
                },
                yAxis3D: {
                    type: 'category'
                },
                zAxis3D: {},
                visualMap: {
                    max: 1e8,
                    dimension: 'Population'
                },
                dataset: {
                    dimensions: [
                        'Income',
                        'Life Expectancy',
                        'Population',
                        'Country',
                        { name: 'Year', type: 'ordinal' }
                    ],
                    source: lifeExpectancy
                },
                series: [
                    {
                        type: 'bar3D',
                        // symbolSize: symbolSize,
                        shading: 'lambert',
                        encode: {
                            x: 'Year',
                            y: 'Country',
                            z: 'Life Expectancy',
                            tooltip: [0, 1, 2, 3, 4]
                        }
                    }
                ]
            }
        };
    }

    componentDidMount() {
        console.log('EChart3DBarWithDataset.js mounted');

        this.setState({ mounted: true });
    }

    componentDidUpdate() {
        console.log('EChart3DBarWithDataset.js updated');
    }

    componentWillUnmount() {
        console.log('EChart3DBarWithDataset.js unmounted');

        this.setState({ mounted: false });
    }

    render() {
        return (
            <div className="main-inner">
                
                <SectionTitle sectiontitle={this.state.sectiontitle} />

                <div id="main-content" className="main-content">
                    <div className="widget-container help-container">
                        <section className="row">
                            <div className="widget widget-help no-heading col-12">
                                <div className="widget-inner">

                                    <article className="widget-content">
                                        
                                        <ReactEcharts option={this.state.chartoption} style={this.state.chartstyle} className="echart-visual" />

                                    </article>

                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        );
    }
}

export default connect()(EChart3DBarWithDataset);

**Comment by pegues** [comment]
I got it done. I first had to run

npm install --save echarts-gl

then

import 'echarts-gl';
