### ISSUE TITLE
主题怎么设置

### ISSUE THREAD

**Issue by qicainiao** [hustcc/echarts-for-react#296]
<ReactEcharts option={areaOption} style={{ height: '380px', marginBottom: '20px' }} theme='macarons2' />

或者     <ReactEcharts option={areaOption} style={{ height: '380px', marginBottom: '20px' }} theme={'macarons2'} />

都不好使

**Comment by hustcc** [comment]
先注册主题。如有 api 问题，请到 echarts 项目中提 issue。
