### ISSUE TITLE
自定义地图放大后，导出的图片不全

### ISSUE THREAD

**Issue by Dorisfeng** [hustcc/echarts-for-react#299]
例子：https://gallery.echartsjs.com/editor.html?c=xHyqn_rQ6g
自定义地图放大后，导出的图片不全
![image](https://user-images.githubusercontent.com/31895359/61202571-71199100-a71a-11e9-9b48-bfcea1ef3f6f.png)

**Comment by Croash** [comment]
这个不是echarts的问题么。。。

**Comment by hustcc** [comment]
echarts 的问题请到 echarts 项目中提 issue。
