### ISSUE TITLE
怎么动态加载

### ISSUE THREAD

**Issue by mailbaoer** [hustcc/echarts-for-react#3]
现在的版本加载了所有module，导致整体js大很多，怎么才能动态加载呢

**Comment by hustcc** [comment]
很好的问题，echarts官方是支持按需引入的，但是echarts-for-react是直接引入了echarts，确实会增加不需要的引入，也会包体大小。

我要想想怎么解决，你有比较好的解决办法吗？

**Comment by ZhengHe-MD** [comment]
我觉得是这样的吧。echarts 有lib和umd两种build. 在commonjs里面应该import lib里面的代码，这样只需要import需要的模块。［实际上我没看过源码，不过一般是这样的吧。就如import { map } from 'lodash'一样 ］

**Comment by hustcc** [comment]
这个做法可行，对于用户（开发者）来说，需要按需引入，入门会稍难一些，所以还是需要兼容目前的写法。

**Comment by codering** [comment]
实在不行就不强依赖echarts, 然用户自己去管理echarts的依赖怎么样？
 ```js
import echarts from 'echarts/lib/echarts'
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/bar'

....
....

import ReactEcharts from 'echarts-for-react'

```

**Comment by codering** [comment]
以后有时间也可以自己写babel插件

**Comment by hustcc** [comment]
@codering 我的想法是增加一个modules属性传入进入，如果这个属性为空，那么就引入全部echarts，否则就应用最小依赖。

这样的好处在于可以兼容旧版本的代码，不然以前的用户一升级导致代码除了bug，那不是坑爹^_^~

**Comment by codering** [comment]
modules属性值是 ？

**Comment by hustcc** [comment]
```js
<ReactEcharts 
    modules={[]}
    ... />
```
组件的props。

**Comment by codering** [comment]
@hustcc 数组里的值是什么? echarts里功能模块路径吗？然后内部异步加载？

**Comment by hustcc** [comment]
嗯，模块路径~这样可行吗？
首先肯定是需要兼容旧版本代码的~

**Comment by codering** [comment]
既然都是写路径，我宁愿用我先前说的方案。
用户完全可以单独建一个echartsLib.js，专门管理需要的echarts功能模块:
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/bar'

....
....

然后你内部依赖改到最小，用户的用法什么都没变，只是多依赖了一个echartsLib.js，而且这个配置是全局通用的，也可以异步加载，感觉这样的兼容性是最好的。

**Comment by walter211** [comment]
可以通过uiwebview整合到react-native项目里么

**Comment by hustcc** [comment]
使用webview的话，理论上是没有问题的~~~
react-native的呼声很高啊，我抽时间学习一下rn，然后测试试试看~

**Comment by Sinovel** [comment]
有没有一个单个的demo,或者都整合在一个文件的，现在的bundle.js太乱看不懂。

**Comment by hustcc** [comment]
demo目录就是网页的全部代码…

**Comment by Sinovel** [comment]
单独的一个bar或者line的demo，这样那个bundle.js能不能简化？初学看不懂

**Comment by hustcc** [comment]
[https://github.com/hustcc/echarts-for-react/blob/master/demo/SimpleChartComponent.jsx](https://github.com/hustcc/echarts-for-react/blob/master/demo/SimpleChartComponent.jsx)

看这个文件，这个是[http://git.hust.cc/echarts-for-react/#/echarts/simple?_k=2xkjj3](http://git.hust.cc/echarts-for-react/#/echarts/simple?_k=2xkjj3) 这个图。

**Comment by Sinovel** [comment]
web前端脚本还是加载不出来，这个有没有前端脚本的demo

**Comment by hustcc** [comment]
这个就是前端脚本啊，你学习了react了没？

**Comment by Sinovel** [comment]
就学了一点这种简单的http://www.ruanyifeng.com/blog/2015/03/react.html，你的这种应该比较高级，看不懂，引用那些JSX文件也显示不出来结果

**Comment by cdoneshot** [comment]
内部暴露一个setModules方法，用户在入口文件配置依赖的模块，如果没有配置，默认引入最小依赖，这种对现在的使用也不会造成影响，同时支持用户自己配置依赖模块。

**Comment by hustcc** [comment]
> 如果没有配置 setModules ，默认引入最小依赖。

这样会影响已经使用的人吧，一旦他们升级 echarts-for-react 版本，就必须修改代码。**如果没有设置，默认为全量引入**，这样貌似可以。

**Comment by cdoneshot** [comment]
> 这样会影响已经使用的人吧，一旦他们升级 echarts-for-react 版本，就必须修改代码。如果没有设置，默认为全量引入，这样貌似可以。
嗯

**Comment by hustcc** [comment]
你如果有兴趣，可以提交一个 pr 啊，另外在实例中添加一个 demo。^_^

**Comment by yangggggg** [comment]
地图相关的组件，我想在页面进来的时候向后端发请求，然后渲染到页面上，不知道怎么设置setOption，求指教

**Comment by hustcc** [comment]
在 state 中放一个 option 数据，先 setOption 为一个空的对象，然后在请求数据成功之后，再 setState 设置请求到的 option 数据。

**Comment by yangggggg** [comment]
感谢！！！

**Comment by hustcc** [comment]
@RelaxLiu 客气了，注意以后有问题的时候，如果 issue 中没有相关的主题，可以新建一个 issue，而不是把问题提到一个不相关的 issue 上面。^_^

**Comment by RelaxLiu** [comment]
@hustcc 了解

**Comment by liaohui1080** [comment]
@hustcc 

import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/bar'

现在可以这样引入组件吗?
是否已经支持

**Comment by hustcc** [comment]
还不支持~ @liaohui1080 具体来说不知道如何实现比较好，如果你有一些想法，欢迎讨论或者 pr。

**Comment by sbyps** [comment]
@codering 如何集成到webpack中进行按需加载echarts和这个echarts-react？自己在项目内部中新建所说的echarts-lib，然后webpack会自动引入？

**Comment by sbyps** [comment]
@hustcc 能否提供一个支持按需加载的版本，或者给个整体思路

**Comment by hustcc** [comment]
```js
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/bar'
```

在使用本项目组件的时候，先 import 需要的部分，试试看打包出来的 bundle 会不会减少。

**Comment by sbyps** [comment]
https://github.com/recharts/babel-plugin-recharts

**Comment by jindada** [comment]
@hustcc  感觉通过babel-plugin无法按需加载 获取不到echarts的option

**Comment by hustcc** [comment]
babel-plugin-recharts 和这个相关没有什么关系啊~

**Comment by hustcc** [comment]
v1.3.5 版本发布，支持自定义加载 echarts 模块，减少打包之后的 js 文件大小，感谢 @SidKwok
