### ISSUE TITLE
支持添加文字描述吗

### ISSUE THREAD

**Issue by JieChang** [hustcc/echarts-for-react#30]
![Uploading image.png…]()

**Comment by hustcc** [comment]
你的图片没有上传成功。

**Comment by JieChang** [comment]
![image](https://cloud.githubusercontent.com/assets/8551885/21035013/17fea182-bdf7-11e6-8d77-19f6ff2dddd8.png)

**Comment by hustcc** [comment]
这个和组件没有关旭，你需要去查询 echarts 的配置文档，我了解到的 [markline](http://echarts.baidu.com/option.html#series-line.markLine) 的配置可以实现这样的功能，具体的实现，可以自己看一下文档。
