### ISSUE TITLE
Cannot read property 'getRawIndex' of undefined

### ISSUE THREAD

**Issue by wustdjf** [hustcc/echarts-for-react#304]
这种错误怎么解决啊，力引导图还没绘制完成，鼠标hover就会报错。echarts-for-react有没有方法判断图片是否加载完成呢

**Comment by albertogaldames** [comment]
I'm getting this same erro when I try to call an action of redux inside the `showTip` event.

```
_handleMouseMove = (params) => {
    const { _setYearHover, yearHover } = this.props;
    const { dataIndex } = params;

    if (dataIndex !== yearHover) {
      _setYearHover(dataIndex);
    }
}
```

Does someone know why?
The error seems to be in this part of the code

![image](https://user-images.githubusercontent.com/24230959/63919233-a108c380-ca3e-11e9-9c76-dc4fd77b657c.png)

**Comment by Li-Kuan** [comment]
同问！！！

**Comment by hustcc** [comment]
请到 echarts 项目中提 issue。
