### ISSUE TITLE
使用ReactEchartsCore写中国地图，地图无法显示

### ISSUE THREAD

**Issue by symnetry** [hustcc/echarts-for-react#310]
如果引入echarts-for-react和加载'echarts/map/js/china.js'是可以正确显示的
但对我来说实在太卡了 采用按需加载 我的引用如下

import ReactEchartsCore from 'echarts-for-react/lib/core';
import echarts from 'echarts/lib/echarts';
import 'echarts/lib/chart/bar';
import 'echarts/lib/chart/scatter';
import 'echarts/lib/chart/map';
import 'echarts/lib/chart/effectScatter';
import 'echarts/lib/component/grid';
import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/geo';
import 'echarts/lib/component/title';
import 'echarts/map/js/china.js'

没有报错，也无法显示

**Comment by hustcc** [comment]
应该是包不够，请到 echarts 项目中提 issue。
