### ISSUE TITLE
在React Hook 中 添加事件onEvents，组件每次render都引起echarts重新渲染

### ISSUE THREAD

**Issue by wlc534** [hustcc/echarts-for-react#311]
实例地址： https://codesandbox.io/s/currying-grass-dg92t   点击+ 按钮增加数字，点击柱子也能增加数字，但echarts 图表每次都重新渲染

**Comment by SidKwok** [comment]
因为每次渲染你生成的option和onEvents都是新的，组件自然就重新渲染了。建议使用useState或useCallback去解决问题。

**Comment by sym233** [comment]
能说详细点吗

**Comment by howel52** [comment]
> 能说详细点吗，有没有demo

https://github.com/hustcc/echarts-for-react/blob/1bea79331ff68b80fe30f7c9bd345a0c80d27230/src/core.jsx#L19-L34

**Comment by sym233** [comment]
> > 能说详细点吗，有没有demo
> 
> https://github.com/hustcc/echarts-for-react/blob/1bea79331ff68b80fe30f7c9bd345a0c80d27230/src/core.jsx#L19-L34

问的是hook啊

**Comment by xhwgood** [comment]
请问你的问题怎么解决的？
我将echart封装成一个组件，然后用React.memo包裹，但还是重新渲染了，真的想不通
