### ISSUE TITLE
求发新版本

### ISSUE THREAD

**Issue by phobal** [hustcc/echarts-for-react#314]
hustcc 你好，我正在基于该库进行图表封装，采用的 TS，但是发现一处问题，就是在设置 theme 类型的时候提示类型错误， theme 的类型应该有 3 种 `string | null | object`, 我看最新的代码中也是这么设置的 https://github.com/hustcc/echarts-for-react/commit/5763e01a4d5d6add169799d421f5227c69a577c2，但是我使用的最新版 (v2.0.15-beta.0) theme 的类型还是 `string | null`

![image](https://user-images.githubusercontent.com/9244211/65828148-41663800-e2ca-11e9-9b7a-da83599f6447.png)

麻烦你更新一下包，谢谢

**Comment by hustcc** [comment]
好的，稍等~

**Comment by hustcc** [comment]
done
