### ISSUE TITLE
echarts events 'finished' 触发多次

### ISSUE THREAD

**Issue by shuai4983958** [hustcc/echarts-for-react#315]
renderDifficultyRatio = () => {
    const onEvents = {
      finished: this.onChartFinished,
    };
    return (
       <ReactEcharts
          option={this.getDifficultyRatioOption()}
          theme="Imooc"
          onEvents={onEvents}
          style={{ height: '350px' }}
        />
      </section>
    );
  };

**Comment by shuai4983958** [comment]
onChartFinished = () => {
    alert('finish')
    // this.props.onPieFinished();
  };

2-3次alert

**Comment by howel52** [comment]
see: https://github.com/hustcc/echarts-for-react/blob/b1df3b339bf07d4f6a2b8fdc62ed3bc4c93f2d0d/src/core.jsx#L32
