### ISSUE TITLE
请问如何判断点击的空白处，

### ISSUE THREAD

**Issue by songhan777** [hustcc/echarts-for-react#316]
原生的时候可以使用，来判断
 myChart.getZr().on(“click”.params)
但是框架的该如何判断呢

**Comment by songhan777** [comment]
https://xbuba.com/questions/52752552         
找到解决方案了

**Comment by wanglihuaya** [comment]
[https://github.com/hustcc/echarts-for-react/issues/537](https://github.com/hustcc/echarts-for-react/issues/537)
这个
