### ISSUE TITLE
[Events] How to bind event listeners with a query?

### ISSUE THREAD

**Issue by SevenOutman** [hustcc/echarts-for-react#318]
According to [ECharts documentation]( https://echarts.apache.org/zh/api.html#echartsInstance.on), the `chart.on(eventName, query, handler)` accepts a second parameter `query` in order to specify a event target. But I've got no clue how I can pass `query` via `onEvents` props.

**Comment by hustcc** [comment]
请到 echarts 项目中提 issue。

**Comment by SevenOutman** [comment]
@hustcc 这不是 echarts 的问题，是在问你这边 props 设计的问题。

**Comment by hustcc** [comment]
chart 事件，可以在 onChartReady 之后（或者通过 ref），拿到 chart 实例，然后调用 api 就参考 echarts 文档就好了。

这部分并没有在项目中有任何改变。
