### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jiangyh1024** [hustcc/echarts-for-react#319]
![image](https://user-images.githubusercontent.com/34930870/66904583-e73dd480-f036-11e9-9cd4-2e17f84c9287.png)

![image](https://user-images.githubusercontent.com/34930870/66904603-eefd7900-f036-11e9-903f-85b753b9a9ef.png)

如果 字符串是个数字 后面的数据不会被显示

**Comment by hustcc** [comment]
请到 echarts 项目中提 issue。
