### ISSUE TITLE
按需加载的问题

### ISSUE THREAD

**Issue by a-boom** [hustcc/echarts-for-react#321]
import ReactEchartsCore from 'echarts-for-react/lib/core';
import echarts from 'echarts/lib/echarts';
import { Button, message } from 'antd';
import moment from "moment";
import 'echarts/lib/component/tooltip';
import 'echarts/lib/chart/bar';
import 'echarts/lib/component/title';

**Comment by a-boom** [comment]
这样是正确的吗

**Comment by hustcc** [comment]
正确
