### ISSUE TITLE
ios13.2系统safari浏览器上查看统计图，手指点击图元，出现的tooltip有很大概率被图元遮挡

### ISSUE THREAD

**Issue by dengsilong** [hustcc/echarts-for-react#323]
### Version
2.0.15-beta.0

### Steps to reproduce
iphone手机safari浏览器浏览网页，查看基本echarts饼状图，手指点击饼块，显示tooltip，tooltip被图形遮盖

### What is expected?
tooltip正常显示不被遮盖

### What is actually happening?
tooltip被遮盖
![TIM截图20191108144335](https://user-images.githubusercontent.com/57519055/68457204-aeaaa880-023a-11ea-8a20-de5ee7fcc5ff.jpg)

---
ios12.4系统上显示正常，ios13.2系统上被遮挡

**Comment by Marszht** [comment]
我也有这个问题， 解决了么

**Comment by dengsilong** [comment]
echart全局tooltip设置position，解决当前版本echarts统计图tooltip在ios13环境下被图形遮盖问题
tooltip = {
                    position: (point, params, dom, rect, size) => { dom.style.transform = "translateZ(0)"; },
                }
