### ISSUE TITLE
设置series中label的显示问题

### ISSUE THREAD

**Issue by miaocunzhi** [hustcc/echarts-for-react#331]
譬如折线图的节点数值显示：
动态更改了option中series的label.show为true，打断点看已经调用了setOption，但是页面中并没有显示。设置label.show为false也没有效果
只有初始化的时候将label.show为true或者为false，才会显示或者隐藏数值
![1576551815(1)](https://user-images.githubusercontent.com/20124199/70961411-b0c71900-20bc-11ea-9379-9f92949041ab.png)

**Comment by howel52** [comment]
贴个 codepen 的 demo 吧

**Comment by miaocunzhi** [comment]
@howel52 codepen的demo用不起来

![截图](https://user-images.githubusercontent.com/20124199/70968670-d6601c80-20d4-11ea-9d65-14b95aff246e.jpg)

大概就是这么个意思会改变option，其他配置改变都能生效，只有label的show没效果
