### ISSUE TITLE
tooltip 设置请教

### ISSUE THREAD

**Issue by airship-shrimp** [hustcc/echarts-for-react#332]
请教一下如何设置tooltip可以使水平线始终在value的高度上而不是鼠标位置？

![tooltip](https://user-images.githubusercontent.com/55677683/71243798-0f55f680-234c-11ea-8fb1-2c5759b485e7.png)

**Comment by hustcc** [comment]
参考 echarts 官方文档，或者在 echarts 仓库中提 issue，这里仅仅是 react 组件的封装，option 配置不会做二次封装。
