### ISSUE TITLE
Is there support for annotations?

### ISSUE THREAD

**Issue by ivan-ivan** [hustcc/echarts-for-react#333]
I'm wondering if there's support for annotations as Grafana library provides:
https://grafana.com/docs/grafana/latest/reference/annotations/
Are there any ways to implement/extend library's functionality so that we can have something like this?

**Comment by hustcc** [comment]
Sorry, you should issue on [echarts](https://github.com/apache/incubator-echarts), here is only the react wrapper for echarts.
