### ISSUE TITLE
reduce bundle size using gl

### ISSUE THREAD

**Issue by claud-io** [hustcc/echarts-for-react#334]
Hi, how can i reduce the bundle size if im using echarts-gl? 
Using  `import ReactEcharts from 'echarts-for-react'; ` will import everything from echarts, i want to reduce bundle size as i did for normal charts. 
Is there a way to do it with `ReactEchartsCore`?

Thanks.

**Comment by hustcc** [comment]
see readme.

**Comment by claud-io** [comment]
Hi, thanks for reply, i've already read it, but didn't find how to import/use echart-gl to reduce bundle size.

Can u help me?

Thanks.

**Comment by hustcc** [comment]
linke [here](https://github.com/hustcc/echarts-for-react#gl)

```
import 'echarts-gl'
import React from 'react';
// import the core library.
import ReactEchartsCore from 'echarts-for-react/lib/core';

// then import echarts modules those you have used manually.
import echarts from 'echarts/lib/echarts';

<ReactEcharts
  option={GL_OPTION}
/>
```

**Comment by claud-io** [comment]
Hy @hustcc, thanks for your reply, 

i've already did it, maybe my question is not clear, let me add an example:

This is my bundle before using echarts-gl: 

![Screenshot 2020-01-08 at 09 14 52](https://user-images.githubusercontent.com/51945810/71961427-92ee5f00-31f7-11ea-8f0f-65bf5d9d5084.png)

then i'want to add a 3d chart so this is a piece of my code:

```
import React, { Component } from 'react'
import _ from 'lodash'

import 'echarts-gl'
import ReactEchartsCore from 'echarts-for-react/lib/core';
import echarts from 'echarts/lib/echarts';
import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/visualMap';
...

return (
            <ReactEchartsCore
                echarts={echarts}
                lazyUpdate={true}
                style={{ height: this.props.height, width: '100%' }}
                option={option}  />                  
 );


```

As you can see, doing `**import 'echarts-gl'**` will import everything from echarts

![Screenshot 2020-01-08 at 09 14 26](https://user-images.githubusercontent.com/51945810/71961572-eb256100-31f7-11ea-89aa-7c8d3c8b7672.png)

Is there a way to avoid this?

Thanks

**Comment by hustcc** [comment]
This is the bug of echarts-gl, you can issue on [here](https://github.com/ecomfe/echarts-gl).

echarts-gl export the dist file, may cause full echarts to be packaged.
