### ISSUE TITLE
A <object> element in HTML

### ISSUE THREAD

**Issue by ZZITE** [hustcc/echarts-for-react#335]
i find it always add a <object> element in my HTML, like:
`
<object style="display:block;position:absolute;top:0;left:0;height:100%;width:100%;overflow:hidden;pointer-events:none;z-index:-1;opacity:0" class="size-sensor-object" tabindex="-1" type="text/html" data="about:blank"></object>
`

and this <object> element dating an audio resource, why is this？

**Comment by hustcc** [comment]
it is created by [size-sensor](https://github.com/hustcc/size-sensor).

after upgrade to the latest version, it will not be create on modern browser.
