### ISSUE TITLE
Adding onEvents causes force graph to re-render

### ISSUE THREAD

**Issue by sudravi** [hustcc/echarts-for-react#337]
I'd like to add a click handler to my force graph so I can interact with nodes. But as soon as I add onEvents, even a dummy one like the one below, my entire graph re-renders whenever another UI element is touched. For example, I have a dropdown menu above my graph, and when I interact with the menu, the graph re-renders. Is there a way to avoid this?

```
<ReactEcharts
   onEvents={{ click: () => {} }}
   style={{ height: '600px', width: '100%' }}
   option={options}
/>
```

**Comment by benmliang** [comment]
+1. I have the same issue..

**Comment by sudravi** [comment]
@benmliang The workaround I used was to set the event handler in a state variable. So in the code below, {onEvents} refers to a state variable that I initialize when the graph is ready. I initialize it to {click: onNodeClick} in my case.

```
<ReactEcharts
   onEvents={onEvents}
   style={{ height: '600px', width: '100%' }}
   option={options}
/>
```

**Comment by benmliang** [comment]
Thanks it works for me

**Comment by WhoAteDaCake** [comment]
Using `React.useCallback` for event functions solved it for me

**Comment by pumpkindev** [comment]
> Using `React.useCallback` for event functions solved it for me
perfect

**Comment by dispeakble** [comment]
> Using `React.useCallback` for event functions solved it for me

Hi, could you give an example for the onEvents prop with a click event listener without re-rendering the whole chart after one click? I have tried with the useCallback but it still re-renders.
Currently I have:

const onBarClick = useCallback((params) => {console.log(params)}, []);

const onEvents = {
  click: onBarClick
}

return <ReactEcharts
  ...
  onEvents={onEvents}
/>;

**Comment by markpenfold** [comment]
Does anyone have an example of this working? I'm using the callback route too but still constantly re-rendering
Thanks!

**Comment by hustcc** [comment]
> Does anyone have an example of this working? I'm using the callback route too but still constantly re-rendering
> Thanks!
> 

which version？

**Comment by markpenfold** [comment]
Hi hustcc, I'm using react 19.1.0 and react-force-graph 1.29.

I'm able now to mutate the color of a node. But any change to the graph, like adding a link, forces a full reload. So all the positions/physics are reset. I just want to be able to update without a full reworking... 

Thanks!

To change color I'm doing this:


```
const handleNodeClick = useCallback((node: any) => {
  if (!node || !graphRef.current) return;

  // Reset old node
  if (selectedNodeRef.current && selectedNodeRef.current !== node) {
    selectedNodeRef.current.color = selectedNodeRef.current.saved_col;
  }

  // Toggle
  if (selectedNodeRef.current === node) {
    node.color = node.saved_col;
    selectedNodeRef.current = null;
    setSelectedNode(null);
  } else {
    node.color = '#ff0000';
    selectedNodeRef.current = node;
    setSelectedNode(node.id);
  }

  graphRef.current.refresh?.();
}, [setSelectedNode]);

```

**Comment by markpenfold** [comment]
OK, I have it working now. This feels like a massive hack though. 

Basically, the idea is to grab the currently existing nodes (including their positions etc. as force graph has set them) Then only update any nodes that are new. 

I can't work out how to get back the live nodes. 


So I've added a ref which tracks them, and update based on this:

```useEffect(() => {
    const limitedEvents = timelineBuilderEvents.slice(0, 100);


    const prevNodesById: Map<GraphNode['id'], GraphNode> = new Map(
      (graphRef.current?.graphData?.nodes as GraphNode[] | undefined)?.map(
        (n) => [n.id, n]) ?? []
    );

  const nodes: GraphNode[] = limitedEvents.map((event): GraphNode => {
  const nodeId = event._id.toString();
  const baseColor = getCollectionColor(event.collection) || '#3b82f6';

  const existingNode = prevNodesById.get(nodeId);

  if (existingNode) {
    // Optional: update fields that may change
    existingNode.name = event.event;
    existingNode.description = event.additional_information || '';
    existingNode.saved_col = baseColor;

    return existingNode;
  }

  // New node
  return {
    id: nodeId,
    name: event.event,
    year: event.date_obj?.year
      ? event.date_obj.year > 0
        ? `${event.date_obj.year} AD`
        : `${Math.abs(event.date_obj.year)} BC`
      : '',
    val: 3,
    color: baseColor,
    saved_col: baseColor,
    description: event.additional_information || '',
  };
});
//... do link stuff here

    setGraphData({ nodes, links });

  }, [timelineBuilderEvents, getCollectionColor]);```

**Comment by hustcc** [comment]
it is not the issue of this repo？

**Comment by markpenfold** [comment]
Doh! Similar problem though, so maybe this work-around can help?

M
