### ISSUE TITLE
setCursorStyle when i getEchartsInstance

### ISSUE THREAD

**Issue by prrrcl** [hustcc/echarts-for-react#339]
I need change cursor. [How to change the cursor on the series? #5588](https://github.com/apache/incubator-echarts/issues/5588) There is the official api. They said:

> `chart.on('mousemove', params => {
      const { professionId } = params.data
      if (professionId) {
        chart.getZr().setCursorStyle('pointer')
      } else {
        chart.getZr().setCursorStyle('default')
      }
    })`

> 

I tried with: `chart.current.getEchartsInstance()._api._getZr().setCursorStyle('default')`, and i got undefined. Whats happen?

**Comment by NeroMorto** [comment]
Hi! First of all check that the instance exists (I mean render was finished and you have an instance)
Best way (IMHO) to do this in 'finished' event handler.
And second try this code:
`this.echartsReact.current.getEchartsInstance().getZr().setCursorStyle('crosshair')` (Skip ._api._)

**Comment by AbhaysinghBhosale** [comment]
Want to set default cursor to already drilled items as they cant be drilled more in sunburst, Is there any way for this ?
