### ISSUE TITLE
How can I use the dispatchAction Function in Echarts

### ISSUE THREAD

**Issue by AlisaBen** [hustcc/echarts-for-react#340]
I can use the dispatchAction like this:
`
myChart.dispatchAction({
    type: 'highlight',  
    type: 'downplay',          
    seriesIndex: number|Array,  
    seriesName: string|Array, 
    dataIndex: number,        
    name: string                
});
`
And how can I use it in echarts-for-react?

**Comment by howel52** [comment]
You can get the ref in this way, see https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api
