### ISSUE TITLE
Echarts 富文本标签 rich 配置不生效

### ISSUE THREAD

**Issue by zhangsenhua** [hustcc/echarts-for-react#342]
如题，无法实现 富文本标签
示例：https://www.echartsjs.com/zh/option.html#title.textStyle.rich
示例：https://www.echartsjs.com/zh/tutorial.html#%E5%AF%8C%E6%96%87%E6%9C%AC%E6%A0%87%E7%AD%BE

**Comment by bcheok** [comment]
請問有解決方法嗎？

**Comment by bcheok** [comment]
應該是SVG render 所以沒有rich

**Comment by Travistom** [comment]
确实是这个原因

> 應該是SVG render 所以沒有rich

**Comment by Jatal8080** [comment]
我也是用了 SVG render 之后， 富文本标签rich就实效了， 请问有解决办法了吗现在

**Comment by lifuzhao100** [comment]
@zhangsenhua
1、可以提供一个example吗？
2、建议使用同样的option，直接对接echarts，看看rich富文本能不能使用
像rich富文本这样的东西，跟这个组件是100%没有关系的，很多情况下就是使用echarts的姿势不对。

**Comment by Marszht** [comment]
> 應該是SVG render 所以沒有rich

是 echart 在 5.0 以后的版本不支持，在 5.0 之后会支持
