### ISSUE TITLE
TS6131 TypeScript (TS) 无法使用选项“outFile”来编译模块，除非 "--module" 标记为 "amd" 或 "system"。

### ISSUE THREAD

**Issue by Nathan2020-0126** [hustcc/echarts-for-react#343]
当我引入ecarts for react时，提示这个错误
TS6131 TypeScript (TS) 无法使用选项“outFile”来编译模块，除非 "--module" 标记为 "amd" 或 "system"。

我的项目文件
![图片](https://user-images.githubusercontent.com/16734387/75617316-712aac00-5b98-11ea-91b8-188425ace9ed.png)

![图片](https://user-images.githubusercontent.com/16734387/75617325-9d462d00-5b98-11ea-8d12-17ec8c42a464.png)

**Comment by hustcc** [comment]
看不懂~
