### ISSUE TITLE
容器隐藏时触发resize

### ISSUE THREAD

**Issue by ligaofeng0901** [hustcc/echarts-for-react#344]
容器隐藏时（父容器dom的style.display='none'），触发了resize事件，echarts会认为容器大小为0。当容器再次出现时（父容器dom的style.display='block'），再次触发resize事件，这是会出现一个不自然的动画，图表从左上方展开，实际上是0到当前大小的一个过渡动画。能否加一个在resize的时候判断一下容器是否被隐藏或大小为0时不触发resize的逻辑？

**Comment by Junior2Ran** [comment]
建议魔改

**Comment by hustcc** [comment]
建议直接移出容器，而不是英镑容器。
