### ISSUE TITLE
Graph options : TypeError: el is undefined

### ISSUE THREAD

**Issue by Jayesh23** [hustcc/echarts-for-react#349]
Version
4.7.0

Steps to reproduce
import ReactEchartsCore from "echarts-for-react/lib/core";

<ReactEchartsCore
ref={refRef}
echarts={echarts}
style={{ height: "100vh", left: 0, top: 0, width: "100%" }}
option={/* a function which returns an Echarts option to generate a timseries graph */}
onEvents={{
click: propertyTable,
// contextmenu: Playground
}}
/>

sample Echarts Object : https://gallery.echartsjs.com/editor.html?c=xZ9kqwdwb4&v=2

When i try to set series.fixed : true
i get an error :- TypeError: el is undefined

its working fine when fixed is set to false.

However when i push the output of the code manually to the ReactEchartsCore option it renders the graph,
I have cross checked by replacing the option in the apache echarts site also it renders the graph there as well.

What is expected?
A timeseries graph i.e i have a let's say data of 10 timestamps and for each timestamp i have data for 11 nodes, i just want to fix the position of all the nodes for each time stamp.

What is actually happening?
Not able to get the timeseries graph when trying to directly pass option through a function to the ReactEchartsCore option.

error in line main.bundle.js 83143:7
var el = edge.getGraphicEl();
el[FOCUS_ADJACENCY] && el.off('mouseover', el[FOCUS_ADJACENCY]);
el[UNFOCUS_ADJACENCY] && el.off('mouseout', el[UNFOCUS_ADJACENCY]);
![Screenshot from 2020-04-08 18-05-38 (copy)](https://user-images.githubusercontent.com/20610884/79444196-7d5bb300-7ff8-11ea-94eb-6de6708f408e.png)

**Comment by hustcc** [comment]
please create issue on echarts repo.
