### ISSUE TITLE
高度自适应应该怎么做

### ISSUE THREAD

**Issue by jasminecjc** [hustcc/echarts-for-react#35]
如题，是竖向的柱状图，固定每条柱状图的宽度和间距，让图表高度自适应，这个怎么做呢

**Comment by hustcc** [comment]
**1. css 实现**：给组件设置 class 属性，给 class 对应的 css 代码；或者直接传入 style。
**2. js 实现**：使用 api 获得组件的 dom，然后使用 js 去控制他的高度。
