### ISSUE TITLE
onEvents这么比较存在问题

### ISSUE THREAD

**Issue by wqzwh** [hustcc/echarts-for-react#350]
```js
if ( 
   !isEqual(prevProps.theme, this.props.theme) || 
   !isEqual(prevProps.opts, this.props.opts) || 
   !isEqual(prevProps.onEvents, this.props.onEvents) 
 ) { 
   this.dispose(); 
  
   this.rerender(); // 重建 
   return; 
 } 
```

以上代码中` !isEqual(prevProps.onEvents, this.props.onEvents) `存在问题，经过lodash测试发现：

```js
_.isEqual({}, {})  // true

_.isEqual({click: ()=> 1}, {click: () => 1})  // false，期望应该返回true

_.isEqual(Object.keys({click: ()=> 1}), Object.keys({click: () => 1})) // true
```

所以建议使用Object.keys包裹下，当然如果怕引用类型可以再加个sort()，期望可以提交个pr来解决问题

@hustcc

**Comment by hustcc** [comment]
> _.isEqual({click: ()=> 1}, {click: () => 1})  // false，期望应该返回true

这个返回 false 是正确的，因为 function 的引用不一样。 按照下面的写法就是对的。

```ts
const click = () => 1

_.isEqual({click: click}, {click: click});
```

**Comment by wqzwh** [comment]
> > _.isEqual({click: ()=> 1}, {click: () => 1})  // false，期望应该返回true
> 
> 这个返回 false 是正确的，因为 function 的引用不一样。 对于 function 按照下面的写法才是 true。
> 
> ```ts
> const click = () => 1
> 
> _.isEqual({click: click}, {click: click});
> ```

但是我在使用的时候却是返回的false

**Comment by hustcc** [comment]
> _.isEqual({click: ()=> 1}, {click: () => 1}) // false

你按照这个写，肯定是 false，这个没有问题的。因为这是两个不同的 function。

**Comment by wqzwh** [comment]
实际场景中我在组件上绑定了一个click方法，但是 `prevProps.onEvents` 和 `this.props.onEvents`经过这里比较（`!isEqual(prevProps.onEvents, this.props.onEvents)` ）之后返回的是true，期望的是false

**Comment by wqzwh** [comment]
![image](https://user-images.githubusercontent.com/16662470/79556999-6a1e1580-80d4-11ea-9f8d-c21d349e07ae.png)
![image](https://user-images.githubusercontent.com/16662470/79557014-74d8aa80-80d4-11ea-8d80-7a7659886cc9.png)

以上两个比较之后返回的是true，期望是返回false。 @hustcc  麻烦看看

**Comment by hustcc** [comment]
```ts
class Component {

  onClick = () {

  }

  render() {}

    return (<EchartForReact option={...} onEvents={{
      click: this.onClick
    }}>)
  }
}
```

按照上面的方式写，事件 callback 挂到 this 上。

**Comment by wqzwh** [comment]
> ```ts
> class Component {
> 
>   onClick = () {
> 
>   }
> 
>   render() {}
> 
>     return (<EchartForReact option={...} onEvents={{
>       click: this.onClick
>     }}>)
>   }
> }
> ```
> 
> 按照上面的方式写，事件 callback 挂到 this 上。比较就是 true 了。使用 key 的问题，在于，我的 callback 换了一个实现，也不会被感知到。

我这边用的是函数试绑定，组件里面不存在this的概念

**Comment by hustcc** [comment]
函数式组件确实存在这个问题~我也是最近刚在需求中写了一些 hook~使用 keys 的方式肯定不是很好~

**Comment by hustcc** [comment]
@wqzwh 我知道在 FC 怎么做了。

我想使用类似于 component 组件中的 this 该怎么办，用它跟踪变量的变化，但是不触发 re-render。那就是使用 useRef。

**Comment by hongdeyuan** [comment]
能不能，给一个具体的例子🌰

**Comment by nmsn** [comment]
遇到同样的问题

```jsx
const onEvents = useMemo(
    () => ({
      mouseover: item => {
        onMouseCallback?.(item?.dataIndex);
      },
      mouseout: item => {
        onMouseCallback?.(null);
      },
    }),
    [],
  );
```

绑定事件，每次都触发都会 rerender

**Comment by hongdeyuan** [comment]
本人已收到您的邮件，辛苦了！如有重要事情，看到后，将尽快给你回复。。。

**Comment by MrZhouZh** [comment]
大佬, 能贴个示例吗

**Comment by hustcc** [comment]
useCallback 缓存下方法，保持引用。
