### ISSUE TITLE
如何将默认语言设置成英文

### ISSUE THREAD

**Issue by cx7388** [hustcc/echarts-for-react#351]
toolbox数据显示界面都是中文
![image](https://user-images.githubusercontent.com/22318220/79601856-c93a5500-80e9-11ea-8397-4f4b93f8d695.png)

**Comment by hustcc** [comment]
echarts 怎么设置英文？

**Comment by cx7388** [comment]
我在Vue-echarts的一个issue里看到可以强制使用 `langEN.js`，但我不知道如何在echarts-for-react里实现。
https://github.com/ecomfe/vue-echarts/issues/373#issuecomment-578371914

**Comment by hustcc** [comment]
```ts
toolbox: {
  show: true,
  feature: {
      mark: { show: true },
      magicType: { show: true, type: ["line", "bar"], title: {
        line: "Line",
        bar: "Bar",
      }
    },
    restore: { show: true, title: "Reset" },
    saveAsImage: { show: true, title: "Save as Image" }
  }
}
```

设置 options 中的 toolbox 配置，手动指定 title，用英文即可。
