### ISSUE TITLE
怎么connect多个echarts的图？

### ISSUE THREAD

**Issue by fengnex** [hustcc/echarts-for-react#353]
<ReactEcharts
  option={this.getOption()}
  style={{height: '300px', width: '100%'}}
  onEvents={onEvents} />
按上面这样的方式，如果开发了2个ReactEcharts，想调用echarts.init的对象把这2个图connect起来，也就是说，当鼠标放在任意一个图上时，另外一个图上相同横轴位置也显示对应的提示，这样方便不同图之间对比，但是这个效果在ReactEcharts上怎么实现呢？

**Comment by hustcc** [comment]
ref:

https://github.com/hustcc/echarts-for-react/blob/c191d484cb24f477e65dcc1abac7464305da08f8/demo/src/charts/Api.jsx#L94-L98
