### ISSUE TITLE
Resize not working on Safari desktop

### ISSUE THREAD

**Issue by thetylerwolf** [hustcc/echarts-for-react#354]
Works fine in Chrome, but not at all in Safari.

echarts version: 4.6.0
echarts-for-react version: 2.0.15-beta.1
react version: 16.12.0

**Comment by colinatdatasembly** [comment]
Also having this issue (same version of `echarts-for-react`). Charts are only resizing when their container height changes but not width. The `style` prop is set to `{height: "100%", width: "100%"}`).

**Comment by hustcc** [comment]
done v2.0.16

**Comment by dcantu96** [comment]
Hi I'm currently using `echarts-for-react version: 3.0.1` and I'm still having trouble with width resizing in safari. It does grow but it won't shrink.

**Comment by hustcc** [comment]
Give your version of safari.

**Comment by dcantu96** [comment]
> Give your version of safari.

https://github.com/hustcc/size-sensor/issues/15#issuecomment-815807523
