### ISSUE TITLE
Questions about the fourth Component API & Echarts API

### ISSUE THREAD

**Issue by zys555** [hustcc/echarts-for-react#356]
Does anyone know how to use this API? For example, to use dispatchAction in the API of Echarts through this API. I saw the way to write it in the example, but I didn't see where to write it.Is it the render function or something else?But I tried everything, and it was either BUG or no effect

**Comment by hustcc** [comment]
ref: https://github.com/hustcc/echarts-for-react/blob/c191d484cb24f477e65dcc1abac7464305da08f8/demo/src/charts/Api.jsx#L94-L98
