### ISSUE TITLE
When "datazoom" event updates the component state, it does not fired

### ISSUE THREAD

**Issue by e965** [hustcc/echarts-for-react#357]
Demo: https://codesandbox.io/s/vigilant-jones-wbv8o (try to make zoom or pinch, the chart is static)

When the state is eventually updated (this can be seen when the "Rezet zoom" button appears), event starts to work fine. I also tried to add an event listener via useEffect (on the chart instance), and via onChartReady (via `{echarts => echarts._api.on(...)}`), the result is same.

**Comment by hustcc** [comment]
You should update the option.dataZoom config.

**Comment by e965** [comment]
@hustcc can you please tell me exactly how?
