### ISSUE TITLE
support echarts global getInstanceByDom

### ISSUE THREAD

**Issue by aweibell** [hustcc/echarts-for-react#359]
It would be very nice to be able to get hold of a given ECharts instance by an ID, from anywhere in my application.

My use case is that I have a React/Redux application and want to be able to interact with the ECharts API from outside the component holding the chart. I'd like to store a short identificator in redux, which I could pick up elsewhere and use to get a reference to the ECharts instance object through calling a global function, like the `getInstanceByDom` function.

I could achieve this by being able to set an id on the ECharts DOM element, I guess. Then I could use `document.getElementById` to get the element and `getInstanceByDom` to get the instance?

Any suggestions on how to solve this with the existing library functionality is of course appreciated.

**Comment by aweibell** [comment]
I added this change locally yesterday, but it did not work. Even if I had the dom element, the `getInstanceByDom` did return `undefined`.

```
index 746c909..71d380d 100644
--- a/src/core.jsx
+++ b/src/core.jsx
@@ -22,7 +22,7 @@ export default class EchartsReactCore extends Component {
     if (typeof this.props.shouldSetOption === 'function' && !this.props.shouldSetOption(prevProps, this.props)) {
       return;
     }
-
+
     // 以下属性修改的时候，需要 dispose 之后再新建
     // 1. 切换 theme 的时候
     // 2. 修改 opts 的时候
@@ -140,6 +140,7 @@ export default class EchartsReactCore extends Component {
     // for render
     return (
       <div
+        id={this.props.chartId}
         ref={(e) => { this.echartsElement = e; }}
         style={newStyle}
         className={`echarts-for-react ${className}`}
@@ -150,6 +151,7 @@ export default class EchartsReactCore extends Component {

 EchartsReactCore.propTypes = {
   option: PropTypes.object.isRequired, // eslint-disable-line react/forbid-prop-types
+  chartId: PropTypes.string,
   echarts: PropTypes.object, // eslint-disable-line react/forbid-prop-types
   notMerge: PropTypes.bool,
   lazyUpdate: PropTypes.bool,
@@ -179,6 +181,7 @@ EchartsReactCore.propTypes = {
```

I also found that the global echarts library object had another method, `getInstanceById` which I assumed were expecting the `echarts_instance.id` as available through echarts-for-react as in the example code:

`let echarts_instance = this.echarts_react.getEchartsInstance();`

Even if I provided this id, the `getInstanceById` method returned `undefined`.

**Comment by hustcc** [comment]
```tsx
// cache all the instance on global
// then use redux key to get instance from cache
const cache = new Map();

class Test  {

  onRef = (n) => {
    // save instance into cache
    cache.set(randomKey, cache);

   // save randomKey in redux
  dispatch(....);
  }

   render() {
     return <EchartsReact { ... } ref={this.onRef}>;
  }
}
```

**Comment by aweibell** [comment]
Thanks, I assume you meant `cache.set(randomKey, n)` here. 

I'm not very satisfied with using `window` but it worked well for now! :)
