### ISSUE TITLE
散点地图默认mouseover方法，可否保留默认方法同时设置click方法？

### ISSUE THREAD

**Issue by RelaxLiu** [hustcc/echarts-for-react#36]
地图散点，鼠标移入弹出提示框，能否实现鼠标移入弹出提示框功能保留，并为散点添加点击事件，如果可以求设置方法。
感谢！！！
![image](https://cloud.githubusercontent.com/assets/16301089/23009256/d70c00cc-f44f-11e6-97d1-541140da944a.png)
如图点击原点进行下一步操作，求问点击事件添加方法

**Comment by hustcc** [comment]
本身的 echarts 就不支持鼠标移到 tooltip 里面做点击操作吧，如果实现需要这样的功能，可以去绑定 click 事件，然后自己弹出一个 dom 节点，在这个 dom 节点去做你要做的操作。

**Comment by RelaxLiu** [comment]
@hustcc 了解了，我尝试用其他方法解决吧，感谢！！！
