### ISSUE TITLE
Chart does not re-render when one of the series is removed

### ISSUE THREAD

**Issue by smihuc** [hustcc/echarts-for-react#362]
We are passing the series into our own custom `Chart` component which renders the `ReactEcharts` component. When you remove a series, the line stays on the chart. Our `Chart` component is re-rendering and passing the new series into `ReactEcharts`, but it is not re-rendering.

The only way to get the chart to render only the new data is to unmount & re-mount it.

I made this example to illustrate the problem: https://codesandbox.io/s/friendly-archimedes-vf2o0?file=/src/index.js
If you remove series, nothing changes on the chart even though the series are no longer being passed into `ReactEcharts`. If you unmount & re-mount the chart ("Toggle chart" button), then you'll see the right series.

This problem doesn't happen with Echarts itself, only with echarts-for-react.

To me at least, it seems that the root cause of this is that `ReactEcharts` does not re-render when the `option` prop is changed.

**Comment by fxxjdedd** [comment]
@smihuc 
add `notMerge` to ReactEcharts props should fix the problem.
 
notMerge: https://echarts.apache.org/zh/api.html#echartsInstance.setOption
