### ISSUE TITLE
How to reference chart instance

### ISSUE THREAD

**Issue by aweibell** [hustcc/echarts-for-react#363]
I am able to get a reference to the chart instance both by `onChartLoad` or by `ref` prop with `useRef`. However, when I zoom in the chart, and then call getOption() on those references,  the values are not updated. It seems I got a copy of the instance object?

Are there any recommended pattern for achieving interaction with the chart instance? I would like to set series data dynamically and user the updated datazoom values.

I would like for another component in my React application to be able to interact with the chart instance, i.e. need to pass the reference to parent/child components.

For datazoom I can use event listeners, but then there are different events for slider and inside, so it appears a little hacky.

**Comment by harrysoer** [comment]
have you tried accessing the `current` property first on the `ref` value?

**Comment by harrysoer** [comment]
Kinda frustrating that the `datazoom` event listener won't give me the complete parameters that I needed :( 
`
const onEvents =
  {
    datazoom: () => {
      if (ref.current) {
        const { startValue, endValue } = ref.current.getEchartsInstance().getOption().dataZoom[0]
        if (startValue && endValue) {
          console.log({
            startValue: moment(startValue).format(),
            endValue: moment(endValue).format()
          })
        }
      }
    },
  }`
