### ISSUE TITLE
datazoom event is not showing the "startValue" and "endValue" from the parameter

### ISSUE THREAD

**Issue by harrysoer** [hustcc/echarts-for-react#365]
from the [documentation](https://echarts.apache.org/en/api.html#events.datazoom) there's an option that you can access the `startValue` and `endValue` but from the `onEvent` prop but it only returns these properties
```
dataZoomId: "series00"
end: 100
from: "viewComponent_186_0.83586"
start: 0.12926577042399176
type: "datazoom"
```

The only way I could retrieve the `startValue` and `endValue` in a hassle way is that I have to create a `useRef()` for the ReactCharts component and retrieve those value from `getEchartsInstance()`
e.g.

```
  const onEvents = {
    datazoom: () => {
      if (ref.current) {
        const { startValue, endValue } = ref.current.getEchartsInstance().getOption().dataZoom[0]
        if (startValue && endValue) {
          console.log({
            startValue: moment(startValue).format(),
            endValue: moment(endValue).format()
          })
        }
      }
    },
  }
```

**Comment by hustcc** [comment]
send issue in echarts.
