### ISSUE TITLE
Get `Uncaught TypeError: Cannot read property 'getDisplayList' of null` warning

### ISSUE THREAD

**Issue by baurine** [hustcc/echarts-for-react#366]
Hi,

After adding the `onEvents` prop to `ReactEchartsCore` component, I always get the `Uncaught TypeError: Cannot read property 'getDisplayList' of null` warning in the browser console when clicking the legend. I tried but failed to find the root cause, do you have any idea? Thanks in advance.

The core code:

```jsx
  const [selectedLegends, setSelectedLegends] = useState({})

  const handleLegendChange = ({ name, selected }) => {
    setSelectedLegends(selected)
  }

  const opt = useMemo(() => {
    ...
    legend: {
      ...
      selected: selectedLegends
    ...
  )

      <ReactEchartsCore
        echarts={echarts}
        notMerge={true}
        lazyUpdate={true}
        style={{ height: HEIGHT }}
        option={opt}
        theme={'light'}
        onEvents={{ legendselectchanged: handleLegendChange }}
      />
```

The details are in here: https://github.com/pingcap-incubator/tidb-dashboard/pull/663/commits/886875f3e87b2e2af01dab968c561a0f57c25d13 , related PR: https://github.com/pingcap-incubator/tidb-dashboard/pull/663

The warning screenshot:

![image](https://user-images.githubusercontent.com/1284531/86111541-73c2f100-baf9-11ea-835a-6fb3ef5453e2.png)

**Comment by Emma-yuan** [comment]
请问您解决了吗？我也遇到了相同问题

**Comment by baurine** [comment]
> 请问您解决了吗？我也遇到了相同问题

Nope. But I found change `notMerge` props to its default value `false` can help me remove the `onEvents` props in the above case.

**Comment by xiyanfeixu** [comment]
I have changed notMerge to false ,but still have warnings like the above case.

**Comment by findxc** [comment]
I find that if you call setState in onEvents listener, the error occurs. Maybe the error has something to do with the React re-render.

```js
const onLegendSelected = () => {
  // the setCount triggers React re-render, when you click lengend, the error occurs
  setCount(c => c + 1);
};

const onEvents = {
  legendselectchanged: onLegendSelected,
};
```  

version: echarts: 4, echarts-for-react: ^2.0.16

**Comment by dolimovkhumoyun** [comment]
Has anyone found solution for this issue?
@hustcc

**Comment by hustcc** [comment]
Can someone give me a live demo?

**Comment by findxc** [comment]
@hustcc https://codesandbox.io/s/echarts-for-react-issues-366-ru14m

**Comment by hustcc** [comment]
@findxc  in FC, set onLegendSelected in memo, keep the function with same ref.

**Comment by findxc** [comment]
I have updated my demo https://codesandbox.io/s/echarts-for-react-issues-366-ru14m , and it can work now ✌️✌️✌️. The key point is to wrap your event listeners with useMemo or useCallback.

```js
const onLegendSelected = useCallback((params) => {
  const { selected } = params
  setSelected(selected)
}, [])
```

Many thanks to hustcc 👍👍👍

**Comment by WhoAteDaCake** [comment]
I've changed to using `legendselected` instead of `legendselectchanged` and it stopped crashing
