### ISSUE TITLE
能否支持rem 布局

### ISSUE THREAD

**Issue by ycshill** [hustcc/echarts-for-react#368]
我用了  postcss-px-to-rem  在项目中，但是咱的组件不能适用， 只能是px的布局，这样在数据大屏的时候样式会有问题，能否支持 postcss-px-to-rem

**Comment by baxtergu** [comment]
可能需要引入[postcss-js](https://github.com/postcss/postcss-js)，如果只用postcss的话是不会对css-in-js这种方式生效的

**Comment by hustcc** [comment]
可以使用 class name 传入，不传入 style 的方式，然后在外部通过  class name  去控制样式。这样和原生 html css 逻辑是一致的。
