### ISSUE TITLE
stillShowZeroSum属性失效

### ISSUE THREAD

**Issue by RelaxLiu** [hustcc/echarts-for-react#37]
在react环境下，饼图值为零时想设置饼图不显示，可是总是失效，在官网demo下实验好用，移到项目中就失效，不知道为什么，求大神指点！！！

**Comment by hustcc** [comment]
可以大概贴一下你的代码吗？

**Comment by RelaxLiu** [comment]
series: [
        {
          name:'睡眠时长',
          type:'pie',
         //  为true或者为false结果一样，数据为零时饼图不消失
          stillShowZeroSum: false,
          radius: ['60%', '70%'],
          avoidLabelOverlap: false,
          label: {
            normal: {
              show: false,
              position: 'center'
            },
            emphasis: {
              show: true,
              textStyle: {
                fontSize: '30',
                fontWeight: 'bold'
              }
            }
          },
          labelLine: {
            normal: {
              show: false
            }
          },
          data:[
            {
              value:$this.state.SleepLong._12_24, 
              name:'> 12'
            },
            {
              value:$this.state.SleepLong._10_12, 
              name:'10-12'
            },
            {
              value:$this.state.SleepLong._8_10, 
              name:'8-10'
            },
            {
              value:$this.state.SleepLong._6_8, 
              name:'6-8'
            },
            {
              value:$this.state.SleepLong._0_6, 
              name:'< 6'
            }
          ]
        }
      ]



我在segmentfault上也提问了
https://segmentfault.com/q/1010000008457261

**Comment by hustcc** [comment]
目测有可能是 echarts 版本的原因。

`echarts-for-react` 使用的是 "echarts": "^3.1.1".

**Comment by RelaxLiu** [comment]
@hustcc 我这边的版本是3.3.2，我在琢磨琢磨，麻烦啦！！！

**Comment by hustcc** [comment]
嗯，我这边也是时候升级一下了。

**Comment by RelaxLiu** [comment]
@hustcc 感谢，我努力成长，你们这样的大神是我的榜样！！！！
