### ISSUE TITLE
map areaColor doesn't work!

### ISSUE THREAD

**Issue by nanqiaoYue** [hustcc/echarts-for-react#370]
Recently, I set areaColor while using a 3D Map, but it didn't work. 
**version:**
"echarts": "^4.8.0",
 "echarts-for-react": "^2.0.16",
 "echarts-gl": "^1.1.1",

**The code is as follows:**
```
geo3D: {
   map: 'china',
   roam: true,
   itemStyle: {
      areaColor: '#1d5e98', // 蓝色，地图每个区域颜色
      opacity: 1,
      borderWidth: 0.4,
      borderColor: '#000'
   },
   label: {
      show: true,
      textStyle: {
         color: '#000', // 地图初始化区域字体颜色
         fontSize: 8,
         opacity: 1,
         backgroundColor: 'rgba(0,23,11,0)'
      },
   },
   ......
}
```
**The specific effects are as follows:**
![image](https://user-images.githubusercontent.com/31209616/87266961-fe8fec80-c4f8-11ea-8b5c-31fb632db2b1.png)

I don't know if it's a version issue or else? Looking forward to your reply! Thank you!

**Comment by hustcc** [comment]
send issue on echarts.

**Comment by wuhao930406** [comment]
map3D时 onEvents 下的 click方法在无法调用

**Comment by nanqiaoYue** [comment]
您好，您的邮件已收到。我会尽快查看，给您回复。
