### ISSUE TITLE
echarts-for-react only support echarts v3.0 & 4.0?

### ISSUE THREAD

**Issue by Lijiaoa** [hustcc/echarts-for-react#371]
I use echarts `v4.5.0` and the echarts-for-react `2.0.15-beta.1` to develop. Echarts had a bug fix in v4.4.0. But it didn't help in my environment. 

So echarts-for-react could support echarts ^v4.4.0?

for this [issue](https://github.com/apache/incubator-echarts/issues/11101): support NaN data

**Comment by zevero** [comment]
I tried it with v5.0.0-alpha.2 
I can not run it because of
`Attempted import error: '__spreadArrays' is not exported from 'tslib'.`

Did not investigate further, but it would be nice for echarts-for-react to support v5.0 as soon as possible!

**Comment by Lijiaoa** [comment]
@zevero  seems like this repo is not maintain

**Comment by hustcc** [comment]
https://github.com/hustcc/echarts-for-react/issues/388

3.0.0-beta.1 released, echarts v5 supported.

**Comment by hustcc** [comment]
> I use echarts `v4.5.0` and the echarts-for-react `2.0.15-beta.1` to develop. Echarts had a bug fix in v4.4.0. But it didn't help in my environment.
> 
> So echarts-for-react could support echarts ^v4.4.0?
> 
> for this [issue](https://github.com/apache/incubator-echarts/issues/11101): support NaN data

the version is control by yourself. the repo only point v3 | v4.
