### ISSUE TITLE
刷新数据后，老数据和新数据都显示在图表中

### ISSUE THREAD

**Issue by ZGZGK1002** [hustcc/echarts-for-react#373]
昨天在开发图标时，发现当更新数据后，新数据和老数据会都显示在图表中。最后通过修改源码解决了该问题。在源码的renderEchartDom方法中添加echartObj.clear()；解决问题。

**Comment by liuhui666** [comment]
没错，render之前没有clear会有问题
而且手动调用echartInstance.clear后，如果option不发生变化，不会重新render

**Comment by PipiHua** [comment]
为什么这个取到的实例没有clear方法呢？郁闷

**Comment by Lisianthus-A** [comment]
遇到了同样的问题，我是通过手动setOption解决的

**Comment by lifuzhao100** [comment]
正确方式不应该是手动调用clear，而是在props中传入notMerge，https://echarts.apache.org/zh/api.html#echartsInstance.setOption 中，setOption支持传入三个参数，option, notMerge，lazyUpdate，其中notMerge为true表示不会合并旧的数据

**Comment by hustcc** [comment]
notMerge配置。

**Comment by gujiwuqing** [comment]
notMerge配置 但是还是没有作用 有选择七天 30天的数据 然后快速点击切换则会出现两个数据在一起的情况
