### ISSUE TITLE
option 变化后的 dispose 操作导致百度地图闪烁

### ISSUE THREAD

**Issue by tonyzhou1890** [hustcc/echarts-for-react#379]
echarts master 分支对百度地图扩展的渲染机制进行了修改（extension-src/bmap/BMapCoordSys.js）：
![image](https://user-images.githubusercontent.com/15159550/91109955-125d6f80-e6af-11ea-9654-11a3e34e000e.png)
当 center 和 zoom 不变的情况下，不重绘百度地图。这样可以避免闪烁以及额外的开销。
而 echarts-for-react 在 option 变化后会先 dispose ，然后重绘。这会导致闪烁问题依然存在。希望后续版本中修改一下。
![image](https://user-images.githubusercontent.com/15159550/91110196-a4fe0e80-e6af-11ea-902d-e83391499a65.png)

**Comment by hustcc** [comment]
只有那三个配置才回 dispose，其他配置不会。不然也没法生效。
