### ISSUE TITLE
词云热点分析

### ISSUE THREAD

**Issue by gsnwwolf** [hustcc/echarts-for-react#38]
百度词云这个chart渲染不出来

http://gallery.echartsjs.com/editor.html?c=xBJ11Hguze
option = {
    title: {
        text: '热点分析',
        link: 'https://www.baidu.com/s?wd=' + encodeURIComponent('ECharts'),
        x: 'center',
        textStyle: {
            fontSize: 23
        }

    },
    backgroundColor: '#F7F7F7',
    tooltip: {
        show: true
    },
    toolbox: {
        feature: {
            saveAsImage: {
                iconStyle: {
                    normal: {
                        color: '#FFFFFF'
                    }
                }
            }
        }
    },
    series: [{
        name: '热点分析',
        type: 'wordCloud',
        //size: ['9%', '99%'],
        sizeRange: [6, 66],
        //textRotation: [0, 45, 90, -45],
        rotationRange: [-45, 90],
        //shape: 'circle',
        textPadding: 0,
        autoSize: {
            enable: true,
            minSize: 6
        },
        textStyle: {
            normal: {
                color: function() {
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')';
                }
            },
            emphasis: {
                shadowBlur: 10,
                shadowColor: '#333'
            }
        },
        data: [{
            name: "Jayfee",
            value: 666
        }, {
            name: "Nancy",
            value: 520
        }]
    }]
};

//myChart.setOption(option);
myChart.on('click', function(params) {
    //alert((params.name));
    window.open('https://www.baidu.com/s?wd=' + encodeURIComponent(params.name));

});

**Comment by hustcc** [comment]
你的代码是怎么写的？

**Comment by gsnwwolf** [comment]
import React from 'react';
import ReactEcharts from 'echarts-for-react';
/**
 * 关键词分析-词云图
 */
class PromKeyWordCloudsCardRateChart extends React.Component {

    constructor(props) {
        super(props);
        this.getChartOption = this.getChartOption.bind(this);
    }

    getChartOption() {
        const {cloudsCardRateData} = this.props;
        let seriesData = [];
        cloudsCardRateData.map(opt=> {
            let obj = {
                name: opt.get('d_promotion_ad_keyword'),
                value: opt.get('m_create_card_rate')
            };
            seriesData.push(obj);
        });
        const option = {
            title: {
                text: '词云图',
                x: 'center',
                textStyle: {
                    fontSize: 23
                }
            },
            backgroundColor: '#F7F7F7',
            tooltip: {
                show: true
            },
            toolbox: {
                feature: {
                    saveAsImage: {
                        iconStyle: {
                            normal: {
                                color: '#FFFFFF'
                            }
                        }
                    }
                }
            },
            series: [{
                name: '词云图',
                type: 'wordCloud',
                sizeRange: [6, 66],
                rotationRange: [-45, 90],
                textPadding: 0,
                autoSize: {
                    enable: true,
                    minSize: 6
                },
                textStyle: {
                    normal: {
                        color: function () {
                            return 'rgb(' + [
                                    Math.round(Math.random() * 160),
                                    Math.round(Math.random() * 160),
                                    Math.round(Math.random() * 160)
                                ].join(',') + ')';
                        }
                    },
                    emphasis: {
                        shadowBlur: 10,
                        shadowColor: '#333'
                    }
                },
                data: [{
                    name: "Jayfee",
                    value: 666
                }, {
                    name: "Nancy",
                    value: 520
                }, {
                    name: "Nancy",
                    value: 120
                }]
            }]
        };
        return option;
    }

    render() {
        return (
            <ReactEcharts
                style={{height: '300px', width: '100%',float:'left',marginBottom:20}}
                option={this.getChartOption()}/>
        );
    }
}
export default PromKeyWordCloudsCardRateChart;

**Comment by gsnwwolf** [comment]
浏览器控制台显示：
 Uncaught Error: Component series.wordCloud not exists. Load it first.entity.getClass @ clazz.js?3e66:165(anonymous function) @ Global.js?b9d3:195each @ util.js?10f4:260visitComponent @ Global.js?b9d3:178entity.topologicalTravel @ component.js?cc72:89Model.extend.mergeOption @ Global.js?b9d3:147initBase @ Global.js?b9d3:633Model.extend.resetOption @ Global.js?b9d3:92Model.extend.setOption @ Global.js?b9d3:74echartsProto.setOption @ echarts.js?68a2:283renderEchartDom @ echarts-for-react.js?d937:81ReactEcharts_componentDidMount @ echarts-for-react.js?d937:33(anonymous function) @ ReactCompositeComponent.js?d2b3:265measureLifeCyclePerf @ ReactCompositeComponent.js?d2b3:75(anonymous function) @ ReactCompositeComponent.js?d2b3:264notifyAll @ CallbackQueue.js?f006:76ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js?ba2e:80TransactionImpl.closeAll @ Transaction.js?f15f:206TransactionImpl.perform @ Transaction.js?f15f:153TransactionImpl.perform @ Transaction.js?f15f:140_assign.perform @ ReactUpdates.js?8e6b:89flushBatchedUpdates @ ReactUpdates.js?8e6b:172TransactionImpl.closeAll @ Transaction.js?f15f:206TransactionImpl.perform @ Transaction.js?f15f:153ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js?e9be:62batchedUpdates @ ReactUpdates.js?8e6b:97ReactEventListener.dispatchEvent @ ReactEventListener.js?944f:147

**Comment by hustcc** [comment]
需要外部引入 wordCloud 这个 js 文件…
