### ISSUE TITLE
Tooltip doesn't display

### ISSUE THREAD

**Issue by arpitashekhar** [hustcc/echarts-for-react#386]
I am using echarts v^4.2.1 and echarts-for-react v2.0.16, the tooltip doesn't display even after setting the following options:
```
tooltip: {
    trigger: "item",
    show: true,
    triggerOn: "mousemove",
    alwaysShowContent: false,
  }
```

Also tried setting `series.data.tooltip` for individual items, that doesn't work either.

**Comment by NeroMorto** [comment]
@arpitashekhar Hi! Can you provide a live code example?
