### ISSUE TITLE
Update Chart to Remove Line

### ISSUE THREAD

**Issue by parabuzzle** [hustcc/echarts-for-react#387]
I'm calling the component like this: 

```
<ReactEcharts
            option={this.chartOptions()}
            style={{ height: '350px', width: '100%' }}
            className="react_for_echarts"
            showLoading={this.state.loading}
          />
```

My Chart Options has a single series initially.

When I click a button on my page I add another line series to the chartoptions and it draws the extra line on the chart properly. 

When I click it again, it removes that series from the chartoptions but the line remains on the chart. 

Is there a way to force the chart to redraw on any change to the chartoptions?

**Comment by NeroMorto** [comment]
@parabuzzle Hi! Can you provide a code example on codepen or something else? I'll try to help you.

**Comment by hyh123a** [comment]
import "echarts/lib/chart/bar";

Msybe it is ok when you use line type.
