### ISSUE TITLE
feat: please support echarts v5.0

### ISSUE THREAD

**Issue by dongliutony** [hustcc/echarts-for-react#388]
I encountered below errors when updated echarts to v5.0:

System complains that it cannot find below functions, such as getInstanceByDom().

var EchartsReactCore = function (_Component) {
  _inherits(EchartsReactCore, _Component);

  function EchartsReactCore(props) {
    _classCallCheck(this, EchartsReactCore);

    var _this = _possibleConstructorReturn(this, (EchartsReactCore.__proto__ || Object.getPrototypeOf(EchartsReactCore)).call(this, props));

    _this.getEchartsInstance = function () {
      return _this.echartsLib.getInstanceByDom(_this.echartsElement) || _this.echartsLib.init(_this.echartsElement, _this.props.theme, _this.props.opts);
    };

    _this.dispose = function () {
      if (_this.echartsElement) {
        try {
          (0, _sizeSensor.clear)(_this.echartsElement);
        } catch (e) {
          console.warn(e);
        }
        // dispose echarts instance
        _this.echartsLib.dispose(_this.echartsElement);
      }
    };

**Comment by hustcc** [comment]
can helpto give us a pr

**Comment by zachsa** [comment]
Ahh. I am getting the same issue. Will have to rollback to echarts 4 for now

**Comment by yifans** [comment]
I am also getting the same issue and rollback to V4. V5 offers lots of new features, looking forward the update to support V5~

**Comment by theDoinb** [comment]
+1

**Comment by thetylerwolf** [comment]
This library has been great. Would be even greater with echarts 5!

+1

**Comment by hustcc** [comment]
最近两周看看。

I will finish v5 in 2 weeks, has anyone want to contribute?

**Comment by zachsa** [comment]
I would be interested in taking a look early January. I'm not sure what needs to change though?

**Comment by hustcc** [comment]
[v3](https://github.com/hustcc/echarts-for-react/tree/v3) is on the way.

**Comment by glaucopater** [comment]
> 最近两周看看。
> 
> I will finish v5 in 2 weeks, has anyone want to contribute?

I do, how can I help?

**Comment by hustcc** [comment]
> > 最近两周看看。
> 
> > 
> 
> > I will finish v5 in 2 weeks, has anyone want to contribute?
> 
> 
> 
> I do, how can I help?

Help me to write the website and demo on v3 branch.

**Comment by greatbear412** [comment]
> > > 最近两周看看。
> > 
> > 
> > > 
> > 
> > 
> > > I will finish v5 in 2 weeks, has anyone want to contribute?
> > 
> > 
> > I do, how can I help?
> 
> Help me to write the website and demo on v3 branch.

详细说说.
Willing to help.

**Comment by pedroviniv** [comment]
Thank you very much for building such a great lib, I've been using a lot in my projects!
any progress in this feature? is there anything I could help? I'm really excited to see this working with echarts 5.0,
this version has enhancements in label overlapping problemas

**Comment by xingangsun** [comment]
@hustcc 既然是react，考虑支持一下 hooks？

**Comment by pissang** [comment]
@dongliutony Hi, it seems this error is similar to https://github.com/apache/echarts/issues/13701. If so, it has been fixed in https://github.com/apache/echarts/pull/13890 and will be included in the coming 5.0.1 which will be released this week.

**Comment by Veigar-C** [comment]
这个月能出个版本吗？图表一多，resize 和 id create 写到头皮发麻

**Comment by dmozzoni** [comment]
The newer echarts changed how it gets exported. I hand edited the index.js in the lib folder to get echarts 5 to work. I'm sure there is a better way though.

If you replace line 33 in the echarts-for-react/lib/index.js:
    _this.echartsLib = _echarts2['default'];
with:
    _this.echartsLib = _echarts2['default'] || _echarts2 ;

**Comment by hsluoyz** [comment]
Any progress?

**Comment by ISBN9527** [comment]
The latest progress ?

**Comment by zhenzhenmao** [comment]
> > > > 最近两周看看。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I will finish v5 in 2 weeks, has anyone want to contribute?
> > > 
> > > 
> > > I do, how can I help?
> > 
> > 
> > Help me to write the website and demo on v3 branch.
> 
> 详细说说.
> Willing to help.



> > > 最近两周看看。
> > 
> > 
> > > 
> > 
> > 
> > > I will finish v5 in 2 weeks, has anyone want to contribute?
> > 
> > 
> > I do, how can I help?
> 
> Help me to write the website and demo on v3 branch.

已经修复了么，没有修复的话，我愿意帮忙

**Comment by Braffolk** [comment]
Any update on this?

**Comment by jrdzha** [comment]
Also curious if there is any update here? Perhaps a PR we can take a look at?

**Comment by hustcc** [comment]
Sorry, I'm very busy these days. I have to deal with it during the Spring Festival.

Set up a flag  🚩 before 02-18, I will release a beta version.

**Comment by hustcc** [comment]
> Sorry, I'm very busy these days. I have to deal with it during the Spring Festival.
> 
> > Set up a flag  🚩 before 02-18, I will release a beta version.


```
+ echarts-for-react@3.0.0-beta.1
```

beta.1 is released, have a try! after Spring Festival, will release stable.

**Comment by neilharrisbrown** [comment]
Nice work - thanks!
