### ISSUE TITLE
 Unknown prop `option` 

### ISSUE THREAD

**Issue by shangxinbo** [hustcc/echarts-for-react#39]
按照示例在图表组件上使用option属性会报错
code
```
import chart from 'echarts-for-react'
……
<chart styleName="chart-warp" option={this.state.option}></chart>
```
error
``` 
Unknown prop `option` on <chart> tag. Remove this prop from the element
```

**Comment by hustcc** [comment]
试试看下面这么引入会有问题吗？

```js
import ReactEcharts from 'echarts-for-react';
```

**Comment by shangxinbo** [comment]
用ReactEcharts没有问题   ……  ……

**Comment by shangxinbo** [comment]
这么做好么

**Comment by hustcc** [comment]
嗯，应该是一个 bug，感觉是 default export 的问题。**也有可能是你代码中 chart 被重写了。**

我抽时间测试一下。

**Comment by shangxinbo** [comment]
我找到原因了 https://facebook.github.io/react/warnings/unknown-prop.html
**You are using a React component without an upper case. React interprets it as a DOM tag because React JSX transform uses the upper vs. lower case convention to distinguish between user-defined components and DOM tags.**
因为我的组件如果命名成chart的话，react认为这是一个普通的dom元素，并不会使用jsx编译
所以，应该使用大写字幕开头的组件
谢谢
