### ISSUE TITLE
layout.global.error.title

### ISSUE THREAD

**Issue by wJianX** [hustcc/echarts-for-react#390]
ant-design-pro5

"echarts": "^5.0.0",
"echarts-for-react": "^2.0.16",
报
layout.global.error.title
TypeError: Cannot read property 'dispose' of undefined  啥问题

**Comment by zys555** [comment]
目前这个不支持echarts5.0自己下一个4.9版本的echarts

**Comment by hustcc** [comment]
https://github.com/hustcc/echarts-for-react/issues/388

Supported.
