### ISSUE TITLE
报错Cannot read property 'getInstanceByDom' of undefined

### ISSUE THREAD

**Issue by TangTangJia** [hustcc/echarts-for-react#399]
具体代码如下：
`import React, { useState, useEffect } from 'react';
import ReactEcharts from "echarts-for-react";

export default function Total() {
  const getOption = () => {
    return {
      title: {
        text: '折线图堆叠'
      },
      tooltip: {
        trigger: 'axis'
      },
      legend: {
        data: ['邮件营销', '联盟广告', '视频广告', '直接访问', '搜索引擎']
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      toolbox: {
        feature: {
          saveAsImage: {}
        }
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
      },
      yAxis: {
        type: 'value'
      },
      series: [
        {
          name: '邮件营销',
          type: 'line',
          stack: '总量',
          data: [120, 132, 101, 134, 90, 230, 210]
        },
        {
          name: '联盟广告',
          type: 'line',
          stack: '总量',
          data: [220, 182, 191, 234, 290, 330, 310]
        },
        {
          name: '视频广告',
          type: 'line',
          stack: '总量',
          data: [150, 232, 201, 154, 190, 330, 410]
        },
        {
          name: '直接访问',
          type: 'line',
          stack: '总量',
          data: [320, 332, 301, 334, 390, 330, 320]
        },
        {
          name: '搜索引擎',
          type: 'line',
          stack: '总量',
          data: [820, 932, 901, 934, 1290, 1330, 1320]
        }
      ]
    };
  }
  return (
      <div>
        <ReactEcharts
          option={getOption()}
          style={{ height: '600px', width: '100%' }}
        />
      </div>
  )
}
`

报错信息：
![image](https://user-images.githubusercontent.com/34622385/103498777-d1f1d780-4e80-11eb-94ca-c234781bc935.png)

**Comment by findxc** [comment]
@TangTangJia 你是不是用的 echart v5 的版本？用 echart v4 就不会有这个报错了

**Comment by TangTangJia** [comment]
> @TangTangJia 你是不是用的 echart v5 的版本？用 echart v4 就不会有这个报错了

谢谢回复，果然是版本问题

**Comment by superlbr** [comment]
v5肿么办 @hustcc

**Comment by hustcc** [comment]
> v5肿么办 @hustcc 

3.0.0 试试看。

**Comment by superlbr** [comment]
@hustcc 不行。。。

**Comment by hustcc** [comment]
求提供一个 live demo~ @superlbr

**Comment by superlbr** [comment]
@hustcc 
是写法的问题，v5的写法变了。。。

**Comment by superlbr** [comment]
@hustcc 
xAxis "0" not found 这又是啥，数据格式也变了？

**Comment by superlbr** [comment]
@hustcc live demo https://codesandbox.io/s/compassionate-wilbur-2ljns?file=/App.tsx

**Comment by hustcc** [comment]
先排查是不是 echarts写错了，在echarts官网试试这个写法。

**Comment by superlbr** [comment]
@hustcc option代入echarts官网示例是OK的，不按需引入是OK的，按需引入的写法是参考ReadMe

**Comment by superlbr** [comment]
@hustcc 查到了DatasetComponent这个组件也要引入

**Comment by superlbr** [comment]
@hustcc 是缺GridComponent

**Comment by superlbr** [comment]
@hustcc 建议更新下README

**Comment by hustcc** [comment]
> @hustcc 建议更新下README

来一个 pr 吧~~

**Comment by superlbr** [comment]
@hustcc done https://github.com/hustcc/echarts-for-react/pull/414
