### ISSUE TITLE
what if I want to use map. any demo?

### ISSUE THREAD

**Issue by ZhengHe-MD** [hustcc/echarts-for-react#4]

**Comment by hustcc** [comment]
参考这个[demo](http://echarts.baidu.com/demo.html#geo-lines)，编写option，然后赋值到Echarts中应该就可以了，我周时间写一个live demo。

**Comment by Korbin-Wang** [comment]
使用这个component，提示no china map exits，按example方式导入china.js，不work。 能提供具体导入china map的方法么？

**Comment by walter211** [comment]
什么时候出RN版本

**Comment by hustcc** [comment]
@Korbin-Wang @ZhengHe-MD 周末我抽空在live demo中加一个china map的例子。

@walter211 react-native自己并没有用过，工作项目中也没有涉及，所以可能暂时没有打算，如果你有想法，可以PR代码，或者自己另开项目^_^~

**Comment by hustcc** [comment]
@Korbin-Wang @ZhengHe-MD 已经增加一个[China map的demo](http://git.hust.cc/echarts-for-react/#/echarts/map?_k=esrh93)，好像就是require一些China.js就可以了。

代码在这里：[https://github.com/hustcc/echarts-for-react/blob/master/demo/MapChartComponent.jsx](https://github.com/hustcc/echarts-for-react/blob/master/demo/MapChartComponent.jsx)
