### ISSUE TITLE
请问怎么添加单击事件

### ISSUE THREAD

**Issue by Pehfan** [hustcc/echarts-for-react#40]
我要给折线图上的每个点添加单击事件，请问该如何做呢？

**Comment by hustcc** [comment]
两种方法：

1. 使用这个库的 api 就可以获取 echarts 的实例，然后后面就和 echarts 的使用类似。
2. 使用 `onEvents` 属性，直接传入点击事件就可以了。

**Comment by Pehfan** [comment]
那么请问通过哪个api呢，这个库好像没有api文档吧？

**Comment by hustcc** [comment]
就是 README 文件中有描述：[4. Component API & Echarts API](https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api).

具体 API 名字为 `getEchartsInstance()`。

**Comment by Pehfan** [comment]
非常感谢，完美解决。
