### ISSUE TITLE
建议增加获取原生echarts 的api用以调用echarts.util等api

### ISSUE THREAD

**Issue by Virtycle** [hustcc/echarts-for-react#400]
建议增加获取原生echarts 的api用以调用echarts.util等api，import echarts from 'echarts'; 的方式如果项目里装了其他版本的echarts容易有问题， 另外建议 库里的echarts版本不要写死

**Comment by hustcc** [comment]
Echarts方法自己业务引入使用。本项目并没有限制版本。
