### ISSUE TITLE
Error 'setoption' should not be called during main process

### ISSUE THREAD

**Issue by vortesnail** [hustcc/echarts-for-react#402]
作者你好，在使用 echarts-for-react 时切换路由时，数据渲染过于频繁时会出现以下报错：

`Error 'setoption' should not be called during main process` 

经过查询，解决方案是在 `setOption` 之前调用一次实例的 `.clear()` 即可，或者采用定时器延迟 `.setOption` 。

但是通过阅读作者的源码后发现没有这样的钩子，可否简单加一下这样的钩子呢？

辛苦～

**Comment by vortesnail** [comment]
比如提供以下属性：
```diff
  // render the dom
  renderEchartDom = () => {
    // init the echart object
    const echartObj = this.getEchartsInstance();
    // set the echart option
+   if (this.props.clearBeforeSetOption) {
+     echartObj.clear();
+   }
    echartObj.setOption(this.props.option, this.props.notMerge || false, this.props.lazyUpdate || false);
    // set loading mask
    if (this.props.showLoading) echartObj.showLoading(this.props.loadingOption || null);
    else echartObj.hideLoading();

    return echartObj;
  };
```

**Comment by hustcc** [comment]
感觉 setOption 之前需要调用 clear 算是 echarts 的 bug 吧，看看是否 echarts 中有相关 issue？

如果官方建议这么处理的话，就在这里加上这样的配置项吧！

**Comment by sthenault** [comment]
Sorry I do not understand but I'm having the same error on component resizing, which is pretty annoying. The suggested patch doesn't seems to do the trick in may case.

Would be interested in any follow-up, thx.

**Comment by makeupsomething** [comment]
We are also getting this error. Is there any suggested fix?

**Comment by vortesnail** [comment]
> We are also getting this error. Is there any suggested fix?

Maybe you should fork this repo, and add a `settimout` function to explore it.

**Comment by hustcc** [comment]
I think this is an issue of echarts, we should fix it echarts, instead of patching.

@vortesnail @makeupsomething @sthenault

**Comment by hustcc** [comment]
@pissang Take a look at this issue?

**Comment by pissang** [comment]
I'm not sure but it usually happens when having errors during update, which is a synchronized process. Use a disposed instance may also have this kind of issue. Of course it will help us a lot if there is a reproducible demo:)

**Comment by pissang** [comment]
@sthenault Thanks for the information. This is a known bug of echarts and already been planned in version 5.1.1. Which will be released next month.

**Comment by sthenault** [comment]
@pissang, good to know, thx!

**Comment by hustcc** [comment]
Closed it
