### ISSUE TITLE
Error when try to use modules imports

### ISSUE THREAD

**Issue by coolswood** [hustcc/echarts-for-react#406]
Everything works fine when I import the entire echarts library. But if I import modules I get the following error.
<img width="421" alt="Снимок экрана 2021-02-10 в 22 25 58" src="https://user-images.githubusercontent.com/25247802/107568009-17779200-6bef-11eb-891a-0db8f8c7b9b9.png">

code:
```
<ReactEchartsCore
        echarts={echarts}
        option={{
          xAxis: {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
          },
          yAxis: {
            type: 'value',
          },
          series: [
            {
              data: [150, 230, 224, 218, 135, 147, 260],
              type: 'line',
            },
          ],
        }}
        style={{ height: '200px' }}
        notMerge={true}
      />
```
`"echarts": "^5.0.2"`
`"echarts-for-react": "^3.0.0-beta.2"`

**Comment by ieltxualganaras** [comment]
can this be related to this? 
I think that esm/index.js is not importing echarts correctly,
it says:
import * as echarts from 'echarts';
and it should be:
import * as echarts from 'echarts/core';

is this something that you intend to push to npm soon?

**Comment by coolswood** [comment]
@hustcc can you please tell me when you can return to the project?

**Comment by hustcc** [comment]
> @hustcc can you please tell me when you can return to the project?

what is your problem？

**Comment by coolswood** [comment]
@hustcc I can't resolve the error I described above. It seems I did everything as it is said in the documentation, but the modular imports do not work

**Comment by sjfkai** [comment]
Try the following code from [echars tutorial](https://echarts.apache.org/en/tutorial.html#Use%20ECharts%20with%20bundler%20and%20NPM)
```js
import * as echarts from 'echarts/core';
import {
    BarChart,
    // The series types are defined with the SeriesOption suffix
    BarSeriesOption,
    LineChart,
    LineSeriesOption
} from 'echarts/charts';
import {
    TitleComponent,
    // The component types are defined with the suffix ComponentOption
    TitleComponentOption,
    GridComponent,
    GridComponentOption
} from 'echarts/components';
import {
    CanvasRenderer
} from 'echarts/renderers';

// Combine an Option type with only required components and charts via ComposeOption
type ECOption = echarts.ComposeOption<
  BarSeriesOption | LineSeriesOption | TitleComponentOption | GridComponentOption
>;

// Register the required components
echarts.use(
    [TitleComponent, TooltipComponent, GridComponent, BarChart, CanvasRenderer]
);
```

Then

```jsx
    <ReactEchartsCore
        echarts={echarts}
        option={{
          xAxis: {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
          },
          yAxis: {
            type: 'value',
          },
          series: [
            {
              data: [150, 230, 224, 218, 135, 147, 260],
              type: 'line',
            },
          ],
        }}
        style={{ height: '200px' }}
        notMerge={true}
      />
```

**Comment by coolswood** [comment]
@sjfkai It works perfectly, thank you! Apparently it is necessary to update the documentation of echarts-for-react, because here the deprecated import method is described

**Comment by hustcc** [comment]
@sjfkai can help to give me a pr？

**Comment by coolswood** [comment]
@hustcc I'll try to do it tonight

**Comment by sjfkai** [comment]
> @sjfkai @coolswood can help to give me a pr？

I have made this. #407 Have a see  guys.
