### ISSUE TITLE
echarts在Tab面也切换时,只有第一次进入的第一个Tab也显示

### ISSUE THREAD

**Issue by cgd199158** [hustcc/echarts-for-react#41]
echarts在Tab面也切换时,只有第一次进入的第一个Tab页显示,请问如何才能所有Tab页都能显示?

**Comment by hustcc** [comment]
肯定是你的代码 bug，可以贴下大概代码吗

**Comment by cgd199158** [comment]
应该不是代码bug的问题,highchart就不存在这种问题,网上找了下,好像是说echart在display:none后需要重新渲染一次才能正常显示.

**Comment by hustcc** [comment]
可以看看在切换 tab 的时候，是否有 setOption 方法调用，或者 render 方法执行。

**Comment by lydiafork** [comment]
我也遇到了这个问题，echarts官方解答是切换的时候需要resize(),不过后来我是结合react-measure动态计算宽度解决的/(ㄒoㄒ)/~~

**Comment by hustcc** [comment]
@lydiafork 可以大概贴一下代码，可以帮助下其他人。

**Comment by cgd199158** [comment]
@lydiafork 还要动态计算宽度吗?

**Comment by lydiafork** [comment]
今天刚看到(ノへ￣、)捂脸   ，实在不好意思，没有看GitHub消息的习惯
`import Measure from 'react-measure';`
初始化
 `this.state = {
      dimensions: {
        width: '100%',
      },
    };`

`const { width } = this.state.dimensions;`
   `
return (   `
       `  <Measure   
        onMeasure={(dimensions) => {
          this.setState({ dimensions });
        }}
      >   `
          ` <div>   `
         `   <ReactEcharts   `
              ` ref={this.props.ref}   `
               `option={   `
                 ` mapDataToEcharts(data, color, name, maxy, unit, multiple)   `
               `}   `
               `notMerge  `
               `showLoading={false}   `
               `lazyUpdate   `
               `style={{ width, height: 175 }}  `
             `/>   `
           `</div>   `
        ` </Measure>`
