### ISSUE TITLE
series 里面的 label 设置无效

### ISSUE THREAD

**Issue by DBingo** [hustcc/echarts-for-react#410]
想要自定义 label 样式，但是发现修改 option 里面的 label 无法生效，甚至设置为 show: false 都无法隐藏。
emphasis 和 labelLine 字段也无法生效。
找了半天不知道问题出在哪里，同样的 option 在 echart 的 playground 里面是正常的。
目前在使用 type: 'pie' 和  type:'bar' 的图表均有发现，其他类型还没测试

https://codesandbox.io/s/compassionate-payne-fqn6x?file=/App.tsx

**Comment by DBingo** [comment]
https://echarts.apache.org/v4/examples/zh/editor.html?c=pie-nest
像这种官方示例的 option， 搬到  echarts-for-react  里面，也是 label 样式都丢了

**Comment by hustcc** [comment]
这里网站的 echarts 是 v5，是否版本对应上？

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/108598580-641a5480-73c9-11eb-8062-a15e8fbe1b1c.png)

![image](https://user-images.githubusercontent.com/7856674/108598587-6aa8cc00-73c9-11eb-9c9e-da98378adab8.png)

你使用了 v4 的配置项，用到 v5 的 echarts 上了。
