### ISSUE TITLE
Echarts pie chart proportion is too small to display text

### ISSUE THREAD

**Issue by keephungryHF** [hustcc/echarts-for-react#418]
        "echarts": "^5.0.2",
        "echarts-for-react": "^3.0.1",
[Here's an example](https://codesandbox.io/s/keen-ganguly-b2u0o?file=/App.tsx)
When the proportion of ”excellence“  is small，number do not display。
But when I increase the excellent ratio, the text is displayed
（当优秀这一项的比例很小时，上面的label数字就不显示了），我在想是不是和版本有关系？我使用的方式不对吗？

**Comment by hustcc** [comment]
在 echarts 测试看看，排除出是谁的问题。
