### ISSUE TITLE
echarts添加了单击事件后，如何判断点击的位置是哪里呢？

### ISSUE THREAD

**Issue by Pehfan** [hustcc/echarts-for-react#42]
我的雷达图有6个维度，每个维度之间点需要添加单击事件，请问echarts怎么判断我点击的是哪个点？
![radar](https://cloud.githubusercontent.com/assets/22440412/23897460/39d2d71a-08e8-11e7-87bf-2133be5ea093.png)

**Comment by Pehfan** [comment]
是根据dataIndex获取吧，但是我的dataIndex都是0，并且添加单击事件的时候，点第一次执行1次，点第二次执行2次，第三次执行4次依次类推，求解。

**Comment by hustcc** [comment]
这个是 雷达图 吧，要不把你的 option 代码贴下吧，我自己本地调试试一下。

echarts-for-react 项目中的事件全部用的是 echarts 的事件，只要原生 echarts 可以实现，这个组件就肯定可以实现。

**Comment by Pehfan** [comment]
我明天早上发可以吧，我的事件点一次触发多次有可能是因为我把事件放在了render方法里。

**Comment by Pehfan** [comment]
代码大致是这样，我需要点击雷达图上的点传入对应的下标的这个['48', '45', '47', '46', '54', '50']数组的值
option = {
    radar: {
        indicator: [
           { name: '玩具', max: 50},
           { name: '食品', max: 1800},
           { name: '用品', max: 200},
           { name: '纸品', max: 240},
           { name: '棉品', max: 5200},
           { name: '其他', max: 2560}
        ],

        name: {
          textStyle: {
            fontSize: 14,
            color: '#6e6e6e',
          },
        },
        splitArea: {
          areaStyle: {
            color: ['#fff'],
            shadowColor: 'rgba(0, 0, 0, 0.3)',
            shadowBlur: 10,
          },
        },
    },
    series: [{
        name: '客户营销推荐',
          type: 'radar',
          itemStyle: {
            normal: {
              areaStyle: {
                type: 'default',
              },
            },
          },
        data : [
            {
                value : [0, 967.2, 109.1, 170, 2601.5, 1280],
                symbolSize: 15,
                  itemStyle: {
                    normal: {
                      color: 'rgba(255, 105, 120, 0.8)',
                      labelLine: {
                        show: false,
                      },
                    },
              },
            },
        ]
    }]
};

**Comment by Pehfan** [comment]
我看了echarts官网API后发现可以用triggerEvent来控制坐标轴的标签是否响应和触发鼠标事件，然后现在我可以依据标签名传入数组内对应的值，不用点击雷达图内的点获取位置了，也算间接解决了问题。
