### ISSUE TITLE
echarts-for-react在option配置中无法显示toolbox

### ISSUE THREAD

**Issue by sky185959** [hustcc/echarts-for-react#421]
在项目中配置了toolbox无法显示
toolbox: {
      show: true,
      orient: 'vertical',
      top: 'middle',
      right: 'right',
    },

**Comment by hustcc** [comment]
1. 看看 echarts 官网是否可以
2. 看看版本是不是匹配
3. 如果还有问题，那么就给出跟详细的问题、报错
