### ISSUE TITLE
请问 pie chart 是否支持 unselected 事件？

### ISSUE THREAD

**Issue by aaamber323** [hustcc/echarts-for-react#422]
目前是支持点击选中触发 `this.PieSelect` 方法，但是取消选中，不会调用该方法：

```
const onEvents = {
      pieselectchanged: this.PieSelect,
};
```

请问，如果想做到取消选中的时候触发一个方法，该怎么做？

**Comment by hustcc** [comment]
参考 echarts 官方文档和示例，如果有问题，可以在 echarts 上提 issue。这里仅仅是 react 封装，不改变和增强 echarts 能力。
