### ISSUE TITLE
图表根据父容器大小响应式变化是如何实现的？

### ISSUE THREAD

**Issue by xiaoxiaoqian1217** [hustcc/echarts-for-react#428]
请问下源码是如何根据窗口大小的变化绘制图表的大小来做的响应式的，看起来式下面这里的代码起了作用，想问下原理的是什么呢？
![image](https://user-images.githubusercontent.com/22864018/118346016-1d24a100-b56b-11eb-948e-afc5c4f1eeac.png)

**Comment by hustcc** [comment]
size-sensor 代码里面搜一下这个库的使用。
