### ISSUE TITLE
any clue what would cause this error: "Uncaught TypeError: Cannot read property 'resize' of null"?

### ISSUE THREAD

**Issue by codTango** [hustcc/echarts-for-react#43]
My setup is that I have multiple sets of data and config for different chart types, so it allows to dynamically switch between multi chart types. It just simply pass everything as props to this HOC called `echarts-base-chart`, then it uses the `echarts-for-react` inside it.

Recently, I found it will throw this error when I switch the chart from one type to another. So I'm wondering what would cause this error?
![screen shot 2017-03-17 at 2 14 00 pm](https://cloud.githubusercontent.com/assets/5359697/24057152/c2ab7bb0-0b1c-11e7-95ae-66349b35e928.png)

**Comment by hustcc** [comment]
Can you show your code here ?

**Comment by hustcc** [comment]
This is bug of element-resize-event, Can you give me your code to help me solve the bug.

**Comment by codTango** [comment]
yes. but my code base is too big, it would take me some time to do diagnostic and extract the problem code.

**Comment by hustcc** [comment]
Maybe you can attach the mainly code into [here](https://github.com/KyleAMathews/element-resize-event/issues/16), maybe the author of `element-resize-event` can solve it quickly.

**Comment by hustcc** [comment]
update `echarts-for-react@1.1.7`, maybe can solve this bug. You can hava a try. ^_^
