### ISSUE TITLE
遇到了同样的问题，但是此issue中的🔗失效了

### ISSUE THREAD

**Issue by lbarakidouji** [hustcc/echarts-for-react#433]
componentDidMount () {
    this.echartsInstance = this.echarts_react.getEchartsInstance();
    this.zr = this.echartsInstance.getZr();
    this.zr.on('click', this.onChartClick);
  }

  onChartClick = (...rest) => {
    alert('1')
  }

https://xbuba.com/questions/52752552         
找到解决方案了

_Originally posted by @songhan777 in https://github.com/hustcc/echarts-for-react/issues/316#issuecomment-541494503_

**Comment by lbarakidouji** [comment]
自己解决了

**Comment by becca-ch** [comment]
链接失效了 能否重新说下解决方案 谢谢

**Comment by xudihui** [comment]
> 链接失效了 能否重新说下解决方案 谢谢

+1

**Comment by systemctls** [comment]
思路就是监听加载成功，在加载成功里做处理。拿到座标通过座标转换得到逻辑座标值（dataindex）
