### ISSUE TITLE
get nulll instance

### ISSUE THREAD

**Issue by CaptainJon** [hustcc/echarts-for-react#437]
When I am trying to wrap this component with some default options, I got errors everytime while trying to get the echart instance. Then I tried to log the instance in console and I found that it returned null after I fetched some async data.
![image](https://user-images.githubusercontent.com/51065061/124532704-a35eb480-de43-11eb-8237-683ccc768f17.png)
![image](https://user-images.githubusercontent.com/51065061/124532730-a9ed2c00-de43-11eb-81c0-72f793281da2.png)

**Comment by CaptainJon** [comment]
it will log the right instance the first time after loading the page, but while the getting async data is completed, which means the page will load again, then the instance returns null.

**Comment by wangjingithub** [comment]
有没有大佬解决这个实例问题啊？？？

**Comment by hustcc** [comment]
参考 demo https://github.com/hustcc/echarts-for-react/blob/master/docs/examples/api.md
