### ISSUE TITLE
event回调中setState导致zoom重置。

### ISSUE THREAD

**Issue by wanglianjie91** [hustcc/echarts-for-react#438]
如题， 在onEvents任何事件中setState，无论该state是否传入到Chart组件中，zoom都会重置。

**Comment by mkrauser** [comment]
@wanglianjie91 I'm having the same problem. If you did find a solution, it would be nice if you could share

**Comment by mkrauser** [comment]
Anyone who stumbles across this:
In our case we listened to the legendselectchanged and tried to update some information next to the chart. We saved the selected legend items (events.selected) to the component state. 
But when we added the state setter, the labels were not greyed out anymore. The whole behaviour was gone.

The reason for this was, that the chart was updated when the state changed. And the data for the chart contained the legend. So the component forgot about the greyed out legend-items.

The solution was, to add the selected legend items from the state to the chart-data.
