### ISSUE TITLE
Error on map: use the same code, but original way can rander

### ISSUE THREAD

**Issue by SnowfungusWang** [hustcc/echarts-for-react#445]
Recently, I try to register and use map(in geojson way), but the original echarts way works, the `echarts-for-react` way fails.
And I get this Error:
![image](https://user-images.githubusercontent.com/37967256/128631371-57f65aad-81ad-41c8-a37f-8f2924cdeb35.png)

version:
"echarts": "^5.1.2",
"echarts-for-react": "^3.0.1",
"react": "^17.0.2",
 "typescript": "^4.3.5",

**The code is as follow:** 
options: 
```
const getMapOpt = () => {
    const options = {
      grid: { top: 0, bottom: 0 },
      series: [
        {
          type: "map",
          map: "guangdong",
          aspectScale: 0.5,
          zoom: 1.3,
          label: {
            show: true,
            position: "insideTop",
            color: "#333",
          },
          itemStyle: {
            areaColor: "#fff",
            borderColor: "#343DA9",
            borderWidth: 1,
          },
          emphasis: {
            label: {
              color: "#fff",
            },
            itemStyle: {
              areaColor: "rgba(152, 155, 207, 0.7)",
            },
          },
        },
      ],
    };
    return options;
  };
```

init: 
```
useEffect(() => {
    echarts.registerMap("guangdong", geoJSON["guangdong"]);
    return () => {};
  }, []);
```
HTML
```
      <ReactEcharts
        option={getMapOpt}
        style={{ height: "400px" }}
      ></ReactEcharts>
```
Thanks🤞

**Comment by iitodo** [comment]
ReactEChartsCore  is the best choice for echarts 5 +.

<ReactEChartsCore
  echarts={echarts}
  option={getMapOpt}
  style={{ height: "400px" }}
/>

**Comment by SnowfungusWang** [comment]
> ReactEChartsCore is the best choice for echarts 5 +.
> 
> <ReactEChartsCore
> echarts={echarts}
> option={getMapOpt}
> style={{ height: "400px" }}
> />

Thanks  pretty  much, I have tried it, but still got the same error.

**Comment by hustcc** [comment]
保证注册地图在渲染之前。

> echarts.registerMap("guangdong", geoJSON["guangdong"]);
