### ISSUE TITLE
echart does not resize with react-grid-layout

### ISSUE THREAD

**Issue by lieyongchang** [hustcc/echarts-for-react#451]
I am using ResponsiveGridLayout, React-Grid-Layout in my application, and I am using echarts as grid items.

The drag and drop works fine, but when i resize the grid item, the chart did not resize together with it. I have tried implementing the onLayoutchange properties, but it is not working.

can someone can help me out here

this is my [codesandbox ](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-z3wd9?file=/src/newvsreturnvisitors.js:844-855)that reproduce the issue

**Comment by ThoughtofWeb** [comment]
did you solve this problem?I met the same problem

**Comment by lieyongchang** [comment]
yes click this [link](https://codesandbox.io/s/react-grid-layout-with-resizable-forked-ub5v2?file=/src/newvsreturnvisitors.js). If you have suggestion to improve this code, please let me know too, I am here to learn as well

**Comment by whiteblueblack** [comment]
@lieyongchang 你的代码解决了我的问题，谢啦

**Comment by Husain010** [comment]
Is there something that matches the same logic of the echarts resize function?
