### ISSUE TITLE
Can't add 'click' event for gauge chart 

### ISSUE THREAD

**Issue by antran998** [hustcc/echarts-for-react#457]
**My option:** 
{
  series: [
    {
      type: 'gauge',
      center: ['50%', '100%'],
      startAngle: 180,
      endAngle: 0,
      min: 0,
      max: 20,
      radius: '75',
      splitNumber: 10,
      itemStyle: {
        color: '#3aa272',
      },
      progress: {
        show: true,
        width: 30,
      },
      pointer: {
        show: false,
      },
      axisLine: {
        lineStyle: {
          width: 30,
          color: [[1, '#fdb00d']],
        },
      },
      axisTick: {
        distance: -45,
        splitNumber: 5,
        lineStyle: {
          width: 2,
          color: '#A2B2D2',
        },
        show: false,
      },
      splitLine: {
        distance: -52,
        length: 14,
        lineStyle: {
          width: 3,
          color: '#A2B2D2',
        },
        show: false,
      },
      axisLabel: {
        distance: -20,
        color: '#A2B2D2',
        fontSize: 20,
        show: false,
      },
      anchor: {
        show: false,
      },
      title: {
        show: false,
      },
      detail: {
        valueAnimation: true,
        width: '60%',
        lineHeight: 40,
        borderRadius: 8,
        offsetCenter: [0, '-15%'],
        fontSize: 18,
        fontWeight: 'bolder',
        formatter: '{value}/20',
        color: 'auto',
        show: false,
      },
      data: [
        {
          value: 10,
        },
      ],
    },
  ],
}

**My code:** 
const instance = widgetRef.current.getEchartsInstance();
instance.on('click', () => { alert(123) });

**Expect:** Click on gauge gauge chart and alert.
**Reality:** Nothing happen

**Comment by talltwin** [comment]
are you looking for the echarts repo?  If you implement Echarts for React, you'd follow this syntax for Events : 

`<ReactECharts
  option={this.getOption()}
  notMerge={true}
  lazyUpdate={true}
  theme={"theme_name"}
  onChartReady={this.onChartReadyCallback}
  onEvents={EventsDict}
  opts={}
/>`

**Comment by hustcc** [comment]
```tsx
const onEvents = {
  'click': this.onChartClick,
}
...
<ReactECharts
  option={this.getOption()}
  style={{ height: '300px', width: '100%' }}
  onEvents={onEvents}
/>
```
