### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by VikiLee** [hustcc/echarts-for-react#461]
问题描述：
折线图显示异常，echart不管是在最4.0版本还是在5.0版本，在小屏幕上会偶发出现，大屏幕没问题。

4.0版本的echart:
{
"echarts": "4.7.0",
"echarts-for-react": "2.0.15-beta.1"
}

5.0版本的echart:
{
 "echarts": "5.2.2",
 "echarts-for-react": "3.0.2",
}

![image](https://user-images.githubusercontent.com/5304117/142177403-bd71c752-43ad-42a3-a91d-f726eee3a947.png)

**Comment by hustcc** [comment]
现把配置放到 echarts 官网 demo 中，看看是否也存在问题，如果存在那么需要在 echarts 的项目中提交 issue。
