### ISSUE TITLE
按需加载抱错，Unexpected token 'export'，求解

### ISSUE THREAD

**Issue by TrentXie** [hustcc/echarts-for-react#462]

**Comment by TrentXie** [comment]
echarts v5版本

**Comment by TrentXie** [comment]
nextjs，ssr问题，使用dynamic方法，ssrfalse即可

**Comment by liran319** [comment]
"Uncaught SyntaxError: Unexpected token '.' " ERROR when build ReactECharts in nextjs, both `ssr` or `dynamic + no-ssr`
