### ISSUE TITLE
How can i add decal patterns to the graphs?

### ISSUE THREAD

**Issue by afkcodes** [hustcc/echarts-for-react#465]
First of all Thanks @hustcc this package is so wonderful, fulfill all my needs in every manner i want plot the data a big kudos to you. Now coming to the question. I saw on the echarts examples that we can add decal patterns just wanted to know if we can do the same, if yes please tell me how. Thanks

**Comment by mobeigi** [comment]
@afkcodes You can add decals using eCharts options (if you're using v5+).

Go read the documentation:
https://echarts.apache.org/en/option.html#legend.itemStyle.decal.symbol
https://echarts.apache.org/examples/en/editor.html?c=doc-example/aria-decal-simple

Closing this issue as it has nothing to do with `echarts-for-react`.

**Comment by afkcodes** [comment]
hey @mobeigi 
I tried with 

aria: {
      enabled: true,
      decal: {
        show: true
      }
    }
    
    as the doc says probably it will use some default decal if you dont provide one but this doesn't seems to work. thanks for the info please let me know if you are able to make it work. i really need this.
