### ISSUE TITLE
No way to set replaceMerge: ['XXX'] with setOption

### ISSUE THREAD

**Issue by yarondav** [hustcc/echarts-for-react#469]
Thank you for making echarts-for-react.

Please see here:
https://github.com/apache/echarts/issues/6202

**Comment by hustcc** [comment]
notMerge

```tsx
import React from 'react';
import ReactECharts from 'echarts-for-react';  // or var ReactECharts = require('echarts-for-react');

<ReactECharts
  option={this.getOption()}
  notMerge={true}
  lazyUpdate={true}
  theme={"theme_name"}
  onChartReady={this.onChartReadyCallback}
  onEvents={EventsDict}
  opts={}
/>

```

**Comment by mhyfritz** [comment]
Hi @hustcc,

`replaceMerge` is a new parameter in ECharts v5. It lets you replace specific components (e.g. series) without losing other state (e.g. current zoom setting, legend selection) while `notMerge` replaces/resets everything. It would be really great if you could support `replaceMerge` in `echarts-for-react`. In any case, thanks a lot for your work on this library! 

Sources:
https://github.com/apache/echarts/issues/6202#issuecomment-974761211
https://echarts.apache.org/en/api.html#echartsInstance.setOption

**Comment by branogoga** [comment]
You can use the custom effect to replace the part You need:

```
  useEffect(() => {
    if (!chartRef.current) {
      return
    }
    // @ts-ignore
    const chart = chartRef.current.getEchartsInstance()
    if (!chart) {
      return
    }

    chart.setOption(option, {
      replaceMerge: ['series'],
    })
  }, [chartRef, ...])
```
