### ISSUE TITLE
高度设置后仍然出错

### ISSUE THREAD

**Issue by lydiafork** [hustcc/echarts-for-react#47]
外框的高度明明是171，到内框就又变成100了 /(ㄒoㄒ)/~~ help
![89d643aa-9e77-4d40-84cb-95aaf99e9d82](https://cloud.githubusercontent.com/assets/16407920/24555089/7034cbf6-1662-11e7-8f6f-f8e817e654c2.png)

**Comment by hustcc** [comment]
具体代码是怎么写的，另外错误是什么？
