### ISSUE TITLE
onEvents 的问题

### ISSUE THREAD

**Issue by wssll789** [hustcc/echarts-for-react#477]
在Component中使用
如果需要用到props或者state的话我就需要
onEvents = {
            'legendselectchanged': this.legendselectchanged.bind(this)
          }
.bind(this)的这个操作就会造成图表重新刷新
如果不.bind(this)就不会重新刷新，但是这样就没办法使用 props和state

**Comment by wulanx0920** [comment]
遇到了同样问题，请问有解决么

**Comment by LinYu01** [comment]
```
  const onChartClick = useCallback((param, echarts) => {
    console.log(param, echarts);
    setCount((count) => count + 1);
  }, []);

  const onChartLegendselectchanged = useCallback((param, echarts) => {
    console.log(param, echarts);
  }, []);
```

**Comment by zhaobosky** [comment]
遇到同样的问题

**Comment by FengHuangDong** [comment]
可以在onchartready的callback里面拿到echart实例自己去添加事件监听

**Comment by LaraineR** [comment]
> 可以在onchartready的callback里面拿到echart实例自己去添加事件监听

你好，请问有例子嘛？
