### ISSUE TITLE
getEchartsInstance无法获取echarts的实例

### ISSUE THREAD

**Issue by challen03** [hustcc/echarts-for-react#48]
getEchartsInstance无法获取echarts的实例,只有一些私有方法，无法获取connect方法

**Comment by hustcc** [comment]
打印出来 getEchartsInstance 的结果出来是什么东西？undefined？

**Comment by challen03** [comment]
![image](https://cloud.githubusercontent.com/assets/23453275/24835923/5119bf70-1d41-11e7-9d27-611c55565f8a.png)
![image](https://cloud.githubusercontent.com/assets/23453275/24835926/656553b8-1d41-11e7-9924-4fc4c8ce738c.png)
是一个echarts的实例，但是里面的connect方法没有

**Comment by hustcc** [comment]
connent 这个 API 是 echarts 的方法，而不是 echarts 实例的方法，你可以这么使用：

```js
import echarts from 'echarts';

let echarts_1 = this.refs.echarts_react1.getEchartsInstance();
echarts_1.group = 'group';

let echarts_2 = this.refs.echarts_react2.getEchartsInstance();
echarts_2.group = 'group';

// 调用 connect API
echarts.connect('group');
// 或者可以直接传入需要联动的实例数组
echarts.connect([echarts_1, echarts_2]);
```

非常不好意思，因为最近忙，所以 issue 回复比较晚。

**Comment by challen03** [comment]
好的，谢谢了，我当时搞了好久，现在这个需要暂时不做了，感谢
