### ISSUE TITLE
在做echart滚动条动画的时候，如果配置了toolTip滚动条动画就会出现问题，每次动画都会初始化一次，在社区上用方法的时候应该是没有问题的

### ISSUE THREAD

**Issue by qwe5117022** [hustcc/echarts-for-react#480]

**Comment by qwe5117022** [comment]
let max = 100
    let num = 0
    let end = 30
    const instance = useRef(null);
    let isBig = true;
    let timerId;    
function delay() {
        if (isBig) {
            num = num + 2;
            end = end + 2;
            if (end > max) {
                isBig = false;
            }
            const newOption = instance.current?.getEchartsInstance().getOption();//获取最新改变的option
            newOption.dataZoom[0].end = end
            newOption.dataZoom[0].start = num
            instance.current?.getEchartsInstance().setOption(newOption);//强制更新echarts图表
 
        } else {
            num = 0;
            end = 30
            if (num < max || end < max) {
                isBig = true;

            }
            const newOption = instance.current?.getEchartsInstance().getOption();//获取最新改变的option
            newOption.dataZoom[0].end = 30
            newOption.dataZoom[0].start = 0
            instance.current?.getEchartsInstance().setOption(newOption);//强制更新echarts图表
        }
    }
    useEffect(() => {
        if (timerId) {
            clearInterval(timerId);
        }
        timerId = setInterval(function () {
            delay();
        }, 1000);
        return () => {
            clearInterval(timerId)
        }
    }, [])

**Comment by qwe5117022** [comment]
代码部分是这样，是我代码写的部分有bug吗，麻烦大佬帮忙看一下

**Comment by qwe5117022** [comment]
这个是一个自动滚动dataZoom的start 和end的一个定时器，每次自动往右边滚动，到达100就重新开始，我只要不配置tooltip，定时器就不会发生bug

**Comment by qwe5117022** [comment]
我用原生封装了一下好像没有问题

**Comment by hustcc** [comment]
option 中的 function，请保持引用，比如 useCallback.
