### ISSUE TITLE
Labels for pie chart is not getting hidden 

### ISSUE THREAD

**Issue by ghulamyazdani** [hustcc/echarts-for-react#481]
![image](https://user-images.githubusercontent.com/55938346/159572014-a4c7f5de-bca4-417f-aaa7-fb4fe2f4c6a2.png)
I want to hide the labels from the pie chart i.e churns but not able to do that  ,have tried 
![image](https://user-images.githubusercontent.com/55938346/159572317-0c3c3698-4516-418e-bb78-1e345b24395d.png)

this didn't worked

**Comment by iAmmarTahir** [comment]
By using: 

`{
 ...,
series: [
  ....,
  label: {
        show: false,
  },
  .....
]
}`

you can hide the labels.
