### ISSUE TITLE
Bundle size still large after manually imported

### ISSUE THREAD

**Issue by mesopa** [hustcc/echarts-for-react#492]
Hello team.
I was trying to reduce the bundle size following the example available on your git repository but I don't see any improvement. The final result is very similar. Do you think I'm missing something?

Before manually import:
![image](https://user-images.githubusercontent.com/6706294/173983422-8952549e-9a9d-4975-9056-3d322b9da9ce.png)

Manually import the necessary components:
![image](https://user-images.githubusercontent.com/6706294/173982998-8c25aaea-27c5-44ec-abb0-00ec21bd81e5.png)
![image](https://user-images.githubusercontent.com/6706294/173983347-8c232065-cfb9-4423-9e06-b65fedc684b5.png)

![image](https://user-images.githubusercontent.com/6706294/173982806-22b35dc3-a27b-4ce8-a98a-9bf452027173.png)

If I remove all the components, only for reference:
![image](https://user-images.githubusercontent.com/6706294/173982887-73670036-8eac-484f-93a6-8fe00a1f6536.png)

Best regards.

**Comment by hustcc** [comment]
this is the limit of echarts.
