### ISSUE TITLE
ReactECharts 可以导入ECharts官网的3D地球嘛，如果可以的话请问如何导入

### ISSUE THREAD

**Issue by ZYyyh-cool** [hustcc/echarts-for-react#493]
option = {
  backgroundColor: '#000',
  globe: {
    baseTexture: ROOT_PATH + '/data-gl/asset/earth.jpg',
    heightTexture: ROOT_PATH + '/data-gl/asset/bathymetry_bw_composite_4k.jpg',
    displacementScale: 0.1,
    shading: 'lambert',
    environment: ROOT_PATH + '/data-gl/asset/starfield.jpg',
    light: {
      ambient: {
        intensity: 0.1
      },
      main: {
        intensity: 1.5
      }
    },
    layers: [
      {
        type: 'blend',
        blendTo: 'emission',
        texture: ROOT_PATH + '/data-gl/asset/night.jpg'
      },
      {
        type: 'overlay',
        texture: ROOT_PATH + '/data-gl/asset/clouds.png',
        shading: 'lambert',
        distance: 5
      }
    ]
  },
  series: []
};
 <ReactECharts style={{ height: "100vh",width:"100vh" }} option={option } />
 我这样子做不可以

**Comment by hustcc** [comment]
please give me information!

**Comment by hustcc** [comment]
如果 echarts 官网可以，这个 react 组件就一定可以。
