### ISSUE TITLE
dispatchAction 

### ISSUE THREAD

**Issue by kll982** [hustcc/echarts-for-react#497]
在 echarts-for-react 中该如何使用 dispatchAction 方法呢

**Comment by EquinoxFlowerJG** [comment]
同问

**Comment by hustcc** [comment]
https://github.com/hustcc/echarts-for-react#component-api--echarts-api

get the instance, than exec `dispatchAction ` API.

**Comment by EquinoxFlowerJG** [comment]
您好，来信已收到，我会尽快给您回复的。
