### ISSUE TITLE
map设置zoom属性问题

### ISSUE THREAD

**Issue by zhongning7924** [hustcc/echarts-for-react#50]
当设置zoom属性为1.5倍的时候，默认显示是正常的，滑动鼠标滚轮放大地图，停留1s后自己又还原到默认的zoom值，想要的是停留放大后的地图效果，

```js
    geo: {
        map: 'china',
        label: {
            emphasis: {
                show: false
            }
        },
        zoom: 1.5,
        roam: true,
        itemStyle: {
            normal: {
                areaColor: '#323c48',
                borderColor: '#111'
            },
            emphasis: {
                areaColor: '#2a333d'
            }
        }
    },
```

**Comment by hustcc** [comment]
滑动滚轮放大地图的代码可以写出来吗？应该是没有放到 state 里面吧？

**Comment by zhongning7924** [comment]
http://gallery.echartsjs.com/editor.html?c=effectScatter-map
就是把这个的代码的option里面增加了一个 zoom属性，  
echarts的属性设置了roam: true,之后地图可以任意的放大缩小，在echarts示例中使用也是没问题的，但是放到封装的组件中之后，就是有手动放大之后自动还原默认值zoom比例的问题，
import { mapdata } from 'constants/chinacity.js' //封装Option的js，
            mapoption: cloneDeep(mapdata.geomapoption),//设置默认的state

                  //调用地图
                    <ReactEcharts
                                option={this.state.mapoption}
                                style={{height: '800px', width: '100%'}}/>

**Comment by hustcc** [comment]
因为你滚动鼠标 zoom 之后，state 里面 option 的 zoom 并没有变化，所以当下一次 state 触发 render 方法的时候，会导致 zoom 复原。
建议加一下 zoom 事件，然后设置到 state 中。可以[在这里看看](http://echarts.baidu.com/api.html#events)有没有对应的 echarts 事件。

**另外**：简单几个 markdown 语法可以让你的内容和代码可读性更高，所以希望下次再提 issue 的时候，可以给你的代码做一个简单的缩进，以及代码高亮。

**Comment by zhongning7924** [comment]
@hustcc 好的，谢谢~，
但是我不太理解一种情况，当不主动设置zoom属性的时候，echarts中默认的是值是1，此时随意的放大或者缩小地图当停止的时候却是不恢复的，讲道理应该是一样的恢复猜对。。。

**Comment by hustcc** [comment]
这个是有一点奇怪，可能跟 echarts 内部实现有关系吧。

比如：当没有设置 zoom 属性是，echarts 会在内存中缓存一份默认值为 1，然后在鼠标放大缩小的时候，会修改这个 zoom 缓存，当下次收到 option 中的 zoom 还是为 undefined 的时候，就直接取那个缓存值吧。
