### ISSUE TITLE
Apache echarts - Seatmap 

### ISSUE THREAD

**Issue by tytx** [hustcc/echarts-for-react#503]
Hello is this: https://echarts.apache.org/examples/en/editor.html?c=geo-seatmap-flight&lang=ts (custom flight seat map) available as an example/functionality within echarts-for-react?

**Comment by tytx** [comment]
do you know how can i adapt 
```
var chartDom = document.getElementById('main');
var myChart = echarts.init(chartDom);
var option;
```
from: https://echarts.apache.org/examples/en/editor.html?c=geo-seatmap-flight&lang=js
using echarts-for-react

**Comment by hustcc** [comment]
Just pass the `option` in to echarts-for-react component.
