### ISSUE TITLE
触发点击事件后图表会闪烁一下 ( chart will blink when triggering a click event  )

### ISSUE THREAD

**Issue by yyxTheOracle** [hustcc/echarts-for-react#505]
寻找解决方案的时候才发现 [官网实例](https://git.hust.cc/echarts-for-react/examples/event/) 也有这个问题。
![problem](https://media.giphy.com/media/v8hLWmtFvPH7Rp8SDW/giphy.gif)
好像只要点击后触发了组件状态的改变，图表就会闪一下，不知道各位有没有什么好的解决方法 ┭┮﹏┭┮

**Comment by zhengyunyu** [comment]
原因在于这个例子中给图表绑定了Event，源码中对于数据更新时对Event其实作了一层比较，如果Event相同则不会对图表进行重新渲染。但是问题就恰恰在此，作者使用的库是无法对函数进行比较的，所以对于每次set数据来说，Event都不一样，就会导致图表重新更新。解决的方法也很简单，把你绑定的Event都加上useCallback即可解决

**Comment by zhengyunyu** [comment]
Event的比较我也给作者提出了pr，但目前还没得到回应

**Comment by yyxTheOracle** [comment]
> 原因在于这个例子中给图表绑定了Event，源码中对于数据更新时对Event其实作了一层比较，如果Event相同则不会对图表进行重新渲染。但是问题就恰恰在此，作者使用的库是无法对函数进行比较的，所以对于每次set数据来说，Event都不一样，就会导致图表重新更新。解决的方法也很简单，把你绑定的Event都加上useCallback即可解决

感谢您的详细解答！帮了大忙！❤❤❤
