### ISSUE TITLE
当项目运行在React@15.5.4时候PropTypes的问题

### ISSUE THREAD

**Issue by kanoyami** [hustcc/echarts-for-react#51]
当项目运行在React@15.5.4时控制台会报如下警告
*  Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
请大佬替换下PropTypes的访问方式。

**Comment by hustcc** [comment]
使用的是最新版本的 echarts-for-react 吗？最新版本已经修改这个了。

**Comment by FishYu99** [comment]
React@15.5 已經刪除PropTypes
https://github.com/facebook/react/releases/tag/v15.5.0

請額外引入檔案
https://github.com/reactjs/prop-types

**Comment by hustcc** [comment]
@FishYu99 
这个问题在 v1.2.1 版本中已经解决了。
