### ISSUE TITLE
怎么获取缩放比例

### ISSUE THREAD

**Issue by Lubcdtyb** [hustcc/echarts-for-react#53]
echarts 只查到可以通过myChart.chart.map._mapDataMap.china.transform.baseScale来获取缩放比例，echarts-for-react呢？

**Comment by hustcc** [comment]
```js
this.echarts_object.getEchartsInstance().chart.map._mapDataMap.china.transform.baseScale
```

可以看文档 https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api

**Comment by Lubcdtyb** [comment]
![image](https://cloud.githubusercontent.com/assets/12692270/25733023/eddb137c-3187-11e7-95c3-0f1685737f1b.png)这是我打印出来的实例，并没有找到相应的属性

**Comment by hustcc** [comment]
这个 `this.echarts_object.getEchartsInstance()` 取到的就是原生的 echarts 对象，后面的使用就是按照 echarts 文档来了，跟`echarts-for-react`就没有什么关系了。

你可以贴一下你自己的代码（包含 myChart.chart.map._mapDataMap.china.transform.baseScale 这段的），我看看能不能帮你找到问题所在。
