### ISSUE TITLE
怎么监听点击空白的事件呢。echarts的myChart.getZr().on

### ISSUE THREAD

**Issue by iceycc** [hustcc/echarts-for-react#537]

**Comment by wanglihuaya** [comment]
```javascript
  const echartsRef = useRef<any>(null);
  useEffect(() => {
    const echarts = echartsRef.current.getEchartsInstance();
    echarts.getZr().on('click', function (event) {
      if (!event.target) {
        console.log(event);
      }
    });
  }, []);
```

这样就可以了

**Comment by GREEB** [comment]
> ```js
>   const echartsRef = useRef<any>(null);
>   useEffect(() => {
>     const echarts = echartsRef.current.getEchartsInstance();
>     echarts.getZr().on('click', function (event) {
>       if (!event.target) {
>         console.log(event);
>       }
>     });
>   }, []);
> ```
> 
> 这样就可以了

This works but if anyone has issues with ```echarts.getZr()```returning ``ǹull`` , it only works as long as you don't have these ```onEvents``` on ```ReactECharts```

```js

  const onEvents = {
    onmousedown: onMouseDown, // remove this
    onmouseup: onMouseUp, // remove this
  };

```
