### ISSUE TITLE
"version": "1.2.2"： 存在2个 Warning

### ISSUE THREAD

**Issue by Jafeney** [hustcc/echarts-for-react#54]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

建议更新依赖包

**Comment by hustcc** [comment]
1.2.2 版本就是修改了以上 deprecated 问题的，是否本地没有重新安装依赖。

[live demo](http://git.hust.cc/echarts-for-react/) 也是没有 warning 的。

**Comment by jeffvandyke** [comment]
I'm still getting the PropTypes warning, even with the latest version. It looks like all that needs to be done is to replace "React.PropTypes" with "PropTypes".

**Comment by hustcc** [comment]
Sorry, my omission. I have push a new commit, after test, v1.2.3 will solve the warning.

**Comment by hustcc** [comment]
Done, v1.2.3

@jeffvandyke @Jafeney
