### ISSUE TITLE
echarts-for-react@1.2.3 requires a peer of react@>=0.13.2 || ^0.14 || ^15.0.0 but none was installed.

### ISSUE THREAD

**Issue by hnliyuan** [hustcc/echarts-for-react#55]
echarts-for-react@1.2.3 requires a peer of react@>=0.13.2 || ^0.14 || ^15.0.0 but none was installed.

`-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6

**Comment by hustcc** [comment]
666，16 都已经用上了。好激进啊~

**Comment by hnliyuan** [comment]
23333 快兼容呀

**Comment by hustcc** [comment]
16.0.0 还是 beta 和1 alpha，不建议使用啊，建议等官方正式版本出来在使用。

**Comment by hnliyuan** [comment]
哦。好吧，我其实想感受一下Fiber在安卓有没有明显的优化

**Comment by hustcc** [comment]
哦哦，我刚也猜到，应该是要体验这个 fiber 特性，我今天抽时间兼容一下 16 吧，应该只需要修改 peerDependencies。

**Comment by hnliyuan** [comment]
thx~~

**Comment by hustcc** [comment]
v1.2.4 done.

**Comment by hnliyuan** [comment]
可以了。谢谢
