### ISSUE TITLE
How to override the readonly style for position relative?

### ISSUE THREAD

**Issue by Mariella-Pasamonte** [hustcc/echarts-for-react#555]
I'm trying to create a website UI and I intend to add charts. But when I scroll down, the charts is still visible (on top of the navbar). I  tried to hide it with overflow but it won't work. I tried making the navbar fixed but it also scrolled up. 
![image](https://github.com/hustcc/echarts-for-react/assets/73897046/101246c6-4f3b-46cb-8c3a-99443472ea66)

**Comment by IGrebyonkin** [comment]
Я решил эту проблему через z-index:
<Container style="{{zIndex: 300}}">
    <Chart />
</Container>

**Comment by hustcc** [comment]
This is a css problem, use the `style` props, see https://github.com/antvis/G6/discussions/5835 .
