### ISSUE TITLE
我在引用echarts-for-react 时会报出一个错误

### ISSUE THREAD

**Issue by Jackie-Web** [hustcc/echarts-for-react#56]
我在引用echarts-for-react 时会报出一个错误 
Cannot read property 'requestAnimationFrame' of undefined
我定位很久没找到原因。

**Comment by hustcc** [comment]
截图看看，还有你的开发环境，便于我复现。

**Comment by Jackie-Web** [comment]
![image](https://cloud.githubusercontent.com/assets/11611057/25938530/1d926c76-3662-11e7-865a-18356db5b7d1.png)
webpack 打包的 React 15.4.2，
node 环境 v7.10.0
![image](https://cloud.githubusercontent.com/assets/11611057/25939892/fde5a686-3666-11e7-9913-59ea3ad860d4.png)
![image](https://cloud.githubusercontent.com/assets/11611057/25939971/318e8c0a-3667-11e7-91db-3d3dcb94106a.png)
![image](https://cloud.githubusercontent.com/assets/11611057/25940056/76393382-3667-11e7-8e27-37ef547832e0.png)
我定位到的问题是 element-resize-event 这个插件 把this 指向 window 然后 this指向是空的 你看下这个插件？

**Comment by Jackie-Web** [comment]
我在我的项目下把这个依赖去掉了，可以正常使用。麻烦查一下是不是这个插件造成的原因呢  element-resize-event 这个插件的window指向错误导致的。

**Comment by Jackie-Web** [comment]
我自己重新依赖了版本为2.0.7的  element-resize-event 已经可以正常使用了，大概是 2.0.9会有这样的问题。我在这个插件里已经提过问题了，下面的建议是依赖2.0.7。LZ看下是否要降级一下？

**Comment by hustcc** [comment]
可以，我降到 2.0.7 测试一下试试看，然后发新版本。

**Comment by hustcc** [comment]
我直接指定 "element-resize-event": "2.0.7"，限制死版本了。

**Comment by ChanJuanMei** [comment]
我也遇到这个问题了，感谢@hustcc  。我也降级到2.0.7就好了

**Comment by ChanJuanMei** [comment]
我有两个项目，一个是2.0.9的普通配置可以运行。另外一个是webpack中配置了bundle-loader，只能采用2.0.7

**Comment by hustcc** [comment]
Reference: https://github.com/hustcc/echarts-for-react/issues/166
