### ISSUE TITLE
There is an error when I install it by pnpm.

### ISSUE THREAD

**Issue by LukerSpringtree** [hustcc/echarts-for-react#570]
<img width="1273" alt="image" src="https://github.com/hustcc/echarts-for-react/assets/9697295/5489d02b-0d6a-4a52-a8c1-918b010a8abf">

when I remove this dependency, everything will be ok~

**Comment by Nazoya** [comment]
这个问题应该是你的 package-lock.json 文件中地址出错了。删除重装从而更正 lock 文件，或是使用 npm 官方源安装此包一般都可以解决此问题。这个问题发生于 npmmirror 与 npm 未同步时，可能是其他原因导致的，倒不是这个包自身的问题。

This problem may occured for the wrong uri in package-lock.json. Remove and reinstall it to correct lock file or install it through the official source may solve it.
This usually happened when npmmirror being out of sync of npm, for some reason but not a problem about this package though.

😉
