### ISSUE TITLE
想注册使用全世界map地图json文件，一直报错找不到。想问下要怎么注册？

### ISSUE THREAD

**Issue by gxqs416122** [hustcc/echarts-for-react#58]
import ReactEcharts from 'echarts-for-react'
import echarts from 'echarts'
const worldJson = require('./world.json')
echarts.registerMap('world', worldJson)
<ReactEcharts
          ref={(echarts) => {
            this.echarts = echarts
          }}
          onEvents={this.getEvents()}
          option={this.state.option}
          notMerge
          lazyUpdate
          style={this.getStyle()} />
浏览器报错：
geoCreator.js:111 Map world not exists. You can download map file on http://echarts.baidu.com/download-map.html

**Comment by moxiaobei** [comment]
同问

**Comment by hustcc** [comment]
world.json 这个文件在哪里？

**Comment by hustcc** [comment]
把这个文件引入到你们的代码中：http://gallerybox.echartsjs.com/dep/echarts/map/js/world.js

这个的 world 的地图文件吧。

**Comment by gxqs416122** [comment]
这样引用也不行，我看了下原因，echarts.registerMap是维护的一个mapDataStores = {}，而你封装的组件里没有封装接口调用到你代码目录下的echarts包下的echarts.registerMap。而如果直接引入外面的echarts的话，就出现另外一个mapDataStores，而你组件本身不会使用这个。

**Comment by hustcc** [comment]
你那有解决方案吗？如果可以的话，欢迎发起 pr。

**Comment by fufjvnvnf** [comment]
试试手动下载地图之后这样引用？
`require('echarts/map/js/world.js');
`

**Comment by hustcc** [comment]
@fufjvnvnf 你的问题已经解决了？

**Comment by fufjvnvnf** [comment]
没解决啊。。。只是这里感觉换一种import地图的方法或许能行

**Comment by hustcc** [comment]
@gxqs416122 试一下使用 v1.4.1 版本试一下，应该是安装的 echarts 版本有多个造成的。

**Comment by oujiaru** [comment]
同问 该如何引用echarts.registerMap这个api 我用一个市级地图报同样的错 请问各位是怎么解决的
