### ISSUE TITLE
Uncaught Error: Series has not been initialized yet

### ISSUE THREAD

**Issue by sopaco** [hustcc/echarts-for-react#60]
Uncaught Error: Series has not been initialized yet.
报了这个错

**Comment by hustcc** [comment]
什么样的场景报错？感觉是Option 缺少参数。

**Comment by hustcc** [comment]
可以提供你的 option 吗，或者你写的代码片段。

**Comment by Yaxian** [comment]
@sopaco You could try the code blow:
```
const reactEchartsInstance = this.reactEcharts.getEchartsInstance()
setTimeout(() => {
   reactEchartsInstance.setOption([yourOption])
}, 500)
```
no matter where you run this code snippet in react compoennts `Lifecycle Methods`, like `componentWillReceiveProps`.

**Comment by hustcc** [comment]
@Yaxian 不是一个很好的解决办法，react 解决了数据绑定，就不需要我们去手动 setOption 了…

**Comment by Yaxian** [comment]
@hustcc yeah, you are right.
I see your source code at [L68](https://github.com/hustcc/echarts-for-react/blob/master/src/echarts-for-react.js#L68).

The `Echats` instance call `setOption` in `componentDidUpdate` . But `componentDidUpdate` maybe not work if parent component's `shouldComponentUpdate` return `false`, I guess. :smile:

**Comment by hustcc** [comment]
OK, I know your case.
