### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by yangfan0095** [hustcc/echarts-for-react#62]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

之前用的antd 2.9.x 的版本也有这个问题， 希望可以尽快修复！

我用的echarts-for-react 版本是1.2.2

ReactEcharts.propTypes = {
  option: _react2['default'].PropTypes.object.isRequired,
  notMerge: _react2['default'].PropTypes.bool,
  lazyUpdate: _react2['default'].PropTypes.bool,
  style: _react2['default'].PropTypes.object,
  className: _react2['default'].PropTypes.string,
  theme: _react2['default'].PropTypes.string,
  onChartReady: _react2['default'].PropTypes.func,
  showLoading: _react2['default'].PropTypes.bool,
  loadingOption: _react2['default'].PropTypes.object,
  onEvents: _react2['default'].PropTypes.object
};

**Comment by hustcc** [comment]
1.2.5之后是解决这个问题的，更新一下版本。
