### ISSUE TITLE
请问如何使用bmap扩展包？

### ISSUE THREAD

**Issue by fufjvnvnf** [hustcc/echarts-for-react#63]

**Comment by hustcc** [comment]
#58 这个看看。

**Comment by fufjvnvnf** [comment]
所以现在是还不能支持吗？

**Comment by fufjvnvnf** [comment]
bmap貌似和registerMap是不一样的，他只是echarts的一个拓展包。https://github.com/ecomfe/echarts/tree/master/extension/bmap 介绍了如何引入bmap。请问在react中有什么相同的引入方式吗？谢谢

**Comment by hustcc** [comment]
直接使用 echarts 时怎么引入 bmap？

**Comment by fufjvnvnf** [comment]
```
<!--引入百度地图的jssdk，这里需要使用你在百度地图开发者平台申请的 ak-->
<script src="http://api.map.baidu.com/api?v=2.0&ak="></script>
<!-- 引入 ECharts -->
<script src="dist/echarts.min.js"></script>
<!-- 引入百度地图扩展 -->
<script src="dist/extension/bmap.min.js"></script>
```
这三行，或者
```
require('echarts');
require('echarts/extension/bmap/bmap');
```
那个链接里有提到。不过我不是很确实第二种为什么可以引入，因为他没有说明api key。

**Comment by hustcc** [comment]
那就按照这两个方法，要么在 html 中引入 js 文件；要么直接在 js 中 require bmap。

**Comment by fufjvnvnf** [comment]
请问在jsx中如何require那个api key？我直接
`require('http://api.map.baidu.com/api?v=2.0&ak=FUmG8hLpACVnEatoLyLNGSIG4SY6VAIM');
`
不行

**Comment by hustcc** [comment]
这个只能在 html 里面使用 script 引入了…
