### ISSUE TITLE
用的好好的突然就报错了找不到module echarts

### ISSUE THREAD

**Issue by JianglongHe** [hustcc/echarts-for-react#67]
用的好好的突然就报错了找不到module echarts，然后装了echarts模块后样式完全变了还有错误

**Comment by hustcc** [comment]
是否在你的项目中，将 echarts 作为 dependencies。

**Comment by JianglongHe** [comment]
我用的1.1.7之前的版本正常使用，此时dependencies和dev dependencies都没有引入echarts,然后在一次npm install , prod 启动的时候报了找不到echarts,然后装上，鼠标移动到柱子上的提示文字没有了，我没有更新版本，就用老版本，然后我把echarts装上去发现没有文字提示了，比较紧急的问题！

**Comment by hustcc** [comment]
如果比较紧急，可以在你们项目中将 echarts-for-react 的 dependencies 写死为 1.2.5 版本。

```js
"echarts-for-react": "1.2.5",
```

**Comment by JianglongHe** [comment]
很强势，这个可以了

**Comment by SidKwok** [comment]
@JianglongHe 你的`package.json`的`dependencies`里面有`echarts`吗？

**Comment by hustcc** [comment]
@JianglongHe 嗯，解决之后，有空帮我们调试一下 1.3.5 版本的问题吧。帮我们排查一下为什么 tooltip 出不来？

这个版本加入了新特性，就是可以自定义 import echarts 的模块，这样可以减少打包出来的 js 文件大小。

**Comment by SidKwok** [comment]
@JianglongHe 可以看看console里面出的错误是什么

**Comment by JianglongHe** [comment]
@SidKwok console.log()没有撒错误哈，是我们自己不小心写出来的。只是tooltip没有出来而已,现在dependencies里面没有echarts了

**Comment by JianglongHe** [comment]
@hustcc 可以的，下来看看

**Comment by hustcc** [comment]
在你们的 package.json 中 dependencies 加入 "echarts": "^3.5.4"。
然后将版本更换到新版本  "echarts-for-react": "1.3.5"。

然后在看看有没有问题，如果还是有问题，可以把你的 option 信息发出来一下。

**Comment by SidKwok** [comment]
@JianglongHe 你在测试的时候，如果出错，可以看看控制台报的错误，顺便把它贴上来

**Comment by hustcc** [comment]
还是觉得不应该把 echarts 运维 peer

**Comment by hustcc** [comment]
还是觉得不应该把echarts作为peer依赖，这样太灵通，容易导致用户有版本问题，我觉得还是要发一个版本，修改为依赖 echarts。

你觉得怎么样？

**Comment by SidKwok** [comment]
@hustcc 可以的，我也觉得这样子比较合理。顺便把prop-types也移出peer，感觉需要用户安装prop-types来检查echart-for-react也不太合理。

**Comment by hustcc** [comment]
嗯，上次发版本，版本号也有问题，应该是1.3.0的，结果改成了1.3.5。
