### ISSUE TITLE
本地更新为1.4.1版本，依赖包仍为1.1.6版本，会出现问题

### ISSUE THREAD

**Issue by lydiafork** [hustcc/echarts-for-react#69]
如题， 
![image](https://user-images.githubusercontent.com/16407920/26911451-302fee1e-4c40-11e7-891e-d27b9f35d173.png)
看了一些源码，不明白这个defalutView是什么

**Comment by SidKwok** [comment]
你可以尝试删除node_module再重新`npm install`

**Comment by lydiafork** [comment]
尝试过了，不行，要是用之前的node_module就不会出错

**Comment by hustcc** [comment]
你的开发环境，版本，引入库方法，代码片段发一下。

**Comment by lydiafork** [comment]
开发环境： dva1.2.1 
引入库： 
![1](https://user-images.githubusercontent.com/16407920/26914535-7c7604f2-4c54-11e7-9f3a-302e17e152ce.png)

代码片段： 

![2](https://user-images.githubusercontent.com/16407920/26914657-1c2d545a-4c55-11e7-9a76-486b59d76f4a.png)

**Comment by hustcc** [comment]
可以看下你 node_modules 目录中 element-resize-event 这个库的版本号是多少吗？

**Comment by hustcc** [comment]
应该是 2.0.9，可以把安装的这个版本删除，然后安装 element-resize-event@2.0.7 版本，然后在试试看。

**Comment by lydiafork** [comment]
可以啦!! 感谢感谢

**Comment by hustcc** [comment]
好的，感谢反馈，已经升级版本 v1.4.2，修复了这个问题。
