### ISSUE TITLE
How to use it in ES5

### ISSUE THREAD

**Issue by wu123456** [hustcc/echarts-for-react#7]
I use `var ReactEcharts = require('echarts-for-react/lib/echarts-for-react');` to include the ReactEcharts,
and then 

```js
var Trend = React.createClass({
	render : function(){
        return (
            <div style={{background: "white", padding: "10px 0"}}>
                <div style={{height:'200px',width:'95%',margin: '0 auto'}}>
	                <ReactEcharts 
					    option={this.getOption()} 
					    style={{height: '200px', width: '100%'}}  /> 

                </div>
            </div>
        );
    },
    getOption : function(){
    	var option = {
    		// 省略
        };

        return option;
    }
});
```

At last I render Trend, the console report 

`bundle.js:91294 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Trend`
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Trend`.`

I wonder where is wrong.

**Comment by hustcc** [comment]
What‘s your `react version` and other env ?

**Comment by wu123456** [comment]
react@15.1.0 
node@0.10.36

**Comment by hustcc** [comment]
可以把你写的代码核心部分贴出来吧？我今天抽空自己测试了一下，是可以运行的o(〃'▽'〃)o

**Comment by wu123456** [comment]
补充一个
echarts-for-react@1.1.2  extraneous

还有我把代码缩减到
```js
'use strict';

var React = require('react');
var ReactDOM = require('react-dom');
var ReactEcharts = require('echarts-for-react/lib/echarts-for-react');

ReactDOM.render(
    <ReactEcharts 
        option={{}} 
        style={{height: '200px', width: '100px'}}  />,
    document.getElementById('example')
);
```

尝试过用webpack 和 watchify 打包，结果都是一样的。
![image](https://cloud.githubusercontent.com/assets/6984735/17475801/5fdedd00-5d8f-11e6-8e20-fbafe315a2c7.png)

option尝试过填入http://echarts.baidu.com/demo.html#area-rainfall 官网demo的数据，也一样显示不出来。

还有试过运行readme的demo，是可以展示出来的。

可能是我哪里用的不对。

**Comment by hustcc** [comment]
运行过了，确实存在问题。必须使用
```js
import ReactEcharts from './lib/echarts-for-react.js';
```
才行，ES5写法确实存在这个问题，之前我理解错了你的问题呢。建议你还是使用上面代码的方法，然后加个一个loader吧~ ^_^~
