### ISSUE TITLE
目前依赖的Echarts（v3.0）不支持barBorderRadius属性

### ISSUE THREAD

**Issue by BerlinChan** [hustcc/echarts-for-react#70]
目前依赖的Echarts（v3.0）不支持barBorderRadius属性，有[文章](http://www.voidcn.com/blog/maxwell0401/article/p-6626557.html)说Echarts

> 3.6.x版本都不能实现圆角效果

我把本项目的依赖的Echarts版本改为3.5.4，经测试是可以支持该属性的

**Comment by hustcc** [comment]
需要表达什么눈_눈，有地方需要改进吗？
