### ISSUE TITLE
在datazoom事件中调用setState导致datazoom拖动异常

### ISSUE THREAD

**Issue by Coodool** [hustcc/echarts-for-react#71]
在datazoom事件的响应函数中调用this.setState后导致datazoom的拖动行为异常，具体表现为datazoom拖动条卡住抖动。

**Comment by SidKwok** [comment]
提供一下echarts-for-react,echarts的版本 还有具体的option

**Comment by Coodool** [comment]
谢谢 @SidKwok  我想我已经找到原因了：
调用setState会刷新组件，导致Echarts按照初始化配置刷新图表，所以datazoom如果触发了setState，那么图表会刷新并重新处于`startValue:9,endValue:15`的位置，表现为拖动条拖不动的现象
```
dataZoom:[{
  show: true,
  type: 'slider',
  startValue: 9,
  endValue: 15,
}], 
```

**Comment by SidKwok** [comment]
这不是echarts-for-react的问题，我先关掉这个issue吧

**Comment by CynthiaNC** [comment]
@Coodool 确实是因为setState 一直set 的是原始的拖动条位置，那如何记录拖动条位置呢？或者如何只set series 里面的data？setOption 的API 好像无法调用，请问你是怎么解决的？

**Comment by CynthiaNC** [comment]
略微找到一个解决，获取dataZoom改变的值，再把它设置到 setState中...
`
onEvents={{
        datazoom: function (e) {
              // get zoom value: start & end
        },
}}
`

**Comment by Coodool** [comment]
@CynthiaNC 抱歉这个项目暂时没在做了，当时的解决方法不记得了，但是可以给你提供几个思路。一方面，可以通过在shouldComponentUpdate里返回false来阻止组件的刷新。另一方面，如果不想影响到React的正常生命周期，可以不设置dataZoom的startValue和endValue的初始值，改为在事件中动态设置，我记得接收到的dataZoom事件里是可以获取到拖条的起始位置的。

**Comment by CynthiaNC** [comment]
@Coodool 是的，目前采取的是获取当前托条的起始位置。谢谢你哈~
还想问一句，现在我是托条 + 动态加载数据。
但当托条的左控制点位置不是0时，图表数据会混乱。
![image](https://user-images.githubusercontent.com/10840720/29815811-898e303a-8ce4-11e7-9d41-166fc569d3f4.png)
![image](https://user-images.githubusercontent.com/10840720/29815837-a44d5c3e-8ce4-11e7-93c3-ef10c97f98ab.png)

如果没有遇到，我再查一下哈，再次感谢您的帮助~

**Comment by Coodool** [comment]
@CynthiaNC 印象中遇到过类似这种数据混乱的问题，你在将数据给到坐标系上时候最好手动指定每个点对应的x的值，不知道我说的能不能帮到你。
``` js
```

**Comment by Coodool** [comment]
@CynthiaNC 印象中遇到过类似这种数据混乱的问题，你在将数据给到坐标系上时候最好手动指定每个点对应的x的值，不知道我说的能不能帮到你。类似下面这样：
``` js
data:[
    ['2016-05', 9653, 8069],
    ['2016-06', 10695, 12634]
]
```
日期数据就是横轴，后面跟的两个数是每个系列的数据。这样显示指定数据与横轴的对应关系可以避免可能出现的混乱问题。

**Comment by CynthiaNC** [comment]
@Coodool 搞！掂！了！啊~内心好激动！！！
确实是这样的，官网上的例子返回的data 是一个个 object, 只把data里面的 object 都改成数组的，就不会有错乱的数据了。谢谢大神，Orz。可以下班了\(≧▽≦)/
