### ISSUE TITLE
getEchartsInstance doesn't work

### ISSUE THREAD

**Issue by wangqianwen0418** [hustcc/echarts-for-react#74]
I want to get the instance of echarts 
I did as it is said in demos/ChartAPIComponent.jsx
but got this error:
> Uncaught TypeError: Cannot read property 'getEchartsInstance' of null

Then I tested your demo on http://git.hust.cc/echarts-for-react/#/echarts/api?_k=pnr18m
when I click the button, the same error happened, as below
<img width="1268" alt="2017-06-15 23 29 23" src="https://user-images.githubusercontent.com/19774198/27188995-8c9aa260-5222-11e7-85cb-8c090c93f23c.png">
I changed several web browsers but still got the same error

Maybe you can check your demo and find out what's going wrong?

**Comment by SidKwok** [comment]
Working on it.

**Comment by dianyouyun** [comment]
是1.4.3引入HOC后的后遗症，ref 要特殊处理了。

**Comment by SidKwok** [comment]
@dianyouyun 谢谢提醒，欢迎pr

**Comment by hustcc** [comment]
@dianyouyun 你那边已经解决了？ref 要经过怎么样的特殊处理？

**Comment by hustcc** [comment]
解决：echarts-for-react@1.4.4
