### ISSUE TITLE
echarts  action  的接口怎么调用

### ISSUE THREAD

**Issue by xiaomijiayou** [hustcc/echarts-for-react#76]
event 有onEVent 接口， 但是action不知道怎么使用

**Comment by hustcc** [comment]
可以看这个 demo 代码：

https://github.com/hustcc/echarts-for-react/blob/master/demo/ChartWithEventComponent.jsx#L78-L82

**Comment by dream-approaching** [comment]
demo找不到了，可以说下action的使用方式吗
