### ISSUE TITLE
echarts初始化时候获取不到容器宽高导致渲染不正确

### ISSUE THREAD

**Issue by swim1986** [hustcc/echarts-for-react#77]
请教一个问题，组件加载时，样式还没完整完成，echarts就已经初始化了，这时候宽高不正确，echarts渲染不正确，请问怎么手动渲染echarts，或者怎么保证获取到正确的宽高。

**Comment by hustcc** [comment]
可以看下你的代码吗？

根据你的描述，不清楚是什么问题。

**Comment by SidKwok** [comment]
这个你可以调用echarts.resize()来处理
