### ISSUE TITLE
请问stateless组件怎么获取echarts对象

### ISSUE THREAD

**Issue by HeNanBing** [hustcc/echarts-for-react#78]

**Comment by hustcc** [comment]
没有区别。

你可以贴一下你的代码写法，可以针对性的说明一下你的问题。

**Comment by HeNanBing** [comment]
对map做了简单的组件，
![mapecharts](https://user-images.githubusercontent.com/13029560/27533810-822f48c6-5a97-11e7-9968-36f04b7c324d.png)
使用的时候用了ref
![ref](https://user-images.githubusercontent.com/13029560/27533831-93151d96-5a97-11e7-8b26-461e6c151b14.png)
，提示warning：
![warning](https://user-images.githubusercontent.com/13029560/27533851-a04b0a20-5a97-11e7-8970-98c7bd66603a.png)
是不是因为我的react版本问题啊
react新手，用的react版本是15.1.0

**Comment by hustcc** [comment]
你需要在mapEcharts中把ref再抛出来，不然你取到的ref是你的mapEcharts组件…

最简单是方法事干掉mapEcharts这层组件。

**Comment by HeNanBing** [comment]
哦，是的了，谢谢指导，辛苦了。
