### ISSUE TITLE
chrome下style 样式问题

### ISSUE THREAD

**Issue by babycannotsay** [hustcc/echarts-for-react#79]
[bug图片](http://chuantu.biz/t5/117/1498477355x3078728410.png)
在Chrome下，ReactEcharts的width置为100%，其子元素为什么是100px。同理width为80%的时候，子元素是80px。缩放一下才恢复正常了。  在firefox下不会有这样的问题。

**Comment by hustcc** [comment]
因为父元素的宽度是100px 吧。这个就是 css 样式问题了。

**Comment by babycannotsay** [comment]
不是哦。 子元素的值 都是跟父元素的值一起的。。但是父元素的符号是%， 子元素的符号时px

**Comment by babycannotsay** [comment]
[截图了你看看](http://chuantu.biz/t5/117/1498480414x3078728410.png)。这样的问题都不好描述，也不好搜。

**Comment by hustcc** [comment]
你贴一下你的大概代码，我看看。

**Comment by babycannotsay** [comment]
不好意思啊，已经下班回来了，代码明天给你看。

**Comment by babycannotsay** [comment]
export default class Echarts extends component {
        getOption = () => {/*option设置*/}
        render() {
            return (
               <div>
                    <ReactEcharts option={this.getOption()} style={{height: 300, width: '100%'}}/>
                </div>
            );
        }
    }

    <TabBar.Item title="echarts">
        <Echarts/>
    </TabBar.Item>


上述的TabBar.Item用的是SaltUI的组件。[这是链接](https://salt-ui.github.io/components/tingle-tab-bar)

**Comment by hustcc** [comment]
应该是 TabBar.Item 往 下面这个 div 中写了 css 属性

```js
<div>
  <ReactEcharts option={this.getOption()} style={{height: 300, width: '100%'}}/>
</div>
```

**Comment by babycannotsay** [comment]
但是火狐浏览器下不存在这个问题。是什么情况。

**Comment by hustcc** [comment]
你可以试试外层不用 TabBar.Item 包裹，然后试试不同浏览器。应该可以确定是这个 UI 库的 js 做了一些适配吧。

**Comment by babycannotsay** [comment]
恩，我这个是一个项目里的问题，，一直没考虑去删除这个，现在删了一下确实是这个问题。。折腾了我一个早上的时间了。 那我是不是可以把这个问题提给SaltUI那边呢，[捂脸]

**Comment by hustcc** [comment]
可以反馈试试，主要看他们组件的 UI，感觉像 TabBar.Item 这种确实需要计算宽度然后设置 style。
