### ISSUE TITLE
折线图横坐标显示不全

### ISSUE THREAD

**Issue by iamstd** [hustcc/echarts-for-react#80]
折线图中，举例来说：横坐标data: [1, 2, 3, 4, 5, 6, 7], 纵坐标data: [4, 2, 3, 4, 5], 我这表需要横坐标全部显示，目前横坐标只显示了1，2，3，4，5的坐标，没有显示6，7的坐标。

**Comment by hustcc** [comment]
感觉是option配置格式问题，你可以看看echarts关于options的配置…

或者把你完整的option贴出来，我抽时间帮你看看。

**Comment by SidKwok** [comment]
建议去echarts提这个issue，echarts-for-react不对传入的option进行处理
