### ISSUE TITLE
按需加载折线图，title和legend无法显示

### ISSUE THREAD

**Issue by garview** [hustcc/echarts-for-react#81]
**问题**
按需加载折线图，title和legend无法显示

**环境**
win8
chrome 59
"react": "^15.4.2",
"echarts": "^3.4.0",
"echarts-for-react": "^1.4.4",

**部分代码**

```js
import ReactEchartsCore from 'echarts-for-react/lib/core';
import echarts from 'echarts/lib/echarts';
import 'echarts/lib/chart/line';
import 'echarts/lib/component/tooltip';
// 省略……
<ReactEchartsCore
                    echarts={echarts}
                    option={this.props.option}
                    style={{height: 300}}
                    onEvents={onEvents}
                />
// 省略……
```

顺带一提，不按需加载的话，legend和title都展示正常

```js
import ReactEcharts from 'echarts-for-react';
// 省略……
<ReactEchartsCore
                    echarts={echarts}
                    option={this.props.option}
                    style={{height: 300}}
                    onEvents={onEvents}
                />
// 省略……
```

ps: 希望能提供个codepen上的模版代码，方便编写在线复现代码。提issue时沟通也更有效率。

**Comment by hustcc** [comment]
需要自己手动引入 legend ？具体模块包括有：[echarts module](https://github.com/ecomfe/echarts/blob/master/index.js)

本项目的网站就是使用的 echarts-for-react，代码在：https://github.com/hustcc/echarts-for-react/tree/master/demo，环境是全的，可以自己本地开发测试的。

**Comment by SidKwok** [comment]
legend和title都是echarts的组件，需要按需引入。建议在使用前看看自己的option里使用了那些部件

**Comment by garview** [comment]
确实就是这个问题。
实在没想到title和legend都是单独的组件，需要单独引入。
谢谢楼上两位。
