### ISSUE TITLE
关于加载问题

### ISSUE THREAD

**Issue by wulv** [hustcc/echarts-for-react#82]
请问一下`echarts-for-react`已经依赖了`echarts`，在使用具体某个图的时候又使用这种方式`require("echarts/map/js/china.js");`按需加载，请问这样最后打包出来的是否是真的按需加载吗？

**Comment by hustcc** [comment]
如果直接使用

```js
require('echarts-for-react');
```

则是全量加载，如果使用：

```js
require('echarts-for-react/lib/core');
```

则是按需加载，所谓按需加载就是按照开发所需去加载，你指定哪些就加载哪些。（虽然会减少包大小，但是会提高开发者难度）
