### ISSUE TITLE
package.json 里对 echarts 的依赖难道不应该放到 peerDependencies 里么？

### ISSUE THREAD

**Issue by mytharcher** [hustcc/echarts-for-react#85]
为何在 dependencies 和 devDependencies 里写 echarts 的依赖？ 理论上 echarts 可以看做用于包装的独立插件，应该可以由用户自由指定版本。

**Comment by hustcc** [comment]
应该是 peer 比较符合，之前也是 peer 的，后来因为升级，出现一些版本兼容问题，所以索性由库来指定 echarts 版本。

其实仔细想想，放到 dependencies 也可以算是合理的。

**Comment by mytharcher** [comment]
个人建议还是放回 peer，对应版本就对应版本，正如 react 和相关插件也是这样处理。由包装器指定 echarts 的版本比较不科学，而且就打包（甚至 CDN）优化来讲，想拆出来也不方便。

**Comment by hustcc** [comment]
Ok，简单评估下，发个大版本。

**Comment by SidKwok** [comment]
我同意@mytharcher

**Comment by ruanyl** [comment]
请问大概什么时候能发布下一个版本? @hustcc

**Comment by hustcc** [comment]
如果的是这个依赖关系更新的问题吧？

今天就发一个 2.0.0 版本修正这个依赖缺陷，正好 echarts 前些天也有更新了。

**Comment by hustcc** [comment]
Done, v2.0.0 published.
