### ISSUE TITLE
提供一个按需加载的其他解决方案

### ISSUE THREAD

**Issue by deot** [hustcc/echarts-for-react#86]
因为项目比较多的用到图表，但是有些地方又没又用到，干脆把整个echarts独立开来按需加载，想到  this.echartsInstance拿到值之后才进行一系列操作，思考结合async的使用，可能需要webpack2.x以上
```js
export default class Core extends React.Component {
    // ...
    componentDidMount = async () => {
        this.echartsInstance = await import("echarts");
        // ...
    }

    // update
    componentDidUpdate = async () => {
        this.echartsInstance = this.echartsInstance || await import("echarts"); // （...可能还要思考下）
        // ...
    }
    // ...
}
```

**Comment by SidKwok** [comment]
我认为这是一个很好的想法。

但是我觉得code spliting这方面应该由用户来完成，用户完全可以用一个wrapper把图标库封装一层，然后动态地`import()`。假如我们把代码切割封装到了库里面，相当于我们强制了用户使用webpack，又强制了用户使用code spliting，这样是相当不友好的。现在`echarts-for-react`提供的core功能就能让用户很好地自定义，按照他们的方式来组织包结构，而且这样自由的方式对于后面构建单独的包是很合适的。
