### ISSUE TITLE
series的参数 数量改变后 再改回来 出现问题

### ISSUE THREAD

**Issue by JevanWu** [hustcc/echarts-for-react#88]
`option`里面`series`参数可以接受任一大小的`Array` 第一次我传入的是length为`1`的`Array` 第二次传入的是length为`4`的`Array` 当我再变回length为`1`的`Array`时 图表上的线还是`4`条（理应变回`1`条）

动态变更图表上的线的数量可能存在bug

想要完成的功能：让用户来选择用那一种方式来查看数据，不同的查看方式，图表上线的数量可能会发生改变

**Comment by SidKwok** [comment]
echarts-for-react不会对传入的option进行处理，具体问题可以到echarts那里提issue

**Comment by clyan** [comment]
> `option`里面`series`参数可以接受任一大小的`Array` 第一次我传入的是length为`1`的`Array` 第二次传入的是length为`4`的`Array` 当我再变回length为`1`的`Array`时 图表上的线还是`4`条（理应变回`1`条）
> 
> 动态变更图表上的线的数量可能存在bug
> 
> 想要完成的功能：让用户来选择用那一种方式来查看数据，不同的查看方式，图表上线的数量可能会发生改变

大佬你还记得这个问题怎么解决么。。我也碰到了

**Comment by JevanWu** [comment]
> > `option`里面`series`参数可以接受任一大小的`Array` 第一次我传入的是length为`1`的`Array` 第二次传入的是length为`4`的`Array` 当我再变回length为`1`的`Array`时 图表上的线还是`4`条（理应变回`1`条）
> > 动态变更图表上的线的数量可能存在bug
> > 想要完成的功能：让用户来选择用那一种方式来查看数据，不同的查看方式，图表上线的数量可能会发生改变
> 
> 大佬你还记得这个问题怎么解决么。。我也碰到了

太久了 不记得了 sorry...

**Comment by clyan** [comment]
> 

好的，没事，谢谢大佬，我在想想办法
