### ISSUE TITLE
使用ReactEcharts时的样式问题

### ISSUE THREAD

**Issue by wuyandefeixue** [hustcc/echarts-for-react#93]
![2017-08-11_144518](https://user-images.githubusercontent.com/17920500/29203564-69c9c1fe-7ea4-11e7-89bd-d7078552a4c0.png)
![2017-08-11_145137](https://user-images.githubusercontent.com/17920500/29203594-9f2b552e-7ea4-11e7-8079-b321288025c7.png)

`.reactEchartHeight{
	height: 400px;
}`
当这样写的时候，第二个ReactEcharts的高度还是默认的300px，为什么？这是不是一个bug？

**Comment by hustcc** [comment]
默认里面有 height 为 300px，设置了 style 的时候，会覆盖掉默认值。但是设置 className 的时候，并没有覆盖掉。所以需要在：

```css
.reactEchartHeight{ height: 400px!important; }
```

**Comment by wuyandefeixue** [comment]
好的，多谢！
