### ISSUE TITLE
散点图 scatter 点击事件提示错误

### ISSUE THREAD

**Issue by kivenZhou** [hustcc/echarts-for-react#94]
使用散点图scatter做点击事件的时候报错Uncaught TypeError: Cannot read property 'axesInfo' of null，使用折线图就没有问题，为什么？有解决方法吗？

**Comment by hustcc** [comment]
我也多次遇到这个问题，很可能是触发 echarts 的什么小 bug，但是完全不影响使用。

**Comment by kivenZhou** [comment]
对，不影响使用，不过作为我们前端来说，看到console里面一堆红就头痛啊，还是希望这个问题可以解决掉！

**Comment by SidKwok** [comment]
可以到echarts里面提一下这个bug
