### ISSUE TITLE
动态加载数据 + dataZoom => 数据显示错乱

### ISSUE THREAD

**Issue by CynthiaNC** [hustcc/echarts-for-react#96]
![image](https://user-images.githubusercontent.com/10840720/29810680-4d608f88-8cd3-11e7-8a0c-eb302c8300c5.png)
视图范围dataZoom控件：
左边的控制点移动过后，只要不在原点上，就会出现数据混乱的现象
移动右边则不会。
由于是动态加载数据，所以不知道是否移动显示与动态加载的显示相冲突。

notMerge: true
lazyUpdate: false
动态更改 option 的数据 data

**Comment by CynthiaNC** [comment]
在大神@Coodool 的帮助下，问题暂时得以解决。
把option 里面的坐标数据全部以`数组`的形式存放，而不是 object。
```
data:[
    ['2016-05', 9653, 8069],
    ['2016-06', 10695, 12634]
]
```
日期数据就是横轴，后面跟的两个数是每个系列的数据。这样显示指定数据与横轴的对应关系可以避免可能出现的混乱问题。

如果有其他的大神也遇到类似的问题，或者有其他的解决方案，请留下您温暖的足迹。

**Comment by hustcc** [comment]
可以尝试在 echarts 项目留下 issue，按照描述应该可能是 echarts 的一个隐藏缺陷。
