### ISSUE TITLE
Typescript : Could not find a declaration file for module 'echarts-for-react' 

### ISSUE THREAD

**Issue by freddymounirk** [hustcc/echarts-for-react#97]
TS7016: Could not find a declaration file for module 'echarts-for-react'. '../node_modules/echarts-for-react/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/echarts-for-react` if it exists or add a new declaration (.d.ts) file containing `declare module 'echarts-for-react';`

and i cant find @types/echarts-for-react , please advise urgently

**Comment by SidKwok** [comment]
Currently we don't support TypeScript, but we will consider implement it in the future.

**Comment by echoulen** [comment]
This can be resolve by [PR#125](https://github.com/hustcc/echarts-for-react/pull/125/files)
