### ISSUE TITLE
如何强制刷新表格？

### ISSUE THREAD

**Issue by RelaxLiu** [hustcc/echarts-for-react#98]
大牛您好，我的需求是这样的，表格初始化会有一个动画，动画执行结束后，想强制清空所有数据，然后再重新加载数据，效果与初始化时一样，类似心电图。心电频率从左至右，到最右侧时，左侧从头开始执行动画，不知道有没有解决思路，如有烦请告知，不胜感激

**Comment by hustcc** [comment]
没有看懂你的需求😂

**Comment by RelaxLiu** [comment]
哈哈，就是一个折线图，数据加载完毕后清空重新加载，一直这么循环。

**Comment by hustcc** [comment]
为啥要清空再重新加载，直接重新加载，然后设置option就可以了。

**Comment by RelaxLiu** [comment]
怎么重新加载啊😂😂😂😂

**Comment by SidKwok** [comment]
[官方文档 `setOption`](http://echarts.baidu.com/api.html#echartsInstance.setOption)

**Comment by RelaxLiu** [comment]
constructor(props){
		super(props);
		this.state = {
			option: this.getEleOption()
		}
	}

  // 循环数据
  fetchNewDate(){
    // 拿不到state中的option
    let option = this.state.option;
    option.series[0].data.length = 0;
    this.setState({
      option: option
    })
  }

拿不到state中的option是什么原因呢。。。

**Comment by SidKwok** [comment]
在`constructor`里写上`this.fetchNewDate.bind(this)`

**Comment by RelaxLiu** [comment]
setOption在react里边如何应用啊，没搞懂，求大神指点 @SidKwok

**Comment by SidKwok** [comment]
setOption是echarts的方法，重新加载数据用的，而你上面的代码没有拿到state里面的option是因为你的this丢了，得bind一下。

**Comment by RelaxLiu** [comment]
恩，this丢了我知道了，setOption方法在react里的使用是没弄明白，能否给一个小的demo

**Comment by SidKwok** [comment]
看一下[echarts-for-react的文档](https://github.com/hustcc/echarts-for-react#4-component-api--echarts-api)，你可以通过ref拿到已生成图表的方法，你把这个方法挂载在自己的`component`上（`this`或者`this.state`上都可以，建议`this`，挂载在`this.state`上有可能造成react不必要的rerender），假如你的方法是`this.echarts_instance`，然后你调用`this.echarts_instance.setOption({/*your option*/})`，就可以使用setOption了。

**Comment by RelaxLiu** [comment]
谢谢大牛。 @SidKwok

**Comment by RelaxLiu** [comment]
获取ref之后，并没有setOption方法是什么原因呢。
```
组件：
<ReactEcharts 
  ref='echartsPie'
  option={this.state.pieOption} 
  xs={ 12 } 
  style={{height: "150px"}}/>

componentDidMount() {
    // 获取ref
    var echartsPie = this.refs.echartsPie;
    // 获取函数
    var PieOption = this.getPieOption();
    console.log(echartsPie,'aaaa');
    // 创建饼图空数组
    var dataPie = [];

    var $this = this;
    // 获取用户的睡眠评分信息
    var data = {
     ........
    };
    // 自己创建的ajax服务
    Ajax(
      '/.....',
      'GET',
      data,
      function(data){
    // 有数据返回都是正确的
        console.log(data.data,'ssss');
        dataPie.push(
         。。。。。
        );
        PieOption.series[0].data.length = 0;
        PieOption.series[0].data.push(dataPie);
        console.log(PieOption);
        // 下边这行控制台提示 not function
        // echartsPie.setOption(PieOption);
        $this.setState({
          pieOption: $this.getPieOption()
        })
      },
      function(error){
        ......
      }
    );
  }
```
@SidKwok

**Comment by hustcc** [comment]
看看你本地的 echarts-for-react 版本是多少？之前有一个版本可能会出现这个问题，换成最新版本应该可以解这个问题。

**Comment by RelaxLiu** [comment]
之前是1.2.x，现在换成了1.4.4，但是还是有这个问题。我的写法有问题么 @hustcc

**Comment by hustcc** [comment]
具体的报错截图发一下。

另外，将 echartsPie 打印出来看看是什么结构。

**Comment by RelaxLiu** [comment]
![image](https://user-images.githubusercontent.com/16301089/30095467-749edf40-9305-11e7-88f4-92d37b91e93f.png)
@ @hustcc

**Comment by hustcc** [comment]
```js
this.refs.echartsPie.getEchartsInstance().setOption()
```

**Comment by RelaxLiu** [comment]
好的，我在学习学习，谢谢大神 @hustcc
